/* Orbuff — in-app guest account privacy + recovery controls */
(function(){
  const copy={
    no:{backup:'SIKKERHETSKOPIER KONTO',recover:'GJENOPPRETT KONTO',button:'SLETT GJESTEKONTO',title:'Slette gjestekonto?',body:'Dette sletter kontoknyttede spilldata på Orbuff-serveren og deaktiverer tilgangen til kontoens Diamond-wallet. Kjøps- og transaksjonsposter kan beholdes pseudonymt når det er nødvendig for refusjon, sikkerhet eller regnskaps-/butikkoppfølging. Lokal spillprogresjon på denne enheten slettes ikke.',confirm:'Skriv SLETT for å bekrefte permanent sletting.',word:'SLETT',cancel:'Sletting avbrutt.',working:'Sletter konto …',success:'Gjestekontoen og kontoknyttede serverdata er slettet. Orbuff starter på nytt.',none:'Ingen gjestekonto er lagret på denne enheten.',fail:'Kunne ikke slette kontoen. Prøv igjen når du er tilkoblet.',backupTitle:'Orbuff-konto sikkerhetskopiert',backupHelp:'Oppbevar Account ID og Recovery Key privat. De kan gjenopprette kontoen og en konto-knyttet Diamond-wallet på en ny installasjon.',copied:'Recovery-informasjonen er kopiert til utklippstavlen.',recoverId:'Skriv inn Orbuff Account ID:',recoverKey:'Skriv inn Recovery Key:',recoverSuccess:'Kontoen ble gjenopprettet. Orbuff starter på nytt.',recoverFail:'Kunne ikke gjenopprette kontoen. Kontroller Account ID og Recovery Key.'},
    en:{backup:'BACK UP ACCOUNT',recover:'RECOVER ACCOUNT',button:'DELETE GUEST ACCOUNT',title:'Delete guest account?',body:'This permanently deletes account-linked game data from the Orbuff server and disables access to the account-linked Diamond wallet. Purchase and transaction records may be retained pseudonymously when needed for refunds, security, accounting, or store reconciliation. Local game progress on this device is not deleted.',confirm:'Type DELETE to confirm permanent deletion.',word:'DELETE',cancel:'Deletion cancelled.',working:'Deleting account …',success:'The guest account and account-linked server data were deleted. Orbuff will restart.',none:'No guest account is stored on this device.',fail:'Could not delete the account. Try again while online.',backupTitle:'Orbuff account backed up',backupHelp:'Keep the Account ID and Recovery Key private. They can recover the account and its account-linked Diamond wallet on a new installation.',copied:'Recovery information was copied to the clipboard.',recoverId:'Enter the Orbuff Account ID:',recoverKey:'Enter the Recovery Key:',recoverSuccess:'Account recovered. Orbuff will restart.',recoverFail:'Could not recover the account. Check the Account ID and Recovery Key.'},
    de:{backup:'KONTO SICHERN',recover:'KONTO WIEDERHERSTELLEN',button:'GASTKONTO LÖSCHEN',title:'Gastkonto löschen?',body:'Dadurch werden kontobezogene Spieldaten dauerhaft vom Orbuff-Server gelöscht und der Zugriff auf das verknüpfte Diamond-Wallet deaktiviert. Kauf- und Transaktionsdaten können pseudonymisiert aufbewahrt werden, wenn dies für Rückerstattungen, Sicherheit, Buchhaltung oder Store-Abgleich erforderlich ist. Lokaler Spielfortschritt wird nicht gelöscht.',confirm:'Gib LÖSCHEN ein, um die dauerhafte Löschung zu bestätigen.',word:'LÖSCHEN',cancel:'Löschung abgebrochen.',working:'Konto wird gelöscht …',success:'Gastkonto und kontobezogene Serverdaten wurden gelöscht. Orbuff wird neu gestartet.',none:'Auf diesem Gerät ist kein Gastkonto gespeichert.',fail:'Konto konnte nicht gelöscht werden. Versuche es online erneut.',backupTitle:'Orbuff-Konto gesichert',backupHelp:'Bewahre Account ID und Recovery Key privat auf. Damit können Konto und verknüpftes Diamond-Wallet auf einer neuen Installation wiederhergestellt werden.',copied:'Wiederherstellungsdaten wurden kopiert.',recoverId:'Orbuff Account ID eingeben:',recoverKey:'Recovery Key eingeben:',recoverSuccess:'Konto wiederhergestellt. Orbuff wird neu gestartet.',recoverFail:'Konto konnte nicht wiederhergestellt werden. Prüfe Account ID und Recovery Key.'},
    es:{backup:'COPIA DE SEGURIDAD',recover:'RECUPERAR CUENTA',button:'ELIMINAR CUENTA DE INVITADO',title:'¿Eliminar cuenta de invitado?',body:'Esto elimina permanentemente los datos de juego vinculados a la cuenta del servidor Orbuff y desactiva el acceso al Diamond wallet vinculado. Los registros de compras y transacciones pueden conservarse de forma seudónima cuando sea necesario para reembolsos, seguridad, contabilidad o conciliación con la tienda. El progreso local no se elimina.',confirm:'Escribe ELIMINAR para confirmar la eliminación permanente.',word:'ELIMINAR',cancel:'Eliminación cancelada.',working:'Eliminando cuenta …',success:'La cuenta de invitado y los datos vinculados se eliminaron. Orbuff se reiniciará.',none:'No hay ninguna cuenta de invitado guardada en este dispositivo.',fail:'No se pudo eliminar la cuenta. Inténtalo de nuevo con conexión.',backupTitle:'Copia de seguridad creada',backupHelp:'Guarda en privado el Account ID y Recovery Key. Permiten recuperar la cuenta y su Diamond wallet vinculado en una instalación nueva.',copied:'Datos de recuperación copiados al portapapeles.',recoverId:'Introduce el Orbuff Account ID:',recoverKey:'Introduce el Recovery Key:',recoverSuccess:'Cuenta recuperada. Orbuff se reiniciará.',recoverFail:'No se pudo recuperar la cuenta. Comprueba Account ID y Recovery Key.'},
    fr:{backup:'SAUVEGARDER LE COMPTE',recover:'RÉCUPÉRER LE COMPTE',button:'SUPPRIMER LE COMPTE INVITÉ',title:'Supprimer le compte invité ?',body:'Cette action supprime définitivement du serveur Orbuff les données de jeu liées au compte et désactive l’accès au Diamond wallet associé. Les enregistrements d’achats et de transactions peuvent être conservés sous forme pseudonymisée si nécessaire pour les remboursements, la sécurité, la comptabilité ou le rapprochement avec la boutique. La progression locale n’est pas supprimée.',confirm:'Saisissez SUPPRIMER pour confirmer la suppression définitive.',word:'SUPPRIMER',cancel:'Suppression annulée.',working:'Suppression du compte …',success:'Le compte invité et les données serveur associées ont été supprimés. Orbuff va redémarrer.',none:'Aucun compte invité n’est enregistré sur cet appareil.',fail:'Impossible de supprimer le compte. Réessayez lorsque vous êtes en ligne.',backupTitle:'Compte Orbuff sauvegardé',backupHelp:'Gardez l’Account ID et la Recovery Key privés. Ils permettent de récupérer le compte et son Diamond wallet associé sur une nouvelle installation.',copied:'Informations de récupération copiées.',recoverId:'Saisissez l’Orbuff Account ID :',recoverKey:'Saisissez la Recovery Key :',recoverSuccess:'Compte récupéré. Orbuff va redémarrer.',recoverFail:'Impossible de récupérer le compte. Vérifiez l’Account ID et la Recovery Key.'}
  };
  function lang(){try{const v=String(localStorage.getItem('skyPuffLang')||'no');return copy[v]?v:'en';}catch{return'en';}}
  function text(){return copy[lang()]||copy.en;}
  function identity(){try{return{token:String(localStorage.getItem('pufflingAccountAuthToken')||''),accountId:String(localStorage.getItem('pufflingAccountId')||''),recoveryKey:String(localStorage.getItem('pufflingAccountRecoveryKey')||'')}}catch{return{token:'',accountId:'',recoveryKey:''}}}
  function apiBase(){const configured=String(window.skyPuffConfig?.gameApiUrl||window.skyPuffConfig?.apiBase||window.SKY_PUFF_GAME_API_URL||'').trim();if(configured)return configured.replace(/\/$/,'');try{const raw=String(window.SKY_PUFF_RACE_WS_URL||'');if(!raw)return'';const u=new URL(raw);u.protocol=u.protocol==='wss:'?'https:':'http:';u.pathname='';u.search='';u.hash='';return u.origin;}catch{return'';}}
  function clearIdentity(){try{for(const key of ['pufflingAccountAuthToken','pufflingAccountId','pufflingAccountRecoveryKey','skyPuffRaceReconnect','pufflingIapReceiptsV1'])localStorage.removeItem(key);}catch{}try{window.PufflingDiamondWallet?.clearLocal?.();}catch{}try{window.SkyPuffRaceTransport?.disconnect?.();window.SkyPuffRaceTransport?.clearStoredIdentity?.();window.SkyPuffRaceTransport?.setAuthToken?.('',{persist:false});}catch{}}
  async function ensureRecoveryIdentity(){const transport=window.SkyPuffRaceTransport;if(!transport?.ensureGuestIdentity)throw new Error('account_recovery_unavailable');let id=await transport.ensureGuestIdentity();if(!id?.recoveryKey&&transport.rotateRecoveryKey)id=await transport.rotateRecoveryKey();if(!id?.accountId||!id?.recoveryKey)throw new Error('account_recovery_unavailable');return id;}
  async function backupGuestAccount(){
    const t=text();try{const id=await ensureRecoveryIdentity();const backup=`Orbuff Account ID: ${id.accountId}\nRecovery Key: ${id.recoveryKey}`;let copied=false;try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(backup);copied=true;}}catch{}alert(`${t.backupTitle}\n\n${backup}\n\n${t.backupHelp}${copied?'\n\n'+t.copied:''}`);return{ok:true,accountId:id.accountId,copied};}catch(e){console.error('[OrbuffAccountRecovery]',e);alert(t.recoverFail);return{ok:false,error:String(e?.message||e)};}
  }
  async function recoverGuestAccount(){
    const t=text(),accountId=prompt(t.recoverId,'');if(accountId===null)return{ok:false,cancelled:true};const recoveryKey=prompt(t.recoverKey,'');if(recoveryKey===null)return{ok:false,cancelled:true};
    try{const transport=window.SkyPuffRaceTransport;if(!transport?.recoverGuestIdentity)throw new Error('account_recovery_unavailable');const out=await transport.recoverGuestIdentity(accountId,recoveryKey);if(!out?.token)throw new Error('account_recovery_failed');try{window.PufflingDiamondWallet?.clearLocal?.();}catch{}alert(t.recoverSuccess);setTimeout(()=>location.reload(),50);return{ok:true,recovered:true,accountId:out.accountId};}catch(e){console.error('[OrbuffAccountRecovery]',e);alert(t.recoverFail);return{ok:false,error:String(e?.message||e)};}
  }
  async function deleteGuestAccount(){
    const t=text(),id=identity();
    if(!id.token){alert(t.none);return{ok:true,alreadyDeleted:true};}
    const base=apiBase();if(!base){alert(t.fail);return{ok:false,error:'account_endpoint_missing'};}
    const typed=prompt(`${t.title}\n\n${t.body}\n\n${t.confirm}`,'');
    if(String(typed||'').trim().toUpperCase()!==t.word.toUpperCase()){if(typed!==null)alert(t.cancel);return{ok:false,cancelled:true};}
    const button=document.getElementById('deleteGuestAccountBtn');if(button){button.disabled=true;button.textContent=t.working;}
    try{
      const response=await fetch(base+'/api/account/me',{method:'DELETE',headers:{accept:'application/json','content-type':'application/json',authorization:`Bearer ${id.token}`},body:JSON.stringify({confirm:'DELETE'})});
      let body={};try{body=await response.json();}catch{}
      if(!response.ok||body?.deleted!==true)throw new Error(body?.error||`http_${response.status}`);
      clearIdentity();alert(t.success);setTimeout(()=>location.reload(),50);return{ok:true,deleted:true};
    }catch(e){console.error('[OrbuffAccountPrivacy]',e);alert(t.fail);if(button){button.disabled=false;button.textContent=t.button;}return{ok:false,error:String(e?.message||e)};}
  }
  function syncLabel(){const t=text(),del=document.getElementById('deleteGuestAccountBtn'),backup=document.getElementById('backupGuestAccountBtn'),recover=document.getElementById('recoverGuestAccountBtn');if(del)del.textContent=t.button;if(backup)backup.textContent=t.backup;if(recover)recover.textContent=t.recover;}
  function mount(){
    const menu=document.querySelector('#diagnosticsMenu .card');if(!menu||document.getElementById('deleteGuestAccountBtn'))return;const close=document.getElementById('closeDiagnostics');
    const backup=document.createElement('button');backup.id='backupGuestAccountBtn';backup.type='button';backup.className='secondary';backup.textContent=text().backup;backup.addEventListener('click',backupGuestAccount);menu.insertBefore(backup,close||null);
    const recover=document.createElement('button');recover.id='recoverGuestAccountBtn';recover.type='button';recover.className='secondary';recover.textContent=text().recover;recover.addEventListener('click',recoverGuestAccount);menu.insertBefore(recover,close||null);
    const button=document.createElement('button');button.id='deleteGuestAccountBtn';button.type='button';button.className='secondary';button.style.cssText='border:2px solid rgba(205,65,65,.6);color:#a52e2e;margin-top:8px';button.textContent=text().button;button.addEventListener('click',deleteGuestAccount);menu.insertBefore(button,close||null);
  }
  window.addEventListener('storage',e=>{if(e.key==='skyPuffLang')syncLabel();});
  document.getElementById('languageSelect')?.addEventListener('change',()=>setTimeout(syncLabel,0));
  mount();
  window.OrbuffAccountPrivacy={deleteGuestAccount,backupGuestAccount,recoverGuestAccount,clearIdentity,identity,apiBase,mount,syncLabel};
})();