(function(){
 const session={startedAt:Date.now(),runStartedAt:0,lastScore:0,lastCoins:0,flags:[],blockedSubmissions:0,signature:''};
 function hash(str){let h=2166136261>>>0;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16).padStart(8,'0');}
 function flag(type,detail){const now=Date.now(),text=String(detail||''),previous=session.flags[session.flags.length-1];if(previous&&previous.type===type&&previous.detail===text&&now-previous.at<10000)return;const item={type,detail:text,at:now,score:Math.floor(Number(score)||0),coins:Math.floor(Number(coins)||0)};session.flags.push(item);if(session.flags.length>40)session.flags.shift();try{localStorage.skyPuffAntiCheatFlags=JSON.stringify(session.flags);}catch(_){}console.warn('[SkyPuff AntiCheat]',item);}
 function clearStoredFlags(){try{localStorage.removeItem('skyPuffAntiCheatFlags');}catch(_){} }
 function beginRun(){session.runStartedAt=Date.now();session.lastScore=0;session.lastCoins=0;session.flags=[];session.blockedSubmissions=0;session.signature=hash([session.runStartedAt,Math.random(),navigator.userAgent,SKY_PUFF_VERSION].join('|'));clearStoredFlags();}
 function acceptTransition(height=score,coinCount=coins){session.lastScore=Math.max(0,Math.floor(Number(height)||0));session.lastCoins=Math.max(0,Math.floor(Number(coinCount)||0));}
 function plausibleRun(height,coinCount){const now=Date.now();const elapsed=Math.max(1,now-(session.runStartedAt||now));const h=Math.max(0,Math.floor(Number(height)||0));const c=Math.max(0,Math.floor(Number(coinCount)||0));const maxHeight=Math.max(2500,Math.floor(elapsed/1000*130+2500));const maxCoins=Math.max(500,Math.floor(h*1.8+1200));let ok=true;if(h>maxHeight){flag('height_rate',`${h}>${maxHeight} in ${elapsed}ms`);ok=false;}if(c>maxCoins){flag('coin_rate',`${c}>${maxCoins} at ${h}m`);ok=false;}if(h<session.lastScore-25){flag('score_rollback',`${h}<${session.lastScore}`);ok=false;}session.lastScore=Math.max(session.lastScore,h);session.lastCoins=Math.max(session.lastCoins,c);return ok;}
 function inspectState(){try{if(!running)return true;let ok=true;if(!Number.isFinite(score)||score<0){flag('invalid_score',score);ok=false;}if(!Number.isFinite(coins)||coins<0){flag('invalid_coins',coins);ok=false;}if(player&&(!Number.isFinite(player.hp)||player.hp<0||player.hp>20)){flag('invalid_hp',player.hp);ok=false;}if(save&&(save.bank<0||save.bank>1e9)){flag('invalid_bank',save.bank);ok=false;}if(Number.isFinite(score)&&Number.isFinite(coins))ok=plausibleRun(score,coins)&&ok;return ok;}catch(e){flag('inspect_error',e.message||e);return false;}}
 function verdict(height,coinCount){const clean=plausibleRun(height,coinCount)&&session.flags.filter(f=>Date.now()-f.at<300000).length<4;const payload=[Math.floor(height||0),Math.floor(coinCount||0),session.runStartedAt,session.signature,SKY_PUFF_VERSION].join('|');return {ok:clean,signature:hash(payload),flags:session.flags.slice(-8),runStartedAt:session.runStartedAt};}
 const previousStartGame=typeof startGame==='function'?startGame:null;if(previousStartGame){startGame=function(){beginRun();return previousStartGame.apply(this,arguments);};}
 setInterval(inspectState,2500);
 window.skyPuffAntiCheat={beginRun,inspectState,verdict,acceptTransition,get status(){return {runStartedAt:session.runStartedAt,flags:session.flags.slice(),blockedSubmissions:session.blockedSubmissions,sessionSignature:session.signature};},noteBlockedSubmission(){session.blockedSubmissions++;}};
 beginRun();
})();
