/* Puffling beta.104 — server-validated Boss Session bridge */
(function(){
 let active=null,starting=null,lastBoss=null,lastHp=null,queue=Promise.resolve(),lastHitSentAt=0;
 const sleep=ms=>new Promise(r=>setTimeout(r,Math.max(0,ms||0)));
 function base(){return String(window.skyPuffConfig?.apiBase||window.SKY_PUFF_GAME_API_URL||'').replace(/\/$/,'')}
 async function token(){try{let t=localStorage.getItem('pufflingAccountAuthToken')||'';if(t)return t;const x=await window.SkyPuffRaceTransport?.ensureGuestIdentity?.();return x?.token||localStorage.getItem('pufflingAccountAuthToken')||''}catch(e){return''}}
 async function post(path,data){const t=await token(),u=base();if(!t||!u)throw new Error('boss_server_unavailable');const r=await fetch(u+path,{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+t,'accept':'application/json'},body:JSON.stringify(data||{})});let b={};try{b=await r.json()}catch(e){}if(!r.ok||!b?.ok){const err=new Error(b?.error||'boss_server_rejected');err.status=r.status;err.code=b?.error||'';throw err}return b}
 function refOf(b){return `${String(b?.id||'').toLowerCase()}:${Math.max(1,Math.floor(Number(b?.tier)||1))}`}
 async function start(b){if(!b||active||starting||typeof bossRushMode!=='undefined'&&bossRushMode)return;const ref=refOf(b);starting=(async()=>{try{const s=await post('/api/boss/session/start',{bossRef:ref});const stillSame=(typeof boss!=='undefined'&&boss&&refOf(boss)===ref)||(!boss&&lastBoss&&refOf(lastBoss)===ref);if(!stillSame)return null;active={sessionId:s.sessionId,nonce:s.nonce,bossRef:ref,maxHp:Number(s.maxHp)||Number(b?.maxHp)||Number(b?.hp)||0,minFightMs:Number(s.minFightMs)||5000,minHitMs:Number(s.minHitMs)||180,startedAt:s.startedAt||new Date().toISOString(),startedAtMs:Date.parse(s.startedAt||'')||Date.now()};lastHitSentAt=0;window.SkyPuffBossSessionClient.active=active;return active}catch(e){active=null;return null}finally{starting=null}})();return starting}
 function hit(damage){if(!active)return;const amount=Math.max(1,Math.min(44,Math.floor(Number(damage)||0))),a={...active};queue=queue.then(async()=>{const pace=(a.minHitMs||180)+25,wait=pace-(Date.now()-lastHitSentAt);if(wait>0)await sleep(wait);for(let attempt=0;attempt<3;attempt++){try{const x=await post('/api/boss/session/hit',{sessionId:a.sessionId,nonce:a.nonce,damage:amount});lastHitSentAt=Date.now();if(active?.sessionId===a.sessionId)active.server=x;return x}catch(e){if(e?.code==='hit_rate_limited'||e?.status===429){await sleep(pace+30);continue}if(attempt<2){await sleep(180*(attempt+1));continue}throw e}}}).catch(e=>{if(active?.sessionId===a.sessionId)active.serverError=String(e?.message||e)});}
 function reportDamage(delta){let left=Math.max(0,Math.round(Number(delta)||0));while(left>0){const chunk=Math.min(44,left);hit(chunk);left-=chunk;}}
 async function finish(defeated){if(starting)await starting.catch(()=>null);const a=active;active=null;lastHp=null;window.SkyPuffBossSessionClient.active=null;if(!a||!defeated)return;await queue;try{let st=await post('/api/boss/session/status',{sessionId:a.sessionId});if(st.bossHp>0)throw new Error('boss_proof_incomplete');if(!st.completedAt){const began=Date.parse(st.startedAt||a.startedAt)||a.startedAtMs||Date.now(),minimum=Number(st.minFightMs||a.minFightMs)||5000,wait=minimum-(Date.now()-began)+100;if(wait>0)await sleep(wait);st=await post('/api/boss/session/status',{sessionId:a.sessionId});}if(!st.completedAt||st.bossHp>0)throw new Error('boss_proof_incomplete');await window.SkyPuffBossPufflingRewards?.rollBossReward?.({...defeated,sessionId:a.sessionId,bossRef:a.bossRef});}catch(e){if(typeof showToast==='function')showToast('Boss beseiret, men Puffling-belønningen kunne ikke verifiseres.')}}
 function tick(){try{const b=typeof boss!=='undefined'?boss:null;if(b){if(!lastBoss||lastBoss.id!==b.id||lastBoss.tier!==b.tier){active=null;starting=null;queue=Promise.resolve();lastHitSentAt=0;lastHp=Number(b.hp);start(b)}else if(active&&Number(b.hp)<Number(lastHp)){const current=Number(b.hp);reportDamage(Number(lastHp)-current);lastHp=current}lastBoss={id:b.id,name:b.name,at:b.at,tier:b.tier};}else if(lastBoss){const d=lastBoss;lastBoss=null;if(typeof bossDefeated!=='undefined'&&bossDefeated)finish(d);else{active=null;starting=null;lastHp=null;}}}catch(e){}requestAnimationFrame(tick)}
 window.SkyPuffBossSessionClient={active:null,start,hit,reportDamage,finish,post};requestAnimationFrame(tick);
})();