(function(){
const KEY='skyPuffBossRushWinsV1',USE='skyPuffUseBossPuffMain';
function wins(){try{return {...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(e){return {}}}
function allWon(){const w=wins();return ['storm','candy','ice','galaxy'].every(id=>!!w[id])}
function text(){const l=typeof lang==='string'?lang:'en';const M={no:['BRUK BOSS PUFF I HOVEDSPILLET','Boss Puff låses opp i hovedspillet når alle 4 bossene er beseiret i Boss Rush.','Boss Puff er nå låst opp i hovedspillet! ✨'],en:['USE BOSS PUFF IN MAIN GAME','Boss Puff unlocks in the main game after defeating all 4 bosses in Boss Rush.','Boss Puff is now unlocked in the main game! ✨'],de:['BOSS PUFF IM HAUPTSPIEL NUTZEN','Boss Puff wird nach Siegen über alle 4 Bosse im Boss Rush freigeschaltet.','Boss Puff ist jetzt im Hauptspiel freigeschaltet! ✨'],es:['USAR BOSS PUFF EN JUEGO PRINCIPAL','Boss Puff se desbloquea tras derrotar a los 4 jefes en Boss Rush.','¡Boss Puff ya está desbloqueado en el juego principal! ✨'],fr:['UTILISER BOSS PUFF DANS LE JEU PRINCIPAL','Boss Puff se débloque après avoir vaincu les 4 boss dans Boss Rush.','Boss Puff est maintenant débloqué dans le jeu principal ! ✨']};return M[l]||M.en}
function addToggle(){if(!allWon()||document.getElementById('bossPuffMainToggle'))return;const host=document.querySelector('#start .card')||document.getElementById('start');if(!host)return;const b=document.createElement('button');b.id='bossPuffMainToggle';b.className='secondary';b.style.marginTop='8px';function sync(){b.textContent=(localStorage.getItem(USE)==='1'?'✓ ':'')+text()[0]}b.onclick=()=>{localStorage.setItem(USE,localStorage.getItem(USE)==='1'?'0':'1');sync()};sync();host.appendChild(b)}
window.skyPuffBossRushProgress={record:function(id){const w=wins(),before=allWon();w[id]=true;localStorage.setItem(KEY,JSON.stringify(w));if(!before&&['storm','candy','ice','galaxy'].every(x=>!!w[x])){localStorage.setItem(USE,'1');showToast(text()[2]);addToggle()}},allWon,wins};
const wait=setInterval(()=>{if(typeof drawPlayer!=='function'||!window.skyPuffBossCreator)return;clearInterval(wait);const old=drawPlayer;drawPlayer=function(){const useMain=!bossRushMode&&allWon()&&localStorage.getItem(USE)==='1';if(useMain){const was=bossRushMode;bossRushMode=true;try{return old()}finally{bossRushMode=was}}return old()};addToggle()},100);
setInterval(addToggle,1000);
})();