window.skyPuffTapState={time:0,x:0,y:0,lockUntil:0};
window.skyPuffWorldBurst={count:0,cooldownUntil:0,lastBoostAt:0};
canvas.style.touchAction='none';
canvas.addEventListener('pointerdown',e=>{active=true;pointerX=e.clientX;const n=performance.now(),tap=window.skyPuffTapState,dt=n-tap.time,dx=e.clientX-tap.x,dy=e.clientY-tap.y,close=Math.hypot(dx,dy)<110;if(dt>=55&&dt<=360&&close&&n>=tap.lockUntil){doBoost();tap.time=0;tap.lockUntil=n+170;}else{tap.time=n;tap.x=e.clientX;tap.y=e.clientY;}lastTap=n;});canvas.addEventListener('pointermove',e=>{if(active)pointerX=e.clientX});canvas.addEventListener('pointerup',()=>active=false);canvas.addEventListener('pointercancel',()=>active=false);
function doBoost(){const now=performance.now();const baseCost=Math.max(20,28-save.upBoost*2);const cost=bossArena?baseCost:Math.max(16,baseCost-4);if(!running||boost<cost)return;let burstStep=1;if(!bossArena){const burst=window.skyPuffWorldBurst;if(now<burst.cooldownUntil)return;if(burst.cooldownUntil&&now>=burst.cooldownUntil){burst.count=0;burst.cooldownUntil=0;burst.lastBoostAt=0;}if(burst.lastBoostAt&&now-burst.lastBoostAt>900)burst.count=0;if(burst.count>=5){burst.cooldownUntil=now+2000;return;}burst.count++;burstStep=burst.count;burst.lastBoostAt=now;if(burst.count>=5)burst.cooldownUntil=now+2000;}boost-=cost;if(!bossArena){const chainBonus=(burstStep-1)*.35;const lift=7.2+save.upBoost*.22+chainBonus;const speedCap=-11.5-(burstStep-1)*.3;player.vy=Math.max(speedCap,Math.min(player.vy,0)-lift);}puffAnim=1.25;screenShake=Math.max(screenShake,4);combo=Math.min(9,combo+1);bestCombo=Math.max(bestCombo,combo);comboTimer=95;if(boss){const over=rainbowOvercharge>0;playerShots.push({x:player.x,y:player.y-player.r-8,vx:0,vy:over?-12:-10.2,r:over?14:11,life:120,damage:(12+save.upBoost*2)*(over?2:1)});for(let i=0;i<(over?16:8);i++)particles.push({x:player.x+(Math.random()-.5)*12,y:player.y-player.r,vx:(Math.random()-.5)*(over?2:1.2),vy:-2-Math.random()*(over?5:3),life:18+Math.random()*12,hue:(i*42)%360,size:3+Math.random()*(over?6:4)});}for(let i=0;i<25;i++)particles.push({x:player.x+(Math.random()-.5)*22,y:player.y+22,vx:(Math.random()-.5)*3,vy:2+Math.random()*4,life:38+Math.random()*18,hue:(i*15)%360,size:4+Math.random()*7});}
function hitPlayer(x,y,r){return Math.hypot(player.x-x,player.y-y)<player.r+r}
function checkMission(){return;}
function nextBossStage(){for(const b of bossStages){if(score>=b.at&&!defeatedBosses[b.id]&&b.at>lastBossTriggerAt)return {...b,tier:1};}const endless=getEndlessBossStage(score);if(!endless||endless.tier<=1||endless.at<=lastBossTriggerAt||score<endless.at)return null;const base=bossStages.find(b=>b.id===endless.id);if(!base)return null;return {...base,...endless,hp:Math.max(base.hp,endlessBossHealth(endless)*24),reward:Math.max(base.reward,endlessBossReward(endless))};}
function cancelBossWarning(){if(window.skyBossWarningTimer){clearTimeout(window.skyBossWarningTimer);window.skyBossWarningTimer=null;}bossWarningActive=false;bossPendingStage=null;if(bossWarningEl)bossWarningEl.style.display='none';}
function triggerBossWarning(stage){if(bossWarningActive||boss||!stage)return;cancelBossWarning();bossWarningActive=true;bossPendingStage=stage;const tier=stage.tier||1;bossWarningTextEl.textContent=tier>1?`${stage.emoji} ${stage.name} • TIER ${tier}`:tr('bossIncoming');bossWarningEl.style.display='block';window.skyBossWarningTimer=setTimeout(()=>{window.skyBossWarningTimer=null;if(bossWarningEl)bossWarningEl.style.display='none';bossWarningActive=false;const s=bossPendingStage;bossPendingStage=null;if(running&&!paused&&s&&!boss&&s.at>lastBossTriggerAt)spawnBoss(s);},1200);}
function spawnBoss(stage){
 window.skyBossEntryState={cameraY,score,playerX:player.x,stageAt:stage.at||score};
 bossArena=true;
 enemies.length=0;
 bossArenaY=Math.max(330,Math.min(H-105,H*.78));
 const bossY=Math.max(105,Math.min(155,H*.20));
 player.y=bossArenaY;player.vy=0;player.vx=0;pointerX=player.x;
 boss={id:stage.id,name:stage.name,x:W/2,y:bossY,hp:stage.hp,maxHp:stage.hp,dir:1,r:stage.id==='galaxy'?48:40,shot:0,reward:stage.reward,emoji:stage.emoji,at:stage.at||0,tier:stage.tier||1};bossSpawned=true;bossWrap.style.display='block';bossBar.style.width='100%';if(bossIdentityEl){bossIdentityEl.style.display='block';bossIdentityNameEl.textContent=`${stage.emoji} ${stage.name}`;bossTierEl.textContent=(stage.tier||1)>1?`• TIER ${stage.tier}`:'';}showToast(`${stage.name}! ${stage.emoji}`);startBossMusic(stage.id);}
