/* Orbuff — late-menu multilingual localization safety net v2.0.
 * Legacy feature modules still use Norwegian internally. This reversible layer
 * keeps player-facing menus aligned with the selected language.
 */
(function(){
 const EXACT=new Map([
  ['Kontrollerer spillstatus…','Checking game status…'],['Laster...','Loading...'],['Laster…','Loading…'],['NULLSTILL BETA-DATA','RESET BETA DATA'],
  ['Grafikkmodus','Graphics mode'],['Auto anbefales. Low reduserer Orbuff-glow og effekter for bedre stabilitet.','Auto is recommended. Low reduces Orbuff glow and effects for better stability.'],
  ['TILBAKE TIL ORBDEX','BACK TO ORBDEX'],['TILBAKE','BACK'],['FUSIONER','FUSE'],['Uoppdaget Orbuff ❔','Undiscovered Orbuff ❔'],
  ['Finn denne Orbuffen for å låse opp detaljene og evolution-formene.','Find this Orbuff to unlock its details and evolution forms.'],
  ['Begge Orbuffs må være Ascended og level 20 før de kan fusion.','Both Orbuffs must be Ascended and level 20 before they can fuse.'],
  ['Begge Orbuffs må være level 20 og Ascended.','Both Orbuffs must be level 20 and Ascended.'],['🔒 Begge Orbuffs må være level 20 og Ascended.','🔒 Both Orbuffs must be level 20 and Ascended.'],
  ['Ingen kjent fusion for denne kombinasjonen.','No known Fusion for this combination.'],['Ingen level 20 Ascended Orbuffs','No level 20 Ascended Orbuffs'],
  ['Klekk egg og legg opptil 3 Orbuffs i OrbVault for å beskytte dem mot Fusion.','Hatch eggs and place up to 3 Orbuffs in the OrbVault to protect them from Fusion.'],
  ['Trykk på en tom plass og velg Orbuffen du vil beskytte.','Tap an empty slot and choose the Orbuff you want to protect.'],
  ['Alle Orbuffs – trykk på en Orbuff under for å legge den i neste ledige plass eller fjerne den fra OrbVault.','All Orbuffs — tap an Orbuff below to place it in the next available slot or remove it from the OrbVault.'],
  ['OPPGRADER ORBVAULT','UPGRADE ORBVAULT'],['ORBVAULT MAX LEVEL ✓','ORBVAULT MAX LEVEL ✓'],['TOM PLASS','EMPTY SLOT'],['LEGG I NESTE LEDIGE','PLACE IN NEXT AVAILABLE SLOT'],['FJERN','REMOVE'],['AVBRYT','CANCEL'],
  ['Standard og vanlige Orbuffs vises først.','Standard and Common Orbuffs are shown first.'],['Ingen ubeskyttede Orbuffs er tilgjengelige.','No unprotected Orbuffs are available.'],['Ingen Orbuffs eid ennå.','No Orbuffs owned yet.'],
  ['Legg en Orbuff i OrbVault for å starte hvile, energilading og passiv XP.','Place an Orbuff in the OrbVault to start resting, recharging energy, and earning passive XP.'],
  ['Kjøpte Mystery Boxer lagres uåpnet i Mystery Vault.','Purchased Mystery Boxes are stored unopened in the Mystery Vault.'],['KJØP DIAMANTER 💎','BUY DIAMONDS 💎'],
  ['Åpne én vanlig Mystery Box, eller kombiner 3 uåpnede boxer til ett garantert Orbuff-egg.','Open one regular Mystery Box, or combine 3 unopened boxes into one guaranteed Orbuff Egg.'],
  ['ÅPNE 1 BOX','OPEN 1 BOX'],['Vanlig Mystery Box','Regular Mystery Box'],['3 Boxer → garantert egg','3 Boxes → guaranteed Egg'],
  ['Odds vises før diamanter brukes. Betalte diamanter verifiseres og lagres på server.','Odds are shown before Diamonds are spent. Paid Diamonds are verified and stored on the server.'],
  ['Saldo:','Balance:'],['Kjøp med ekte penger er deaktivert i web-betaen.','Real-money purchases are disabled in the web beta.'],
  ['Målpriser: 25 💎 = €1 • 75 💎 = €3 • 250 💎 = €9 • 600 💎 = €16. Endelig pris og valuta kommer alltid fra App Store eller Google Play. Diamanter krediteres først etter serververifisering.','Target prices: 25 💎 = €1 • 75 💎 = €3 • 250 💎 = €9 • 600 💎 = €16. Final price and currency always come from the App Store or Google Play. Diamonds are credited only after server verification.'],
  ['Bytt én Orbuff mot én Orbuff. Serveren kontrollerer eierskap og fullfører byttet atomisk.','Trade one Orbuff for one Orbuff. The server verifies ownership and completes the trade atomically.'],
  ['Trade-regler: Starter Orbuffs og Vault-beskyttede kopier kan ikke trades. XP/evolution følger ikke den tradede kopien.','Trade rules: Starter Orbuffs and Vault-protected copies cannot be traded. XP/evolution does not follow the traded copy.'],
  ['LAG TRADE-KODE','CREATE TRADE CODE'],['BLI MED','JOIN'],['TRADE-KODE','TRADE CODE'],['Lag eller bli med i et trade-rom.','Create or join a Trade room.'],['DIN ORBUFF','YOUR ORBUFF'],['Velg Orbuff…','Choose Orbuff…'],['Velg en Orbuff du vil tilby.','Choose an Orbuff to offer.'],['MOTSPILLER','OPPONENT'],['Venter på motspillerens tilbud…','Waiting for the opponent’s offer…'],['GODKJENN BYTTE','ACCEPT TRADE'],['NULLSTILL TILBUD','RESET OFFER'],
  ['FULLFØRT ✅','COMPLETED ✅'],['LÅST 🔒','LOCKED 🔒'],['Ingen reparasjoner registrert','No repairs recorded'],['Ikke tilgjengelig','Unavailable'],['Ingen aktive feil','No active errors'],['Ingen lagret feil','No saved errors'],['Siste runtime-feil','Latest runtime error'],
  ['localStorage tilgjengelig','localStorage available'],['localStorage utilgjengelig','localStorage unavailable'],['Diagnostikkmotor mangler','Diagnostics engine missing'],['Smoke check mangler','Smoke Check missing'],
  ['Lokal beta-profil er forventet i nettlesertest','A local beta profile is expected in browser testing'],['Lokal beta-inventory er forventet før innlogging/synk','Local beta inventory is expected before sign-in/sync'],['Web-beta: ekte kjøp er med vilje deaktivert; aktiveres i signert mobilapp','Web beta: real purchases are intentionally disabled; enabled in the signed mobile app'],
  ['Systemstatus: OK ✅ • Launch-klar','System status: OK ✅ • Launch-ready'],['Aktiv: AUTO (HIGH)','Active: AUTO (HIGH)'],['Aktiv: AUTO (LOW)','Active: AUTO (LOW)']
 ]);
 const RULES=[
  [/\bAlle (?:Pufflings|Orbuffs)\b/g,'All Orbuffs'],
  [/– trykk på en (?:Puffling|Orbuff) under for å legge den i neste ledige plass eller fjerne den fra OrbVault\./g,'— tap an Orbuff below to place it in the next available slot or remove it from the OrbVault.'],
  [/Åpne én vanlig Mystery Box, eller kombiner 3 uåpnede (?:boxer|boxes) til ett garantert (?:Puffling|Orbuff)-egg\./g,'Open one regular Mystery Box, or combine 3 unopened boxes into one guaranteed Orbuff Egg.'],
  [/Starter (?:Pufflings|Orbuffs) og Vault-beskyttede kopier kan ikke trades\. XP\/evolution følger ikke den tradede kopien\./g,'Starter Orbuffs and Vault-protected copies cannot be traded. XP/evolution does not follow the traded copy.'],
  [/\bTrade-regler:/g,'Trade rules:'],[/\bSaldo:/g,'Balance:'],[/\bDu:/g,'You:'],[/\bMotspiller:/g,'Opponent:'],
  [/Ingen reparasjoner registrert/g,'No repairs recorded'],[/Statusdetaljer/g,'Status details'],[/Siste runtime-feil/g,'Latest runtime error'],
  [/\bAktiv:\s*/g,'Active: '],[/\bOppdaget (\d+) \/ (\d+) Orbuffs • Trykk på en Orbuff for detaljer/g,'Discovered $1 / $2 Orbuffs • Tap an Orbuff for details'],
  [/\bIkke oppdaget\b/g,'Not discovered'],[/\bTrykk for detaljer\b/g,'Tap for details'],[/\bTrykk for evolution →\b/g,'Tap for evolution →'],[/\bTRYKK FOR Å SE\b/g,'TAP TO VIEW'],
  [/\bEier x/g,'Owned x'],[/\bEnergi:/g,'Energy:'],[/\bUTMATTET\b/g,'EXHAUSTED'],[/\bLÅST OPP ✓\b/g,'UNLOCKED ✓'],[/\bFORHÅNDSVISNING 🔒\b/g,'PREVIEW 🔒'],[/\bLÅSES OPP SENERE 🔒\b/g,'UNLOCKS LATER 🔒'],
  [/\bGJENOPPLIV\b/g,'REVIVE'],[/\bBRUK REVIVE ORB\b/g,'USE REVIVE ORB'],[/\bAKTIV ORBUFF ✓\b/g,'ACTIVE ORBUFF ✓'],[/\bVELG ORBUFF\b/g,'SELECT ORBUFF'],
  [/Evolution låses opp automatisk på Level 10 og Level 20\./g,'Evolution unlocks automatically at Level 10 and Level 20.'],
  [/OPPGRADER TIL LEVEL (\d+) •/g,'UPGRADE TO LEVEL $1 •'],[/([0-9]+) plasser • \+1 energi hvert ([0-9]+)\. min • ([0-9]+) XP\/time/g,'$1 slots • +1 energy every $2 min • $3 XP/hour'],
  [/Revive Orbs: ([0-9]+) • låses opp som daglig bonus på Level 5/g,'Revive Orbs: $1 • unlock as a daily bonus at Level 5'],[/ • 15 % daglig sjanse/g,' • 15% daily chance'],
  [/PLASS ([0-9]+) • TRYGG 🔒/g,'SLOT $1 • SAFE 🔒'],[/TRYKK • PLASS ([0-9]+)/g,'TAP • SLOT $1'],[/Velg Orbuff til plass ([0-9]+)/g,'Choose an Orbuff for slot $1'],[/EIER x/g,'OWNED x'],[/1 TRYGG 🔒 • ([0-9]+) UTE/g,'1 SAFE 🔒 • $1 OUTSIDE'],
  [/Full energi/g,'Full energy'],[/Neste energi om/g,'Next energy in'],[/Neste ([0-9]+) XP om/g,'Next $1 XP in'],
  [/\bOpptjent: ([0-9]+) • Kjøpt: ([0-9]+)/g,'Earned: $1 • Purchased: $2'],[/\bBOXER\b/g,'BOXES'],[/\bBoxer\b/g,'Boxes'],[/\bboxer\b/g,'boxes'],[/\bgarantert egg\b/g,'guaranteed Egg'],
  [/€([0-9]+) målpris/g,'€$1 target price'],[/€([0-9]+) • pris lastes fra butikk/g,'€$1 • price loading from store'],
  [/([0-9]+)\/7 achievements fullført/g,'$1/7 achievements completed'],[/ i én run/g,' in one run'],[/endless-events fullført/g,'endless events completed'],[/Tier 3\+ boss beseiret/g,'Tier 3+ boss defeated'],[/Beseir en Tier 3\+ boss/g,'Defeat a Tier 3+ boss'],[/boss-seire/g,'boss wins'],
  [/([0-9]+) auto-reparasjoner/g,'$1 automatic repairs'],[/([0-9]+) blokkerte submissions/g,'$1 blocked submissions'],[/Systemstatus: ([0-9]+) feil funnet/g,'System status: $1 errors found'],[/Systemstatus: ([0-9]+) advarsel\(er\)/g,'System status: $1 warning(s)'],[/Spillstatus: OK ✅ • ([0-9]+) launch-punkt gjenstår/g,'Game status: OK ✅ • $1 launch item(s) remain'],
  [/Ikke konfigurert — lokal\/test-ghost brukes/g,'Not configured — local/test ghost is used'],[/Lokal fallback/g,'Local fallback'],[/konto- og serverlagret profil/g,'account and server-stored profile'],
  [/TILBAKE/g,'BACK']
 ];
 const LEXICON=[
  ['Checking game status…','Spielstatus wird geprüft…','Comprobando el estado del juego…','Vérification de l’état du jeu…'],['Loading...','Lädt...','Cargando...','Chargement...'],['Loading…','Lädt…','Cargando…','Chargement…'],
  ['RESET BETA DATA','BETA-DATEN ZURÜCKSETZEN','RESTABLECER DATOS BETA','RÉINITIALISER LES DONNÉES BÊTA'],['Graphics mode','Grafikmodus','Modo gráfico','Mode graphique'],
  ['HIGH','HOCH','ALTO','ÉLEVÉ'],['LOW','NIEDRIG','BAJO','FAIBLE'],['Best value','Bestes Angebot','Mejor oferta','Meilleure offre'],['Trade Orbuffs 🔄','Orbuffs tauschen 🔄','Intercambiar Orbuffs 🔄','Échanger des Orbuffs 🔄'],
  ['Auto is recommended. Low reduces Orbuff glow and effects for better stability.','Auto wird empfohlen. Niedrig reduziert Orbuff-Leuchten und Effekte für mehr Stabilität.','Se recomienda Auto. Bajo reduce el brillo y los efectos de los Orbuffs para mejorar la estabilidad.','Auto est recommandé. Faible réduit la lueur et les effets des Orbuffs pour une meilleure stabilité.'],
  ['BACK TO ORBDEX','ZURÜCK ZUM ORBDEX','VOLVER AL ORBDEX','RETOUR À L’ORBDEX'],['BACK','ZURÜCK','VOLVER','RETOUR'],['FUSE','FUSIONIEREN','FUSIONAR','FUSIONNER'],
  ['Undiscovered Orbuff ❔','Unentdeckter Orbuff ❔','Orbuff no descubierto ❔','Orbuff non découvert ❔'],['Find this Orbuff to unlock its details and evolution forms.','Finde diesen Orbuff, um Details und Evolutionsformen freizuschalten.','Encuentra este Orbuff para desbloquear sus detalles y formas de evolución.','Trouvez cet Orbuff pour débloquer ses détails et ses formes d’évolution.'],
  ['Both Orbuffs must be Ascended and level 20 before they can fuse.','Beide Orbuffs müssen Ascended und Level 20 sein, bevor sie fusionieren können.','Ambos Orbuffs deben ser Ascended y de nivel 20 antes de poder fusionarse.','Les deux Orbuffs doivent être Ascended et de niveau 20 avant de pouvoir fusionner.'],
  ['Both Orbuffs must be level 20 and Ascended.','Beide Orbuffs müssen Level 20 und Ascended sein.','Ambos Orbuffs deben ser de nivel 20 y Ascended.','Les deux Orbuffs doivent être de niveau 20 et Ascended.'],
  ['🔒 Both Orbuffs must be level 20 and Ascended.','🔒 Beide Orbuffs müssen Level 20 und Ascended sein.','🔒 Ambos Orbuffs deben ser de nivel 20 y Ascended.','🔒 Les deux Orbuffs doivent être de niveau 20 et Ascended.'],
  ['No known Fusion for this combination.','Keine bekannte Fusion für diese Kombination.','No hay una fusión conocida para esta combinación.','Aucune fusion connue pour cette combinaison.'],['No level 20 Ascended Orbuffs','Keine Ascended-Orbuffs auf Level 20','No hay Orbuffs Ascended de nivel 20','Aucun Orbuff Ascended de niveau 20'],
  ['Hatch eggs and place up to 3 Orbuffs in the OrbVault to protect them from Fusion.','Brüte Eier aus und lege bis zu 3 Orbuffs in den OrbVault, um sie vor Fusion zu schützen.','Incuba huevos y guarda hasta 3 Orbuffs en el OrbVault para protegerlos de la fusión.','Faites éclore des œufs et placez jusqu’à 3 Orbuffs dans l’OrbVault pour les protéger de la fusion.'],
  ['Tap an empty slot and choose the Orbuff you want to protect.','Tippe auf einen leeren Platz und wähle den Orbuff, den du schützen möchtest.','Toca un espacio vacío y elige el Orbuff que quieres proteger.','Touchez un emplacement vide et choisissez l’Orbuff à protéger.'],
  ['All Orbuffs','Alle Orbuffs','Todos los Orbuffs','Tous les Orbuffs'],['— tap an Orbuff below to place it in the next available slot or remove it from the OrbVault.','— tippe unten auf einen Orbuff, um ihn in den nächsten freien Platz zu legen oder aus dem OrbVault zu entfernen.','— toca un Orbuff de abajo para colocarlo en el siguiente espacio libre o retirarlo del OrbVault.','— touchez un Orbuff ci-dessous pour le placer dans le prochain emplacement libre ou le retirer de l’OrbVault.'],
  ['UPGRADE ORBVAULT','ORBVAULT VERBESSERN','MEJORAR ORBVAULT','AMÉLIORER L’ORBVAULT'],['ORBVAULT MAX LEVEL ✓','ORBVAULT MAXIMALSTUFE ✓','NIVEL MÁXIMO DE ORBVAULT ✓','NIVEAU MAXIMAL DE L’ORBVAULT ✓'],['EMPTY SLOT','LEERER PLATZ','ESPACIO VACÍO','EMPLACEMENT VIDE'],['PLACE IN NEXT AVAILABLE SLOT','IN NÄCHSTEN FREIEN PLATZ LEGEN','COLOCAR EN EL SIGUIENTE ESPACIO LIBRE','PLACER DANS LE PROCHAIN EMPLACEMENT LIBRE'],['REMOVE','ENTFERNEN','RETIRAR','RETIRER'],['CANCEL','ABBRECHEN','CANCELAR','ANNULER'],
  ['Purchased Mystery Boxes are stored unopened in the Mystery Vault.','Gekaufte Mystery Boxes werden ungeöffnet im Mystery Vault aufbewahrt.','Las Mystery Boxes compradas se guardan sin abrir en el Mystery Vault.','Les Mystery Boxes achetées sont conservées non ouvertes dans le Mystery Vault.'],['BUY DIAMONDS 💎','DIAMANTEN KAUFEN 💎','COMPRAR DIAMANTES 💎','ACHETER DES DIAMANTS 💎'],
  ['Open one regular Mystery Box, or combine 3 unopened boxes into one guaranteed Orbuff Egg.','Öffne eine normale Mystery Box oder kombiniere 3 ungeöffnete Boxen zu einem garantierten Orbuff-Ei.','Abre una Mystery Box normal o combina 3 cajas sin abrir para obtener un huevo Orbuff garantizado.','Ouvrez une Mystery Box normale ou combinez 3 boîtes non ouvertes pour obtenir un œuf Orbuff garanti.'],['OPEN 1 BOX','1 BOX ÖFFNEN','ABRIR 1 CAJA','OUVRIR 1 BOÎTE'],['Regular Mystery Box','Normale Mystery Box','Mystery Box normal','Mystery Box normale'],['3 Boxes → guaranteed Egg','3 Boxen → garantiertes Ei','3 cajas → huevo garantizado','3 boîtes → œuf garanti'],
  ['Odds are shown before Diamonds are spent. Paid Diamonds are verified and stored on the server.','Die Chancen werden angezeigt, bevor Diamanten ausgegeben werden. Bezahlte Diamanten werden auf dem Server geprüft und gespeichert.','Las probabilidades se muestran antes de gastar diamantes. Los diamantes de pago se verifican y guardan en el servidor.','Les probabilités sont affichées avant de dépenser des diamants. Les diamants payés sont vérifiés et stockés sur le serveur.'],['Balance:','Guthaben:','Saldo:','Solde :'],
  ['Real-money purchases are disabled in the web beta.','Echtgeldkäufe sind in der Web-Beta deaktiviert.','Las compras con dinero real están desactivadas en la beta web.','Les achats en argent réel sont désactivés dans la bêta web.'],
  ['Target prices: 25 💎 = €1 • 75 💎 = €3 • 250 💎 = €9 • 600 💎 = €16. Final price and currency always come from the App Store or Google Play. Diamonds are credited only after server verification.','Zielpreise: 25 💎 = 1 € • 75 💎 = 3 € • 250 💎 = 9 € • 600 💎 = 16 €. Endpreis und Währung stammen immer aus dem App Store oder von Google Play. Diamanten werden erst nach Serverprüfung gutgeschrieben.','Precios objetivo: 25 💎 = 1 € • 75 💎 = 3 € • 250 💎 = 9 € • 600 💎 = 16 €. El precio final y la moneda siempre proceden de App Store o Google Play. Los diamantes se acreditan tras la verificación del servidor.','Prix indicatifs : 25 💎 = 1 € • 75 💎 = 3 € • 250 💎 = 9 € • 600 💎 = 16 €. Le prix final et la devise proviennent toujours de l’App Store ou de Google Play. Les diamants sont crédités après vérification du serveur.'],
  ['Trade one Orbuff for one Orbuff. The server verifies ownership and completes the trade atomically.','Tausche einen Orbuff gegen einen Orbuff. Der Server prüft den Besitz und schließt den Tausch atomar ab.','Intercambia un Orbuff por otro. El servidor verifica la propiedad y completa el intercambio de forma atómica.','Échangez un Orbuff contre un Orbuff. Le serveur vérifie la propriété et effectue l’échange de façon atomique.'],['Trade rules:','Tauschregeln:','Reglas de intercambio:','Règles d’échange :'],
  ['Starter Orbuffs and Vault-protected copies cannot be traded. XP/evolution does not follow the traded copy.','Starter-Orbuffs und durch den Vault geschützte Exemplare können nicht getauscht werden. XP/Evolution werden nicht mit dem getauschten Exemplar übertragen.','Los Orbuffs iniciales y las copias protegidas por el Vault no se pueden intercambiar. La XP/evolución no acompaña a la copia intercambiada.','Les Orbuffs de départ et les exemplaires protégés par le Vault ne peuvent pas être échangés. L’XP/évolution ne suit pas l’exemplaire échangé.'],
  ['CREATE TRADE CODE','TAUSCHCODE ERSTELLEN','CREAR CÓDIGO DE INTERCAMBIO','CRÉER UN CODE D’ÉCHANGE'],['JOIN','BEITRETEN','UNIRSE','REJOINDRE'],['TRADE CODE','TAUSCHCODE','CÓDIGO DE INTERCAMBIO','CODE D’ÉCHANGE'],['Create or join a Trade room.','Erstelle einen Tauschraum oder tritt einem bei.','Crea una sala de intercambio o únete a una.','Créez ou rejoignez une salle d’échange.'],['YOUR ORBUFF','DEIN ORBUFF','TU ORBUFF','VOTRE ORBUFF'],['Choose Orbuff…','Orbuff wählen…','Elegir Orbuff…','Choisir un Orbuff…'],['Choose an Orbuff to offer.','Wähle einen Orbuff als Angebot.','Elige un Orbuff para ofrecer.','Choisissez un Orbuff à proposer.'],['OPPONENT','GEGNER','RIVAL','ADVERSAIRE'],['Waiting for the opponent’s offer…','Warte auf das Angebot des Gegners…','Esperando la oferta del rival…','En attente de l’offre de l’adversaire…'],['You:','Du:','Tú:','Vous :'],['Opponent:','Gegner:','Rival:','Adversaire :'],['ACCEPT TRADE','TAUSCH ANNEHMEN','ACEPTAR INTERCAMBIO','ACCEPTER L’ÉCHANGE'],['RESET OFFER','ANGEBOT ZURÜCKSETZEN','RESTABLECER OFERTA','RÉINITIALISER L’OFFRE'],
  ['COMPLETED ✅','ABGESCHLOSSEN ✅','COMPLETADO ✅','TERMINÉ ✅'],['LOCKED 🔒','GESPERRT 🔒','BLOQUEADO 🔒','VERROUILLÉ 🔒'],['No repairs recorded','Keine Reparaturen erfasst','No se registraron reparaciones','Aucune réparation enregistrée'],['Unavailable','Nicht verfügbar','No disponible','Indisponible'],['No active errors','Keine aktiven Fehler','No hay errores activos','Aucune erreur active'],['No saved errors','Keine gespeicherten Fehler','No hay errores guardados','Aucune erreur enregistrée'],['Latest runtime error','Letzter Laufzeitfehler','Último error de ejecución','Dernière erreur d’exécution'],['Status details','Statusdetails','Detalles del estado','Détails du statut'],
  ['localStorage available','localStorage verfügbar','localStorage disponible','localStorage disponible'],['localStorage unavailable','localStorage nicht verfügbar','localStorage no disponible','localStorage indisponible'],['Diagnostics engine missing','Diagnosemodul fehlt','Falta el motor de diagnóstico','Moteur de diagnostic manquant'],['Smoke Check missing','Smoke Check fehlt','Falta Smoke Check','Smoke Check manquant'],
  ['A local beta profile is expected in browser testing','Beim Browsertest wird ein lokales Beta-Profil erwartet','En las pruebas del navegador se espera un perfil beta local','Un profil bêta local est attendu lors des tests dans le navigateur'],['Local beta inventory is expected before sign-in/sync','Vor Anmeldung/Synchronisierung wird ein lokales Beta-Inventar erwartet','Se espera un inventario beta local antes de iniciar sesión o sincronizar','Un inventaire bêta local est attendu avant la connexion ou la synchronisation'],['Web beta: real purchases are intentionally disabled; enabled in the signed mobile app','Web-Beta: Echtgeldkäufe sind absichtlich deaktiviert; sie werden in der signierten mobilen App aktiviert','Beta web: las compras reales están desactivadas intencionadamente; se activan en la aplicación móvil firmada','Bêta web : les achats réels sont volontairement désactivés ; ils sont activés dans l’application mobile signée'],['System status: OK ✅ • Launch-ready','Systemstatus: OK ✅ • Startbereit','Estado del sistema: OK ✅ • Listo para lanzamiento','État du système : OK ✅ • Prêt au lancement']
 ];
 const LANG_INDEX={de:1,es:2,fr:3};
 const LOCAL_EXACT=Object.fromEntries(Object.entries(LANG_INDEX).map(([code,index])=>[code,new Map(LEXICON.map(row=>[row[0],row[index]]))]));
 const LOCAL_RULES={
  de:[[/^Active:\s*/g,'Aktiv: '],[/\bBalance:/g,'Guthaben:'],[/\bYou:/g,'Du:'],[/\bOpponent:/g,'Gegner:'],[/^(\d+) BOXES(?=\s|$)/g,'$1 BOXEN'],[/^(\d+) BOX(?=\s|$)/g,'$1 BOX'],[/(\d+) Coins/g,'$1 Münzen'],[/^(\d+) slots • \+1 energy every (\d+) min • (\d+) XP\/hour$/g,'$1 Plätze • +1 Energie alle $2 Min. • $3 XP/Stunde'],[/^UPGRADE TO LEVEL (\d+) •/g,'AUF LEVEL $1 VERBESSERN •'],[/^TAP • SLOT (\d+)$/g,'TIPPEN • PLATZ $1'],[/^(\d+)\/7 achievements completed$/g,'$1/7 Erfolge abgeschlossen'],[/ in one run/g,' in einem Lauf'],[/endless events completed/g,'Endlos-Events abgeschlossen'],[/Defeat a Tier 3\+ boss/g,'Besiege einen Boss der Stufe 3+'],[/boss wins/g,'Boss-Siege'],[/(\d+) automatic repairs/g,'$1 automatische Reparaturen'],[/(\d+) blocked submissions/g,'$1 blockierte Übermittlungen'],[/€(\d+) target price/g,'€$1 Zielpreis'],[/^BOXES$/g,'BOXEN'],[/^Boxes$/g,'Boxen'],[/^boxes$/g,'Boxen']],
  es:[[/^Active:\s*/g,'Activo: '],[/\bBalance:/g,'Saldo:'],[/\bYou:/g,'Tú:'],[/\bOpponent:/g,'Rival:'],[/^(\d+) BOXES(?=\s|$)/g,'$1 CAJAS'],[/^(\d+) BOX(?=\s|$)/g,'$1 CAJA'],[/(\d+) Coins/g,'$1 monedas'],[/^(\d+) slots • \+1 energy every (\d+) min • (\d+) XP\/hour$/g,'$1 espacios • +1 de energía cada $2 min • $3 XP/hora'],[/^UPGRADE TO LEVEL (\d+) •/g,'MEJORAR AL NIVEL $1 •'],[/^TAP • SLOT (\d+)$/g,'TOCAR • ESPACIO $1'],[/^(\d+)\/7 achievements completed$/g,'$1/7 logros completados'],[/ in one run/g,' en una partida'],[/endless events completed/g,'eventos infinitos completados'],[/Defeat a Tier 3\+ boss/g,'Derrota a un jefe de nivel 3+'],[/boss wins/g,'victorias contra jefes'],[/(\d+) automatic repairs/g,'$1 reparaciones automáticas'],[/(\d+) blocked submissions/g,'$1 envíos bloqueados'],[/€(\d+) target price/g,'€$1 precio objetivo'],[/^BOXES$/g,'CAJAS'],[/^Boxes$/g,'Cajas'],[/^boxes$/g,'cajas']],
  fr:[[/^Active:\s*/g,'Actif : '],[/\bBalance:/g,'Solde :'],[/\bYou:/g,'Vous :'],[/\bOpponent:/g,'Adversaire :'],[/^(\d+) BOXES(?=\s|$)/g,'$1 BOÎTES'],[/^(\d+) BOX(?=\s|$)/g,'$1 BOÎTE'],[/(\d+) Coins/g,'$1 pièces'],[/^(\d+) slots • \+1 energy every (\d+) min • (\d+) XP\/hour$/g,'$1 emplacements • +1 énergie toutes les $2 min • $3 XP/heure'],[/^UPGRADE TO LEVEL (\d+) •/g,'AMÉLIORER AU NIVEAU $1 •'],[/^TAP • SLOT (\d+)$/g,'TOUCHER • EMPLACEMENT $1'],[/^(\d+)\/7 achievements completed$/g,'$1/7 succès terminés'],[/ in one run/g,' en une partie'],[/endless events completed/g,'événements sans fin terminés'],[/Defeat a Tier 3\+ boss/g,'Battez un boss de niveau 3+'],[/boss wins/g,'victoires contre les boss'],[/(\d+) automatic repairs/g,'$1 réparations automatiques'],[/(\d+) blocked submissions/g,'$1 envois bloqués'],[/€(\d+) target price/g,'€$1 prix indicatif'],[/^BOXES$/g,'BOÎTES'],[/^Boxes$/g,'Boîtes'],[/^boxes$/g,'boîtes']]
 };
 const originalText=new WeakMap(),originalAttr=new WeakMap();let scheduled=false;
 function language(){const value=document.getElementById('languageSelect')?.value;return ['no','en','de','es','fr'].includes(value)?value:'en'}
 function exact(map,value){const match=String(value??'').match(/^(\s*)([\s\S]*?)(\s*)$/),hit=map?.get(match?.[2]);return hit==null?value:`${match[1]}${hit}${match[3]}`}
 function translated(value,target=language()){let out=exact(EXACT,value);for(const [pattern,replacement] of RULES)out=out.replace(pattern,replacement);out=exact(LOCAL_EXACT[target],out);for(const [pattern,replacement] of LOCAL_RULES[target]||[])out=out.replace(pattern,replacement);return out}
 function textNodes(root,out=[]){for(const node of root?.childNodes||[]){if(node.nodeType===3)out.push(node);else if(node.nodeType===1)textNodes(node,out)}return out}
 function syncText(node,target){const record=originalText.get(node),localized=target!=='no';if(localized){if(record&&record.target===target&&node.nodeValue===record.translated)return;const source=record&&(node.nodeValue===record.translated||node.nodeValue===record.original)?record.original:node.nodeValue,value=translated(source,target);originalText.set(node,{original:source,translated:value,target});if(value!==node.nodeValue)node.nodeValue=value;}else if(record){if(node.nodeValue===record.translated)node.nodeValue=record.original;originalText.delete(node)}}
 function syncAttr(el,name,target){const key=`${name}`;let records=originalAttr.get(el);if(!records){records={};originalAttr.set(el,records)}const record=records[key],localized=target!=='no';if(localized){const current=el.getAttribute(name);if(current==null)return;if(record&&record.target===target&&current===record.translated)return;const source=record&&(current===record.translated||current===record.original)?record.original:current,value=translated(source,target);records[key]={original:source,translated:value,target};if(value!==current)el.setAttribute(name,value);}else if(record){if(el.getAttribute(name)===record.translated)el.setAttribute(name,record.original);delete records[key]}}
 function sync(){scheduled=false;const target=language();for(const root of document.querySelectorAll('.overlay[id]')){for(const node of textNodes(root))syncText(node,target);for(const el of root.querySelectorAll('[placeholder],[aria-label],[title]'))for(const name of ['placeholder','aria-label','title'])syncAttr(el,name,target)}}
 function schedule(){if(scheduled)return;scheduled=true;setTimeout(sync,0)}
 const select=document.getElementById('languageSelect');select?.addEventListener('change',()=>{sync();setTimeout(sync,60);setTimeout(sync,300)});
 if(typeof MutationObserver==='function')new MutationObserver(schedule).observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['placeholder','aria-label','title']});
 [0,120,500,1200].forEach(ms=>setTimeout(sync,ms));window.OrbuffMenuLocalization={sync,translated};
})();
