function update(dt){
 const s=Math.min(dt/16.67,1.6);
 if(screenShake>0)screenShake=Math.max(0,screenShake-.45*s);
 if(Math.abs(puffAnim)>.01)puffAnim*=Math.pow(.82,s); else puffAnim=0;
 if(bossFlash>0)bossFlash-=s;
 for(const sp of skySparkles){sp.tw+=.035*s;sp.y+=.03*s;if(sp.y>H+5)sp.y=-5;}
 const target=(pointerX-player.x)*.035;player.vx+=target*s;player.vx*=Math.pow(.86,s);player.vx=Math.max(-7.5,Math.min(7.5,player.vx));player.x+=player.vx*s;
 if(bossArena&&boss){player.y=bossArenaY;player.vy=0;}
 player.vy+=.42*s;if(!bossArena)player.y+=player.vy*s; else player.y=bossArenaY;player.rot=player.vx*.035;
 if(player.x<-player.r)player.x=W+player.r;if(player.x>W+player.r)player.x=-player.r;
 if(invuln>0)invuln-=s;if(shield>0)shield-=s;if(magnet>0)magnet-=s;if(mega>0)mega-=s;player.r=mega>0?38:28;
 if(!bossArena&&player.vy>0){for(const p of platforms){const py=p.y-cameraY,prev=(player.y-player.vy*s)+player.r,curr=player.y+player.r;if(!p.used&&prev<=py+4&&curr>=py&&player.x+player.r*.72>p.x&&player.x-player.r*.72<p.x+p.w){player.y=py-player.r;player.vy=-10.6;puffAnim=-1;boost=Math.min(100,boost+7);combo=Math.min(9,combo+1);bestCombo=Math.max(bestCombo,combo);comboTimer=80;if(p.breakable)p.used=true}}}
 const ceiling=H*.40;if(player.y<ceiling){const sh=ceiling-player.y;cameraY-=sh;player.y=ceiling;score=Math.max(score,Math.floor((-cameraY)/10));scoreEl.textContent=score}
 let minY=Infinity;for(const p of platforms){if(p.move)p.x+=Math.sin(performance.now()/650+p.phase)*.4*s;minY=Math.min(minY,p.y)}while(minY-cameraY>-140){minY-=70+Math.random()*38;addPlatform(minY)}
 for(const e of enemies){e.x+=e.vx*s;e.y+=Math.sin(performance.now()/300+e.phase)*.15*s;if(e.x<20||e.x>W-20)e.vx*=-1;const sy=e.y-cameraY;if(hitPlayer(e.x,sy,e.r)&&invuln<=0){if(shield>0){shield=0;invuln=55;showToast(tr('shieldSaved'))}else if(mega>0){invuln=35;showToast(tr('megaSmash'))}else{player.hp--;hpEl.textContent=player.hp;invuln=75;player.vy=-7;combo=1;if(player.hp<=0)return endGame()}}}
 for(const c of coinItems){const sy=c.y-cameraY;c.spin+=.08*s;const range=150+save.upMagnet*25;if(magnet>0&&!c.taken){const dx=player.x-c.x,dy=player.y-sy,d=Math.hypot(dx,dy);if(d<range){c.x+=dx*.08*s;c.y+=(dy*.08*s)}}if(!c.taken&&hitPlayer(c.x,sy,c.r)){c.taken=true;coins+=combo;coinsEl.textContent=coins;boost=Math.min(100,boost+10);combo=Math.min(9,combo+1);bestCombo=Math.max(bestCombo,combo);comboTimer=90}}
 for(const p of powerups){const sy=p.y-cameraY;if(!p.taken&&hitPlayer(p.x,sy,14)){p.taken=true;if(p.type==='shield'){shield=480;showToast(tr('shield'))}if(p.type==='magnet'){magnet=520+save.upMagnet*100;showToast(tr('magnet'))}if(p.type==='mega'){mega=420;showToast(tr('mega'))}}}
 if(!boss&&!bossWarningActive){const stage=nextBossStage();if(stage)triggerBossWarning(stage);}
 if(boss){let bossSpeed=1.4;if(boss.id==='candy')bossSpeed=1.7;if(boss.id==='ice')bossSpeed=1.15;if(boss.id==='galaxy')bossSpeed=2.0;boss.x+=boss.dir*bossSpeed*s;if(boss.x<55||boss.x>W-55)boss.dir*=-1;boss.shot+=s;if(boss.shot>92){boss.shot=0;const dx=player.x-boss.x,dy=player.y-boss.y;const len=Math.max(1,Math.hypot(dx,dy));const speed=boss.id==='galaxy'?5.3:boss.id==='ice'?4.8:boss.id==='candy'?4.6:4.9;bossShots.push({x:boss.x,y:boss.y+30,vx:(dx/len)*speed,vy:(dy/len)*speed,r:boss.id==='galaxy'?13:11,type:boss.id,life:180});}if(hitPlayer(boss.x,boss.y,boss.r)&&invuln<=0){player.hp--;hpEl.textContent=player.hp;invuln=90;screenShake=10;if(player.hp<=0)return endGame();}}
 for(const shot of playerShots){shot.x+=shot.vx*s;shot.y+=shot.vy*s;shot.life-=s;if(boss&&Math.hypot(shot.x-boss.x,shot.y-boss.y)<shot.r+boss.r){shot.life=0;boss.hp-=shot.damage;bossFlash=7;screenShake=Math.max(screenShake,5);bossBar.style.width=Math.max(0,boss.hp/boss.maxHp*100)+'%';showToast(tr('bossHit'));for(let i=0;i<14;i++){particles.push({x:shot.x,y:shot.y,vx:(Math.random()-.5)*4,vy:(Math.random()-.5)*4,life:24,hue:(i*25)%360,size:3+Math.random()*4});}if(boss.hp<=0){if(bossRushMode){finishBossRushWin();return;}const defeatedId=boss.id,reward=boss.reward,bossName=boss.name;defeatedBosses[defeatedId]=true;bossDefeated=true;boss=null;bossSpawned=false;bossArena=false;player.vy=-10.8;puffAnim=1;bossWrap.style.display='none';stopBossMusic(true);boss=null;running=true;save.bank+=reward;persist();unlockBossCosmetic(defeatedId);showToast(tr('bossDefeated',{name:bossName,reward}));}}}
 playerShots=playerShots.filter(q=>q.life>0&&q.x>-30&&q.x<W+30&&q.y>-60&&q.y<H+60);
 for(const shot of bossShots){shot.x+=shot.vx*s;shot.y+=shot.vy*s;shot.life-=s;if(hitPlayer(shot.x,shot.y,shot.r)&&invuln<=0){shot.life=0;if(shield>0){shield=0;invuln=55;showToast(tr('shieldSaved'));}else if(mega>0){invuln=35;showToast(tr('megaSmash'));}else{player.hp--;hpEl.textContent=player.hp;invuln=75;player.vy=-6;combo=1;screenShake=8;if(player.hp<=0)return endGame();}}}
 bossShots=bossShots.filter(q=>q.life>0&&q.x>-40&&q.x<W+40&&q.y>-80&&q.y<H+80);
 if(comboTimer>0){comboTimer-=s;comboEl.textContent='COMBO x'+combo;comboEl.style.opacity=1;comboEl.style.transform='translateX(-50%) scale(1)'}else{combo=1;comboEl.style.opacity=0;comboEl.style.transform='translateX(-50%) scale(.8)'}
 boost=Math.min(100,boost+.035*s);boostEl.style.width=boost+'%';
 for(const q of particles){q.x+=q.vx*s;q.y+=q.vy*s;q.life-=s}particles=particles.filter(q=>q.life>0);
 platforms=platforms.filter(p=>p.y-cameraY<H+120&&!p.used);coinItems=coinItems.filter(c=>c.y-cameraY<H+100&&!c.taken);powerups=powerups.filter(p=>p.y-cameraY<H+100&&!p.taken);enemies=enemies.filter(e=>e.y-cameraY<H+130);
 checkMission();if(player.y-player.r>H+90)endGame();
}
function endGame(){bossWarningEl.style.display='none';bossWarningActive=false;bossPendingStage=null;bossArena=false;if(!running)return;running=false;const gain=Math.floor(coins*(1+save.upCoin*.15));save.bank+=gain;save.total+=score;save.best=Math.max(save.best,score);if(score<300)save.streak=0;persist();submitOnlineScore(score);finalScoreEl.textContent=score;finalCoinsEl.textContent=coins;finalComboEl.textContent=bestCombo;bankGainEl.textContent=gain;gameOverEl.style.display='flex'}
function drawCloud(x,y,s,a=.3){ctx.save();ctx.globalAlpha=a;const g=ctx.createLinearGradient(x,y-30*s,x,y+28*s);g.addColorStop(0,'#ffffff');g.addColorStop(1,'#dff4ff');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,26*s,0,Math.PI*2);ctx.arc(x+28*s,y-8*s,34*s,0,Math.PI*2);ctx.arc(x+60*s,y,25*s,0,Math.PI*2);ctx.fill();ctx.globalAlpha=a*.22;ctx.fillStyle='#4fa6d8';ctx.beginPath();ctx.ellipse(x+30*s,y+18*s,43*s,10*s,0,0,Math.PI*2);ctx.fill();ctx.restore();}
function drawTrail(){const sk=skins[save.skin];const trail=save.trail==='auto'?sk.trail:save.trail;if(player.vy>=0)return;if(trail==='rainbow'||trail==='candy'||trail==='mint'||trail==='gold'||trail==='storm'||trail==='ice'||trail==='galaxy'||trail==='fire'||trail==='royal'||trail==='neon'||trail==='aurora'){let cols=['#ff4d6d','#ff9f1c','#ffe66d','#4cd97b','#4dabf7','#8b5cf6'];if(trail==='mint')cols=['#8fffe0','#4de0bd','#22bfa0','#9affef','#5fe8ce','#c8fff4'];if(trail==='gold')cols=['#fff1a8','#ffd84d','#ffbd2e','#ffe77a','#ffc24b','#fff4bf'];if(trail==='storm')cols=['#d8e0ea','#8da0b5','#67798b','#c6d1dc','#7e91a3','#edf2f7'];if(trail==='ice')cols=['#e8fbff','#aeeeff','#74d8ff','#d2f6ff','#8be6ff','#ffffff'];if(trail==='galaxy')cols=['#7b61ff','#a55eea','#5f27cd','#00d2d3','#c56cf0','#341f97'];if(trail==='fire')cols=['#fff36b','#ffb12b','#ff6b2b','#ff3b30','#ff8d4d','#ffd166'];if(trail==='royal')cols=['#d8c6ff','#9b7cff','#6c4cff','#f0e7ff','#ad95ff','#ffffff'];if(trail==='neon')cols=['#00fff0','#ff00f5','#8cff00','#00a8ff','#ffea00','#ff3b81'];if(trail==='aurora')cols=['#6fffe9','#5eead4','#8b5cf6','#60a5fa','#34d399','#a7f3d0'];if(trail==='candy')cols=['#ff9bd6','#ffd2f0','#ff7ac8','#b794ff','#9ee7ff','#ffffff'];for(let i=0;i<6;i++){ctx.strokeStyle=cols[i%cols.length];ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-12+i*5,22);ctx.quadraticCurveTo(-15+i*4,36,(-18+i*5)+Math.sin(performance.now()/120+i)*5,55);ctx.stroke();}}else if(trail==='hearts'||trail==='stars'){ctx.font='18px Arial';ctx.textAlign='center';for(let i=0;i<4;i++){ctx.globalAlpha=.75-i*.15;ctx.fillText(trail==='hearts'?'💖':'⭐',(i-1.5)*11,32+i*11);}ctx.globalAlpha=1;}}
function drawHat(){const h=save.hat;if(h==='none')return;ctx.save();ctx.translate(0,-29);ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='26px Arial';if(h==='crown')ctx.fillText('👑',0,-2);if(h==='propeller')ctx.fillText('🚁',0,-2);if(h==='halo')ctx.fillText('😇',0,-2);if(h==='wizard')ctx.fillText('🧙',0,-2);if(h==='stormCrown')ctx.fillText('⚡',0,-2);if(h==='candyCrown')ctx.fillText('🍭',0,-2);if(h==='iceCrown')ctx.fillText('❄️',0,-2);if(h==='galaxyCrown')ctx.fillText('👑',0,-2);ctx.restore();}
function drawFace(){ctx.fillStyle=skins[save.skin].eye;if(save.face==='sleepy'){ctx.strokeStyle=skins[save.skin].eye;ctx.lineWidth=2.4;ctx.beginPath();ctx.arc(-9,3,5,.15*Math.PI,.85*Math.PI);ctx.stroke();ctx.beginPath();ctx.arc(10,3,5,.15*Math.PI,.85*Math.PI);ctx.stroke();ctx.beginPath();ctx.arc(1,8,5,1.1*Math.PI,1.9*Math.PI);ctx.stroke();}else if(save.face==='happy'){ctx.strokeStyle=skins[save.skin].eye;ctx.lineWidth=2.4;ctx.beginPath();ctx.arc(-9,3,5,.1*Math.PI,.9*Math.PI);ctx.stroke();ctx.beginPath();ctx.arc(10,3,5,.1*Math.PI,.9*Math.PI);ctx.stroke();ctx.beginPath();ctx.arc(1,6,9,.1*Math.PI,.9*Math.PI);ctx.stroke();}else if(save.face==='cool'){ctx.fillStyle='#1d2530';ctx.fillRect(-18,-2,14,7);ctx.fillRect(4,-2,14,7);ctx.fillRect(-4,0,8,2);ctx.strokeStyle=skins[save.skin].eye;ctx.lineWidth=2.2;ctx.beginPath();ctx.arc(1,8,6,.05*Math.PI,.95*Math.PI);ctx.stroke();}else{ctx.beginPath();ctx.arc(-9,2,3.8,0,Math.PI*2);ctx.arc(10,2,3.8,0,Math.PI*2);ctx.fill();ctx.strokeStyle=skins[save.skin].eye;ctx.lineWidth=2.2;ctx.beginPath();ctx.arc(1,7,7,.1*Math.PI,.9*Math.PI);ctx.stroke();}}
