function reset(){
 stopBossMusic(false);bossRushMode=false;bossRushSelected=null;lastBossTriggerAt=0;cameraY=0;score=0;coins=0;boost=100;combo=1;bestCombo=1;comboTimer=0;invuln=0;shield=0;magnet=0;mega=0;boss=null;bossSpawned=false;bossDefeated=false;bossWarningActive=false;bossPendingStage=null;bossArena=false;bossArenaY=0;defeatedBosses={storm:false,candy:false,ice:false,galaxy:false};
 player={x:W/2,y:H*.68,vx:0,vy:-9,r:28,rot:0,hp:3+save.upHealth};
 platforms=[];coinItems=[];clouds=[];enemies=[];powerups=[];particles=[];playerShots=[];bossShots=[];skySparkles=[];screenShake=0;puffAnim=0;bossFlash=0;
 let y=H*.82;platforms.push({x:W/2-55,y,w:110,h:18,move:false,breakable:false});
 for(let i=0;i<30;i++){y-=70+Math.random()*35;addPlatform(y)}
 for(let i=0;i<11;i++)clouds.push({x:Math.random()*W,y:Math.random()*H,s:.5+Math.random()*.9,drift:.08+Math.random()*.18});
 for(let i=0;i<28;i++)skySparkles.push({x:Math.random()*W,y:Math.random()*H,tw:Math.random()*6.28,s:.7+Math.random()*1.8});
 setMission();scoreEl.textContent=0;coinsEl.textContent=0;hpEl.textContent=player.hp;streakEl.textContent=save.streak;boostEl.style.width='100%';bossWrap.style.display='none';
}
function startGame(){startMusic();reset();paused=false;running=true;startEl.style.display='none';gameOverEl.style.display='none';missionCompleteEl.style.display='none';shopEl.style.display='none';upgradesEl.style.display='none';lastTime=performance.now();requestAnimationFrame(loop)}
playBtnEl.onclick=startGame;retryBtnEl.onclick=startGame;
menuBtnEl.onclick=()=>{gameOverEl.style.display='none';refreshMenu();startEl.style.display='flex'};
if(continueBtnEl)continueBtnEl.onclick=()=>{missionCompleteEl.style.display='none'};
leaderboardBtnEl.onclick=()=>{startEl.style.display='none';leaderboardMenuEl.style.display='flex';loadLeaderboard();};
closeLeaderboardEl.onclick=()=>{leaderboardMenuEl.style.display='none';startEl.style.display='flex';};
refreshLeaderboardEl.onclick=loadLeaderboard;
playerNameEl.addEventListener('change',()=>{save.playerName=cleanPlayerName(playerNameEl.value);playerNameEl.value=save.playerName;persist();});
shopBtnEl.onclick=()=>{renderShop();applyLanguage();startEl.style.display='none';shopEl.style.display='flex'};closeShopEl.onclick=()=>{shopEl.style.display='none';startEl.style.display='flex'};
upgradeBtnEl.onclick=()=>{renderUpgrades();applyLanguage();startEl.style.display='none';upgradesEl.style.display='flex'};closeUpgradesEl.onclick=()=>{upgradesEl.style.display='none';startEl.style.display='flex'};
dailyBtnEl.onclick=()=>{const now=Date.now(),day=86400000;if(now-save.lastDaily>=day){const reward=250;save.bank+=reward;save.lastDaily=now;save.streak++;persist();refreshMenu();showToast(tr('dailyReward',{streak:save.streak,reward}))}else showToast(tr('dailyClaimed'))};
function pauseGame(){if(!running||paused)return;paused=true;pauseMenuEl.style.display='flex';}
function resumeGame(){if(!running||!paused)return;pauseMenuEl.style.display='none';resumeCountdownEl.style.display='flex';const started=performance.now();function countdown(now){if(!running){resumeCountdownEl.style.display='none';return;}const left=Math.max(0,1500-(now-started));resumeCountdownTextEl.textContent=(left/1000).toFixed(1);if(left>0){requestAnimationFrame(countdown);}else{resumeCountdownEl.style.display='none';paused=false;lastTime=performance.now();requestAnimationFrame(loop);}}requestAnimationFrame(countdown);}
pauseBtnEl.onclick=pauseGame;resumeBtnEl.onclick=resumeGame;
pauseMenuBtnEl.onclick=()=>{paused=false;running=false;pauseMenuEl.style.display='none';gameOverEl.style.display='none';missionCompleteEl.style.display='none';refreshMenu();startEl.style.display='flex';};
function unlockBossCosmetic(id){const key='boss'+id.charAt(0).toUpperCase()+id.slice(1);if(!save[key]){save[key]=true;persist();setTimeout(()=>showToast(tr('bossCosmetic')),1250);}}
function renderChoiceRow(row,obj,currentKey,saveKey){row.innerHTML='';Object.entries(obj).forEach(([id,s])=>{const bossUnlocked=s.boss?save['boss'+s.boss.charAt(0).toUpperCase()+s.boss.slice(1)]:false;const unlocked=bossUnlocked||save.total>=s.need,b=document.createElement('button');b.className='skin'+(unlocked?'':' locked')+(save[currentKey]===id?' selected':'');b.textContent=unlocked?s.name:(s.boss?'🔒 Boss reward':`🔒 ${s.need}m`);b.onclick=()=>{if(!unlocked)return showToast(s.boss?tr('bossUnlock'):tr('needHeight',{need:s.need}));save[currentKey]=id;persist();renderShop();};row.appendChild(b);});}
function renderShop(){renderChoiceRow(skinrowEl,skins,'skin','skyPuffSkin');renderChoiceRow(facerowEl,faceStyles,'face','skyPuffFace');renderChoiceRow(hatrowEl,hats,'hat','skyPuffHat');renderChoiceRow(trailrowEl,trailStyles,'trail','skyPuffTrail');}
const upgrades=[{key:'upBoost',name:'Rainbow Tank',desc:'Lavere puff-kostnad og sterkere boost.',base:1000,max:5},{key:'upMagnet',name:'Magnet Power',desc:'Lengre magnet-varighet.',base:1250,max:5},{key:'upCoin',name:'Coin Bonus',desc:'Flere bankmynter per runde.',base:1500,max:5},{key:'upHealth',name:'Ekstra Liv',desc:'Starter med mer helse.',base:2000,max:3}];
function upgradeLabel(u){const map={no:{upBoost:['Rainbow Tank','Lavere puff-kostnad og sterkere boost.'],upHealth:['Ekstra Liv','Starter med mer helse.'],upCoin:['Coin Bonus','Flere bankmynter per runde.'],upMagnet:['Magnet Power','Lengre magnet-varighet.']},en:{upBoost:['Rainbow Tank','Lower puff cost and stronger boost.'],upHealth:['Extra Life','Start each run with more health.'],upCoin:['Coin Bonus','More bank coins per run.'],upMagnet:['Magnet Power','Longer magnet duration.']},de:{upBoost:['Rainbow Tank','Geringere Puff-Kosten und stärkerer Boost.'],upHealth:['Extra Leben','Starte jede Runde mit mehr Leben.'],upCoin:['Coin Bonus','Mehr Bankmünzen pro Runde.'],upMagnet:['Magnet Power','Längere Magnetdauer.']},es:{upBoost:['Rainbow Tank','Menor coste de puff y boost más fuerte.'],upHealth:['Vida Extra','Empieza cada partida con más vida.'],upCoin:['Coin Bonus','Más monedas para el banco por partida.'],upMagnet:['Magnet Power','Mayor duración del imán.']},fr:{upBoost:['Rainbow Tank','Coût de puff réduit et boost plus puissant.'],upHealth:['Vie Supplémentaire','Commence chaque partie avec plus de vie.'],upCoin:['Coin Bonus','Plus de pièces en banque par partie.'],upMagnet:['Magnet Power','Durée de l’aimant augmentée.']}};return(map[lang]||map.no)[u.key]||[u.name,u.desc];}
function renderUpgrades(){upgraderowEl.innerHTML='';upgrades.forEach(u=>{const lv=save[u.key],cost=Math.floor(u.base*Math.pow(1.8,lv)),b=document.createElement('button');b.className='upgrade';const[nm,ds]=upgradeLabel(u);const priceLabel=lang==='en'?'Price':lang==='de'?'Preis':lang==='es'?'Precio':lang==='fr'?'Prix':'Pris';b.innerHTML=`<strong>${nm} — Lv ${lv}/${u.max}</strong><small>${ds}<br>${lv>=u.max?tr('maxLevel'):`${priceLabel}: ${cost} 🪙`}</small>`;b.onclick=()=>{if(lv>=u.max)return showToast(tr('maxLevel'));if(save.bank<cost)return showToast(tr('needCoins'));save.bank-=cost;save[u.key]++;persist();renderUpgrades();refreshMenu();showToast(tr('upgraded',{name:upgradeLabel(u)[0]}))};upgraderowEl.appendChild(b)})}
canvas.addEventListener('pointerdown',e=>{active=true;pointerX=e.clientX;const n=performance.now();if(n-lastTap<280)doBoost();lastTap=n});canvas.addEventListener('pointermove',e=>{if(active)pointerX=e.clientX});canvas.addEventListener('pointerup',()=>active=false);canvas.addEventListener('pointercancel',()=>active=false);
function doBoost(){const cost=Math.max(20,28-save.upBoost*2);if(!running||boost<cost)return;boost-=cost;if(!bossArena)player.vy-=7.8+save.upBoost*.25;puffAnim=1.25;screenShake=Math.max(screenShake,4);combo=Math.min(9,combo+1);bestCombo=Math.max(bestCombo,combo);comboTimer=95;if(boss){playerShots.push({x:player.x,y:player.y-28,vx:0,vy:-9.4,r:10,life:120,damage:12+save.upBoost*2});}for(let i=0;i<25;i++)particles.push({x:player.x+(Math.random()-.5)*22,y:player.y+22,vx:(Math.random()-.5)*3,vy:2+Math.random()*4,life:38+Math.random()*18,hue:(i*15)%360,size:4+Math.random()*7});}
function hitPlayer(x,y,r){return Math.hypot(player.x-x,player.y-y)<player.r+r}
function checkMission(){if(missionDone)return;const m=missions[missionIndex];let ok=m.type==='height'?score>=m.target:m.type==='coins'?coins>=m.target:bestCombo>=m.target;if(ok){missionDone=true;save.bank+=m.reward;persist();missionRewardTextEl.textContent=tr('missionReward',{reward:m.reward});missionCompleteEl.style.display='block';clearTimeout(window.skyMissionToastTimer);window.skyMissionToastTimer=setTimeout(()=>{missionCompleteEl.style.display='none'},1800);}}
function nextBossStage(){return bossStages.find(b=>score>=b.at&&!defeatedBosses[b.id])||null;}
function triggerBossWarning(stage){if(bossWarningActive||boss)return;bossWarningActive=true;bossPendingStage=stage;bossWarningTextEl.textContent=tr('bossIncoming');bossWarningEl.style.display='block';setTimeout(()=>{bossWarningEl.style.display='none';bossWarningActive=false;const s=bossPendingStage;bossPendingStage=null;if(running&&!paused&&s&&!boss&&!defeatedBosses[s.id])spawnBoss(s);},1200);}
function spawnBoss(stage){bossArena=true;bossArenaY=Math.min(H-145,Math.max(260,player.y));player.y=bossArenaY;player.vy=0;boss={id:stage.id,name:stage.name,x:W/2,y:150,hp:stage.hp,maxHp:stage.hp,dir:1,r:stage.id==='galaxy'?48:40,shot:0,reward:stage.reward,emoji:stage.emoji};bossSpawned=true;bossWrap.style.display='block';bossBar.style.width='100%';showToast(`${stage.name}! ${stage.emoji}`);startBossMusic(stage.id);}
