async function loadLeaderboard(){
 leaderboardStatusEl.textContent=tr('loading');
 leaderboardListEl.innerHTML='';
 try{
   const r=await fetch(API_BASE+'/leaderboard?limit=20',{cache:'no-store'});
   if(!r.ok)throw new Error('HTTP '+r.status);
   const rows=await r.json();
   leaderboardStatusEl.textContent='';
   if(!rows.length){leaderboardStatusEl.textContent=tr('noScores');return;}
   leaderboardListEl.innerHTML=rows.map((row,i)=>{
     const safeName=String(row.name).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
     const medal=i===0?'🥇':i===1?'🥈':i===2?'🥉':`${i+1}.`;
     return `<div style="display:grid;grid-template-columns:42px 1fr auto;gap:8px;align-items:center;padding:9px 10px;margin:5px 0;background:#eef8ff;border-radius:13px;font-weight:800"><span>${medal}</span><span>${safeName}</span><span>${Number(row.height)||0} m</span></div>`;
   }).join('');
 }catch(e){leaderboardStatusEl.textContent='⚠️ '+tr('scoreSendFail');}
}
function applyLanguage(){
 const t=i18n[lang]||i18n.no;
 languageSelectEl.value=lang;playBtnEl.textContent=t.play;upgradeBtnEl.textContent=t.upgrade;shopBtnEl.textContent=t.skins;dailyBtnEl.textContent=t.daily;leaderboardBtnEl.textContent='🏆 '+t.leaderboard;leaderboardTitleEl.textContent=t.globalHighscore;refreshLeaderboardEl.textContent=t.refresh;closeLeaderboardEl.textContent=t.back;playerNameEl.placeholder=t.namePlaceholder;menuTagEl.innerHTML=t.tag;menuHintEl.innerHTML=t.hint;
 bestStatEl.innerHTML=`🏆 ${t.best}<br><span id="bestHeight">${save.best}</span> m`;bankStatEl.innerHTML=`💰 ${t.bank}<br><span id="bankCoins">${save.bank}</span>`;totalStatEl.innerHTML=`📈 ${t.total}<br><span id="totalHeight">${save.total}</span> m`;streakStatEl.innerHTML=`🔥 ${t.streak}<br><span id="menuStreak">${save.streak}</span>`;
 closeShopEl.textContent=t.back;closeUpgradesEl.textContent=t.back;retryBtnEl.textContent=t.retry;menuBtnEl.textContent=t.menu;if(continueBtnEl)continueBtnEl.textContent=t.continue;
 const pt=document.getElementById('pauseTitle');if(pt)pt.textContent=t.pause;if(resumeBtnEl)resumeBtnEl.textContent=t.resume;if(pauseMenuBtnEl)pauseMenuBtnEl.textContent=t.mainMenu;if(pauseTextEl)pauseTextEl.textContent=t.pauseText;
 document.querySelector('#shop h1').textContent=t.shopTitle;document.querySelector('#upgrades h1').textContent=t.upTitle;document.querySelector('#gameOver h1').textContent=t.gameOver;const mct=document.getElementById('missionCompleteTitle');if(mct)mct.textContent=t.missionComplete;
 if(skinsLabelEl)skinsLabelEl.textContent=t.skinsLabel;if(faceLabelEl)faceLabelEl.textContent=t.faceLabel;if(hatsLabelEl)hatsLabelEl.textContent=t.hatsLabel;if(trailsLabelEl)trailsLabelEl.textContent=t.trailsLabel;if(upgradeTextEl)upgradeTextEl.textContent=t.upgradeText;
 if(goHeightLabelEl)goHeightLabelEl.textContent=t.height;if(goCoinsLabelEl)goCoinsLabelEl.textContent=t.coins;if(goComboLabelEl)goComboLabelEl.textContent=t.bestCombo;if(goBankLabelEl)goBankLabelEl.textContent=t.bank;
 refreshAudioUI();if(running||paused){const m=missions[missionIndex];if(m)missionEl.textContent=t.mission+': '+missionText(m);}
}
languageSelectEl.addEventListener('change',()=>{lang=languageSelectEl.value;localStorage.skyPuffLang=lang;applyLanguage();});
let W=innerWidth,H=innerHeight,dpr=Math.min(devicePixelRatio||1,2);
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize);resize();
const save={bank:+(localStorage.skyPuffBank||0),best:+(localStorage.skyPuffBest||0),total:+(localStorage.skyPuffTotal||0),skin:localStorage.skyPuffSkin||'classic',upBoost:+(localStorage.skyPuffUpBoost||0),upHealth:+(localStorage.skyPuffUpHealth||0),upCoin:+(localStorage.skyPuffUpCoin||0),upMagnet:+(localStorage.skyPuffUpMagnet||0),lastDaily:+(localStorage.skyPuffDaily||0),streak:+(localStorage.skyPuffStreak||0),face:localStorage.skyPuffFace||'smile',hat:localStorage.skyPuffHat||'none',trail:localStorage.skyPuffTrail||'auto',bossStorm:localStorage.skyPuffBossStorm==='1',bossCandy:localStorage.skyPuffBossCandy==='1',bossIce:localStorage.skyPuffBossIce==='1',bossGalaxy:localStorage.skyPuffBossGalaxy==='1',playerName:localStorage.skyPuffPlayerName||''};
function persist(){Object.entries({skyPuffBank:save.bank,skyPuffBest:save.best,skyPuffTotal:save.total,skyPuffSkin:save.skin,skyPuffUpBoost:save.upBoost,skyPuffUpHealth:save.upHealth,skyPuffUpCoin:save.upCoin,skyPuffUpMagnet:save.upMagnet,skyPuffDaily:save.lastDaily,skyPuffStreak:save.streak,skyPuffFace:save.face,skyPuffHat:save.hat,skyPuffTrail:save.trail,skyPuffBossStorm:save.bossStorm?'1':'0',skyPuffBossCandy:save.bossCandy?'1':'0',skyPuffBossIce:save.bossIce?'1':'0',skyPuffBossGalaxy:save.bossGalaxy?'1':'0',skyPuffPlayerName:save.playerName}).forEach(([k,v])=>localStorage[k]=v)}
function refreshMenu(){const a=document.getElementById('bestHeight'),b=document.getElementById('bankCoins'),c=document.getElementById('totalHeight'),d=document.getElementById('menuStreak');if(a)a.textContent=save.best;if(b)b.textContent=save.bank;if(c)c.textContent=save.total;if(d)d.textContent=save.streak;}
refreshMenu();playerNameEl.value=save.playerName;
const skins={classic:{name:'Classic',need:0,body:'#ffffff',cheek:'rgba(255,115,160,.45)',eye:'#2b4665',trail:'rainbow'},sunset:{name:'Sunset',need:500,body:'#ffd6e8',cheek:'rgba(255,80,130,.5)',eye:'#5a3b55',trail:'rainbow'},mint:{name:'Mint',need:1500,body:'#c9fff0',cheek:'rgba(40,200,160,.45)',eye:'#245d56',trail:'mint'},golden:{name:'Golden',need:4000,body:'#fff0a8',cheek:'rgba(255,170,30,.5)',eye:'#6b5320',trail:'gold'},storm:{name:'Storm',need:8000,body:'#b6c3d1',cheek:'rgba(120,140,180,.5)',eye:'#26313d',trail:'storm'},candy:{name:'Candy',need:12000,body:'#ffc8f0',cheek:'rgba(255,80,180,.5)',eye:'#6a2d63',trail:'candy'},frost:{name:'Frost',need:18000,body:'#dff7ff',cheek:'rgba(80,180,255,.45)',eye:'#2e617a',trail:'ice'},galaxy:{name:'Galaxy',need:26000,body:'#c9c0ff',cheek:'rgba(160,110,255,.45)',eye:'#322d63',trail:'galaxy'},lava:{name:'Lava',need:36000,body:'#ffb08f',cheek:'rgba(255,80,40,.5)',eye:'#6a261e',trail:'fire'},royal:{name:'Royal',need:50000,body:'#eee5ff',cheek:'rgba(130,90,255,.45)',eye:'#3f2b68',trail:'royal'}};
const cosmetics={face:'smile',hat:'none',trail:'auto'};
const faceStyles={smile:{name:'Smile',need:0},sleepy:{name:'Sleepy',need:3000},happy:{name:'Happy',need:9000},cool:{name:'Cool',need:20000}};
const hats={none:{name:'None',need:0},crown:{name:'Crown',need:7000},propeller:{name:'Propeller',need:14000},halo:{name:'Halo',need:24000},wizard:{name:'Wizard Hat',need:40000},stormCrown:{name:'Storm Crown ⚡',need:999999,boss:'storm'},candyCrown:{name:'Candy Horns 🍭',need:999999,boss:'candy'},iceCrown:{name:'Ice Crown ❄️',need:999999,boss:'ice'},galaxyCrown:{name:'Galaxy Crown 👑',need:999999,boss:'galaxy'}};
const trailStyles={auto:{name:'Skin Trail',need:0},rainbow:{name:'Rainbow',need:0},hearts:{name:'Hearts',need:10000},stars:{name:'Stars',need:22000},neon:{name:'Neon',need:35000},aurora:{name:'Aurora',need:50000}};
const missions=[{type:'height',target:300,reward:25},{type:'coins',target:25,reward:30},{type:'combo',target:5,reward:35},{type:'height',target:900,reward:50}];
function missionText(m){if(lang==='en')return m.type==='height'?`reach ${m.target} m`:m.type==='coins'?`collect ${m.target} coins`:`get combo x${m.target}`;if(lang==='de')return m.type==='height'?`${m.target} m erreichen`:m.type==='coins'?`${m.target} Münzen sammeln`:`Combo x${m.target} erreichen`;if(lang==='es')return m.type==='height'?`llega a ${m.target} m`:m.type==='coins'?`recoge ${m.target} monedas`:`consigue combo x${m.target}`;if(lang==='fr')return m.type==='height'?`atteindre ${m.target} m`:m.type==='coins'?`ramasser ${m.target} pièces`:`obtenir combo x${m.target}`;return m.type==='height'?`nå ${m.target} m`:m.type==='coins'?`samle ${m.target} mynter`:`få combo x${m.target}`;}
let missionIndex=0,missionDone=false;let paused=false;let screenShake=0;let puffAnim=0;let bossFlash=0;let skySparkles=[];let running=false,platforms=[],coinItems=[],clouds=[],enemies=[],powerups=[],particles=[],playerShots=[],bossShots=[];let player,cameraY=0,score=0,coins=0,boost=100,lastTime=0,pointerX=W/2,active=false,lastTap=0,combo=1,bestCombo=1,comboTimer=0,invuln=0,shield=0,magnet=0,mega=0;let boss=null,bossSpawned=false,bossDefeated=false,bossWarningActive=false,bossPendingStage=null;let bossArena=false,bossArenaY=0;let defeatedBosses={storm:false,candy:false,ice:false,galaxy:false};
const bossStages=[{id:'storm',at:1200,name:'Storm Boss',hp:120,reward:250,emoji:'⚡'},{id:'candy',at:2000,name:'Candy Dragon',hp:175,reward:500,emoji:'🐉'},{id:'ice',at:3000,name:'Ice Titan',hp:240,reward:850,emoji:'❄️'},{id:'galaxy',at:4500,name:'Galaxy King',hp:340,reward:1500,emoji:'👑'}];
function showToast(txt){toast.textContent=txt;toast.style.opacity=1;clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.style.opacity=0,1200)}
function biome(){if(score<500)return'blue';if(score<1000)return'sunset';if(score<1200)return'space';if(score<2000)return'candy';if(score<3000)return'frozen';if(score<4500)return'galaxy';return'endless';}
