function drawCloud(x,y,s,a=.3){ctx.save();ctx.globalAlpha=a;const g=ctx.createLinearGradient(x,y-30*s,x,y+28*s);g.addColorStop(0,'#ffffff');g.addColorStop(1,'#dff4ff');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,26*s,0,Math.PI*2);ctx.arc(x+28*s,y-8*s,34*s,0,Math.PI*2);ctx.arc(x+60*s,y,25*s,0,Math.PI*2);ctx.fill();ctx.globalAlpha=a*.22;ctx.fillStyle='#4fa6d8';ctx.beginPath();ctx.ellipse(x+30*s,y+18*s,43*s,10*s,0,0,Math.PI*2);ctx.fill();ctx.restore();}
function activeSkin(){return skins[save.skin]||skins.classic;}
function drawTrail(){const sk=activeSkin();const trail=save.trail==='auto'?sk.trail:save.trail;if(player.vy>=0)return;if(trail==='rainbow'||trail==='candy'||trail==='mint'||trail==='gold'||trail==='storm'||trail==='ice'||trail==='galaxy'||trail==='fire'||trail==='royal'||trail==='neon'||trail==='aurora'){let cols=['#ff4d6d','#ff9f1c','#ffe66d','#4cd97b','#4dabf7','#8b5cf6'];if(trail==='mint')cols=['#8fffe0','#4de0bd','#22bfa0','#9affef','#5fe8ce','#c8fff4'];if(trail==='gold')cols=['#fff1a8','#ffd84d','#ffbd2e','#ffe77a','#ffc24b','#fff4bf'];if(trail==='storm')cols=['#d8e0ea','#8da0b5','#67798b','#c6d1dc','#7e91a3','#edf2f7'];if(trail==='ice')cols=['#e8fbff','#aeeeff','#74d8ff','#d2f6ff','#8be6ff','#ffffff'];if(trail==='galaxy')cols=['#7b61ff','#a55eea','#5f27cd','#00d2d3','#c56cf0','#341f97'];if(trail==='fire')cols=['#fff36b','#ffb12b','#ff6b2b','#ff3b30','#ff8d4d','#ffd166'];if(trail==='royal')cols=['#d8c6ff','#9b7cff','#6c4cff','#f0e7ff','#ad95ff','#ffffff'];if(trail==='neon')cols=['#00fff0','#ff00f5','#8cff00','#00a8ff','#ffea00','#ff3b81'];if(trail==='aurora')cols=['#6fffe9','#5eead4','#8b5cf6','#60a5fa','#34d399','#a7f3d0'];if(trail==='candy')cols=['#ff9bd6','#ffd2f0','#ff7ac8','#b794ff','#9ee7ff','#ffffff'];for(let i=0;i<6;i++){ctx.strokeStyle=cols[i%cols.length];ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-12+i*5,22);ctx.quadraticCurveTo(-15+i*4,36,(-18+i*5)+Math.sin(performance.now()/120+i)*5,55);ctx.stroke();}}else if(trail==='hearts'||trail==='stars'){ctx.font='18px Arial';ctx.textAlign='center';for(let i=0;i<4;i++){ctx.globalAlpha=.75-i*.15;ctx.fillText(trail==='hearts'?'💖':'⭐',(i-1.5)*11,32+i*11);}ctx.globalAlpha=1;}}
function drawHat(){
 const h=hats[save.hat]?save.hat:'none';if(h==='none')return;
 const icon={crown:'👑',propeller:'🚁',halo:'😇',wizard:'🧙',legendHalo:'✨',eventCrown:'🌪️',hunterHelm:'🛡️',cloudBreakerCrown:'☁️',immortalHalo:'♾️',bossVeteranCrown:'⚔️',treasureCrown:'💎',stormCrown:'⚡',candyCrown:'🍭',iceCrown:'❄️',galaxyCrown:'👑'}[h];
 if(!icon)return;
 ctx.save();ctx.translate(0,-29);ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=(h==='cloudBreakerCrown'||h==='hunterHelm')?'24px Arial':'26px Arial';
 if(h==='legendHalo'||h==='immortalHalo'){ctx.globalAlpha=.45;ctx.strokeStyle=h==='immortalHalo'?'#b197fc':'#ffe66d';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(0,-3,20,7,0,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;}
 ctx.fillText(icon,0,-2);
 if(h==='eventCrown'){ctx.font='14px Arial';ctx.fillText('👑',0,5)}
 if(h==='cloudBreakerCrown'){ctx.font='13px Arial';ctx.fillText('💥',15,-9)}
 if(h==='bossVeteranCrown'){ctx.font='13px Arial';ctx.fillText('👑',0,-11)}
 if(h==='treasureCrown'){ctx.font='13px Arial';ctx.fillText('👑',0,-10)}
 ctx.restore();
}
function drawFace(){const sk=activeSkin();const face=faceStyles[save.face]?save.face:'smile';ctx.fillStyle=sk.eye;if(face==='sleepy'){ctx.strokeStyle=sk.eye;ctx.lineWidth=2.4;ctx.beginPath();ctx.arc(-9,3,5,.15*Math.PI,.85*Math.PI);ctx.stroke();ctx.beginPath();ctx.arc(10,3,5,.15*Math.PI,.85*Math.PI);ctx.stroke();ctx.beginPath();ctx.arc(1,8,5,1.1*Math.PI,1.9*Math.PI);ctx.stroke();}else if(face==='happy'){ctx.strokeStyle=sk.eye;ctx.lineWidth=2.4;ctx.beginPath();ctx.arc(-9,3,5,.1*Math.PI,.9*Math.PI);ctx.stroke();ctx.beginPath();ctx.arc(10,3,5,.1*Math.PI,.9*Math.PI);ctx.stroke();ctx.beginPath();ctx.arc(1,6,9,.1*Math.PI,.9*Math.PI);ctx.stroke();}else if(face==='cool'){ctx.fillStyle='#1d2530';ctx.fillRect(-18,-2,14,7);ctx.fillRect(4,-2,14,7);ctx.fillRect(-4,0,8,2);ctx.strokeStyle=sk.eye;ctx.lineWidth=2.2;ctx.beginPath();ctx.arc(1,8,6,.05*Math.PI,.95*Math.PI);ctx.stroke();}else{ctx.beginPath();ctx.arc(-9,2,3.8,0,Math.PI*2);ctx.arc(10,2,3.8,0,Math.PI*2);ctx.fill();ctx.strokeStyle=sk.eye;ctx.lineWidth=2.2;ctx.beginPath();ctx.arc(1,7,7,.1*Math.PI,.9*Math.PI);ctx.stroke();}}
