/* Sky Puff — Puffling Nursery + Vault v0.3 */
(function(){
 const EGG_KEY='skyPuffEggInventoryV1',PENDING_KEY='skyPuffPendingEggsV1',MAX_VAULT=3;let hatching=false;
 const F=()=>window.SkyPuffFusion;
 function loadEggs(){try{return JSON.parse(localStorage.getItem(EGG_KEY)||'{}')}catch(e){return {}}}
 function saveEggs(v){localStorage.setItem(EGG_KEY,JSON.stringify(v||{}));}
 function migratePending(){try{const p=JSON.parse(localStorage.getItem(PENDING_KEY)||'{}');if(!p||typeof p!=='object')return;const e=loadEggs();let changed=false;for(const t of ['rare','epic','legendary']){const n=Math.max(0,+p[t]||0);if(n){e[t]=(e[t]||0)+n;changed=true;}}if(changed)saveEggs(e);localStorage.removeItem(PENDING_KEY);}catch(e){}}
 function addEgg(tier,count=1){const e=loadEggs();e[tier]=(e[tier]||0)+Math.max(1,count|0);saveEggs(e);render();return e;}
 function pool(tier){const f=F();if(!f)return[];if(tier==='legendary')return['eclipse','neonstorm'];if(tier==='epic')return['thunderflame','aurora','tempest'];if(tier==='rare')return['prism','shadow','ember','volt','frost','wind'];return Object.keys(f.BASE||{});}
 function getPuff(id){const f=F();if(!f)return null;return [...Object.values(f.BASE||{}),...Object.values(f.FUSIONS||{})].find(x=>x.id===id)||null}
 function reserveHatch(tier){if(hatching)return null;const e=loadEggs(),p=pool(tier),f=F();if(!f||(e[tier]||0)<=0||!p.length)return null;const id=p[Math.floor(Math.random()*p.length)];e[tier]--;saveEggs(e);f.add(id,1);window.SkyPuffFusionUI?.renderDex?.();return id;}
 function hatch(tier){const id=reserveHatch(tier);if(id)render();return id;}
 function animateHatch(tier){const id=reserveHatch(tier);if(!id)return;hatching=true;render();const p=getPuff(id),layer=document.getElementById('eggHatchLayer'),egg=document.getElementById('eggHatchEgg'),reveal=document.getElementById('eggHatchReveal');if(!layer||!egg||!reveal){hatching=false;render();return;}layer.style.display='flex';reveal.style.display='none';egg.style.display='block';egg.className='eggHatchEgg '+tier;egg.textContent='🥚';requestAnimationFrame(()=>egg.classList.add('shake'));setTimeout(()=>{egg.classList.remove('shake');egg.classList.add('crack');egg.textContent='✨';},850);setTimeout(()=>{egg.style.display='none';reveal.style.display='block';const art=window.SkyPuffVisuals?.art?.(id,0);reveal.innerHTML=`<div class="hatchBurst">${art||`<div style="font-size:58px">${p?.icon||'☁️'}</div>`}<b>${p?.name||id}</b><small>${tier.toUpperCase()} HATCH!</small></div>`;render();},1250);setTimeout(()=>{layer.style.display='none';egg.style.display='block';egg.className='eggHatchEgg';reveal.innerHTML='';hatching=false;render();},2700);}
 function toggleVault(id){const f=F();if(!f)return false;const s=f.load();s.vault=Array.isArray(s.vault)?s.vault.slice(0,MAX_VAULT):[];const i=s.vault.indexOf(id);if(i>=0){s.vault.splice(i,1);f.save(s);render();return true;}if(s.vault.length>=MAX_VAULT||!(s.owned?.[id]>0))return false;s.vault.push(id);f.save(s);render();return true;}
 function ensure(){if(document.getElementById('nurseryVaultMenu'))return;const style=document.createElement('style');style.textContent=`#eggHatchLayer{position:fixed;inset:0;z-index:9999;background:rgba(25,30,60,.62);backdrop-filter:blur(4px);align-items:center;justify-content:center}.eggHatchEgg{font-size:88px;filter:drop-shadow(0 8px 12px #0004);will-change:transform}.eggHatchEgg.shake{animation:eggShake .18s ease-in-out 5}.eggHatchEgg.crack{animation:eggPop .4s ease-out}.hatchBurst{text-align:center;color:#fff;animation:hatchReveal .42s cubic-bezier(.2,.9,.3,1.25)}.hatchBurst .spPuffArt{margin:0 auto 18px;transform:scale(1.35)}.hatchBurst b,.hatchBurst small{display:block;text-shadow:0 2px 8px #0008}.hatchBurst b{font-size:28px}.hatchBurst small{font-size:13px;margin-top:5px}@keyframes eggShake{0%,100%{transform:rotate(0)}25%{transform:rotate(-9deg)}75%{transform:rotate(9deg)}}@keyframes eggPop{50%{transform:scale(1.22)}100%{transform:scale(.1);opacity:.2}}@keyframes hatchReveal{from{transform:scale(.3);opacity:0}to{transform:scale(1);opacity:1}}@media(prefers-reduced-motion:reduce){.eggHatchEgg.shake,.eggHatchEgg.crack,.hatchBurst{animation:none!important}}`;document.head.appendChild(style);const el=document.createElement('div');el.id='nurseryVaultMenu';el.className='overlay';el.style.display='none';el.innerHTML=`<div class="card" style="max-width:620px"><h1 style="font-size:34px">Nursery & Vault 🥚🔐</h1><div class="small">Klekk egg og beskytt opptil ${MAX_VAULT} Pufflings mot Steal My Puff.</div><h3>🥚 Nursery</h3><div id="nurseryEggs" style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px"></div><div id="hatchResult" style="margin:12px 0;font-weight:900"></div><h3>🔐 Puff Vault <span id="vaultCount"></span></h3><div class="small" style="margin-bottom:8px">Hver plass beskytter én Puffling. Har du flere kopier av samme type, er bare den lagrede kopien trygg.</div><div id="vaultList" style="display:grid;grid-template-columns:repeat(2,1fr);gap:8px;max-height:260px;overflow:auto"></div><button id="closeNurseryVault" class="secondary" style="margin-top:12px">TILBAKE</button></div>`;document.body.appendChild(el);const layer=document.createElement('div');layer.id='eggHatchLayer';layer.style.display='none';layer.innerHTML='<div id="eggHatchEgg" class="eggHatchEgg">🥚</div><div id="eggHatchReveal"></div>';document.body.appendChild(layer);document.getElementById('closeNurseryVault').onclick=()=>{el.style.display='none';document.getElementById('start').style.display='flex'};const b=document.createElement('button');b.id='nurseryVaultBtn';b.className='secondary';b.textContent='NURSERY & VAULT 🥚🔐';b.onclick=open;(document.getElementById('menuMoreGrid')||document.querySelector('#start .menuActions'))?.appendChild(b);render();}
 function render(){const f=F();if(!f)return;const eggs=loadEggs(),box=document.getElementById('nurseryEggs');if(box){box.innerHTML='';['rare','epic','legendary'].forEach(t=>{const n=eggs[t]||0,b=document.createElement('button');b.className=t==='legendary'?'gold':'secondary';b.innerHTML=`${t==='rare'?'💙':t==='epic'?'💜':'💛'} ${t.toUpperCase()} EGG<br><small>x${n}</small>`;b.disabled=n<=0||hatching;b.onclick=()=>animateHatch(t);box.appendChild(b)});}const s=f.load();s.vault=Array.isArray(s.vault)?s.vault.slice(0,MAX_VAULT):[];const c=document.getElementById('vaultCount');if(c)c.textContent=`${s.vault.length}/${MAX_VAULT}`;const list=document.getElementById('vaultList');if(list){list.innerHTML='';Object.entries(s.owned||{}).filter(([,n])=>n>0).forEach(([id,n])=>{const p=getPuff(id),locked=s.vault.includes(id),safe=locked?1:0,b=document.createElement('button');b.className=locked?'gold':'secondary';b.innerHTML=`${p?.icon||'☁️'} ${p?.name||id} x${n}<br><small>${locked?`1 TRYGG 🔒 • ${Math.max(0,n-safe)} UTE`:'LEGG 1 I VAULT'}</small>`;b.onclick=()=>{if(!toggleVault(id)&&!locked&&typeof showToast==='function')showToast(`Vault er full (${MAX_VAULT}/${MAX_VAULT})`);};list.appendChild(b)});if(!list.children.length)list.innerHTML='<div class="small">Ingen Pufflings eid ennå.</div>';}}
 function open(){ensure();document.getElementById('start').style.display='none';document.getElementById('nurseryVaultMenu').style.display='flex';render();}
 migratePending();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(ensure,40));else setTimeout(ensure,40);window.SkyPuffNurseryVault={loadEggs,addEgg,hatch,animateHatch,toggleVault,open,render,maxVault:MAX_VAULT};
})();