/* Puffling — Boss Puffling Rewards v0.7 verified session reward */
(function(){
 let grantPending=false,rewardedSession='';
 function fusion(){return window.SkyPuffFusion}function gameplay(){return window.SkyPuffPufflingGameplay}
 function all(){const F=fusion();return F?[...Object.values(F.BASE||{}),...Object.values(F.FUSIONS||{})]:[]}
 function puffInfo(id){return gameplay()?.getPuff?.(id)||all().find(p=>p.id===id)||null}
 function endpoint(){return String(window.skyPuffConfig?.apiBase||window.SKY_PUFF_GAME_API_URL||'').replace(/\/$/,'')}
 async function identity(){let token='';try{token=localStorage.getItem('pufflingAccountAuthToken')||''}catch(e){}if(token)return token;try{const x=await window.SkyPuffRaceTransport?.ensureGuestIdentity?.();return x?.token||localStorage.getItem('pufflingAccountAuthToken')||''}catch(e){return''}}
 function applyGranted(id){const F=fusion();if(!F||!id)return;F.add(id,1);const p=puffInfo(id);if(gameplay()&&!gameplay().active())gameplay().setActive(id);window.SkyPuffFusionUI?.renderDex?.();const rarity=(p?.rarity||'common').toUpperCase(),rare=(p?.rarity==='epic'||p?.rarity==='legendary')?` ${rarity}!`:' ';if(typeof showToast==='function')showToast(`BOSS DROP!${rare} ${p?.icon||'☁️'} ${p?.name||id} funnet!`)}
 async function requestGrant(sessionId){const base=endpoint(),token=await identity();if(!base||!token||!sessionId)throw new Error('reward_server_unavailable');const r=await fetch(base+'/api/acquisition/boss',{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+token,'accept':'application/json'},body:JSON.stringify({sessionId})});let b={};try{b=await r.json()}catch(e){}if(!r.ok||!b?.ok||!b?.serverAuthoritative)throw new Error(b?.error||'reward_rejected');return b}
 async function rollBossReward(defeated){const sessionId=String(defeated?.sessionId||'');if(grantPending||!sessionId||sessionId===rewardedSession||typeof bossRushMode!=='undefined'&&bossRushMode)return;grantPending=true;try{const grant=await requestGrant(sessionId);rewardedSession=sessionId;if(grant.noDrop||!grant.pufflingId){if(typeof showToast==='function')showToast('Boss reward: Ingen Puffling denne gangen ☁️');return}applyGranted(grant.pufflingId)}catch(e){if(typeof showToast==='function')showToast('Boss reward kunne ikke bekreftes av serveren — ingen Puffling ble lagt til.')}finally{grantPending=false}}
 window.SkyPuffBossPufflingRewards={rollBossReward,requestGrant};
})();