/* Sky Puff — Puffling Nursery + Vault v0.1 */
(function(){
 const EGG_KEY='skyPuffEggInventoryV1';
 const MAX_VAULT=3;
 const F=()=>window.SkyPuffFusion;
 function loadEggs(){try{return JSON.parse(localStorage.getItem(EGG_KEY)||'{}')}catch(e){return {}}}
 function saveEggs(v){localStorage.setItem(EGG_KEY,JSON.stringify(v||{}));}
 function addEgg(tier,count=1){const e=loadEggs();e[tier]=(e[tier]||0)+Math.max(1,count|0);saveEggs(e);render();return e;}
 function pool(tier){const f=F();if(!f)return[];if(tier==='legendary')return['eclipse','neonstorm'];if(tier==='epic')return['thunderflame','aurora','tempest'];if(tier==='rare')return['prism','shadow','ember','volt','frost','wind'];return Object.keys(f.BASE||{});}
 function hatch(tier){const e=loadEggs();if((e[tier]||0)<=0)return null;const p=pool(tier);if(!p.length)return null;const id=p[Math.floor(Math.random()*p.length)];e[tier]--;saveEggs(e);F().add(id,1);window.SkyPuffFusionUI?.renderDex?.();render();return id;}
 function getPuff(id){const f=F();if(!f)return null;return [...Object.values(f.BASE||{}),...Object.values(f.FUSIONS||{})].find(x=>x.id===id)||null}
 function toggleVault(id){const f=F();if(!f)return false;const s=f.load();s.vault=Array.isArray(s.vault)?s.vault:[];const i=s.vault.indexOf(id);if(i>=0){s.vault.splice(i,1);f.save(s);render();return true;}if(s.vault.length>=MAX_VAULT)return false;if(!(s.owned?.[id]>0))return false;s.vault.push(id);f.save(s);render();return true;}
 function ensure(){if(document.getElementById('nurseryVaultMenu'))return;const el=document.createElement('div');el.id='nurseryVaultMenu';el.className='overlay';el.style.display='none';el.innerHTML=`<div class="card" style="max-width:620px"><h1 style="font-size:34px">Nursery & Vault 🥚🔐</h1><div class="small">Klekk egg og beskytt opptil ${MAX_VAULT} Pufflings mot Steal My Puff.</div><h3>🥚 Nursery</h3><div id="nurseryEggs" style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px"></div><div id="hatchResult" style="margin:12px 0;font-weight:900"></div><h3>🔐 Puff Vault <span id="vaultCount"></span></h3><div id="vaultList" style="display:grid;grid-template-columns:repeat(2,1fr);gap:8px;max-height:260px;overflow:auto"></div><button id="closeNurseryVault" class="secondary" style="margin-top:12px">TILBAKE</button></div>`;document.body.appendChild(el);document.getElementById('closeNurseryVault').onclick=()=>{el.style.display='none';document.getElementById('start').style.display='flex'};const b=document.createElement('button');b.id='nurseryVaultBtn';b.className='secondary';b.textContent='NURSERY & VAULT 🥚🔐';b.onclick=open;(document.getElementById('menuMoreGrid')||document.querySelector('#start .menuActions'))?.appendChild(b);render();}
 function render(){const f=F();if(!f)return;const eggs=loadEggs(),box=document.getElementById('nurseryEggs');if(box){box.innerHTML='';['rare','epic','legendary'].forEach(t=>{const n=eggs[t]||0,b=document.createElement('button');b.className=t==='legendary'?'gold':'secondary';b.innerHTML=`${t==='rare'?'💙':t==='epic'?'💜':'💛'} ${t.toUpperCase()} EGG<br><small>x${n}</small>`;b.disabled=n<=0;b.onclick=()=>{const id=hatch(t);const p=getPuff(id);const out=document.getElementById('hatchResult');if(out)out.textContent=id?`✨ ${p?.name||id} klekket!`:'Ingen egg å klekke.';};box.appendChild(b)});}
  const s=f.load();s.vault=Array.isArray(s.vault)?s.vault:[];const c=document.getElementById('vaultCount');if(c)c.textContent=`${s.vault.length}/${MAX_VAULT}`;const list=document.getElementById('vaultList');if(list){list.innerHTML='';Object.entries(s.owned||{}).filter(([,n])=>n>0).forEach(([id,n])=>{const p=getPuff(id),locked=s.vault.includes(id),b=document.createElement('button');b.className=locked?'gold':'secondary';b.innerHTML=`${p?.icon||'☁️'} ${p?.name||id} x${n}<br><small>${locked?'BESKYTTET 🔒':'LEGG I VAULT'}</small>`;b.onclick=()=>{if(!toggleVault(id)&&!locked&&typeof showToast==='function')showToast(`Vault er full (${MAX_VAULT}/${MAX_VAULT})`);};list.appendChild(b)});if(!list.children.length)list.innerHTML='<div class="small">Ingen Pufflings eid ennå.</div>';}}
 function open(){ensure();document.getElementById('start').style.display='none';document.getElementById('nurseryVaultMenu').style.display='flex';render();}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(ensure,40));else setTimeout(ensure,40);
 window.SkyPuffNurseryVault={loadEggs,addEgg,hatch,toggleVault,open,render,maxVault:MAX_VAULT};
})();
