/* Puffling — responsive Puffling Nursery + Vault v0.5 */
(function(){
 const EGG_KEY='skyPuffEggInventoryV1',PENDING_KEY='skyPuffPendingEggsV1',MAX_VAULT=3;let hatching=false;
 const F=()=>window.SkyPuffFusion;
 function loadEggs(){try{const raw=JSON.parse(localStorage.getItem(EGG_KEY)||'{}'),out={};for(const t of ['rare','epic','legendary'])out[t]=Math.max(0,Math.floor(Number(raw?.[t])||0));return out;}catch(e){return {rare:0,epic:0,legendary:0}}}
 function saveEggs(v){localStorage.setItem(EGG_KEY,JSON.stringify(v||{}));}
 function migratePending(){try{const p=JSON.parse(localStorage.getItem(PENDING_KEY)||'{}');if(!p||typeof p!=='object')return;const e=loadEggs();let changed=false;for(const t of ['rare','epic','legendary']){const n=Math.max(0,+p[t]||0);if(n){e[t]=(e[t]||0)+n;changed=true;}}if(changed)saveEggs(e);localStorage.removeItem(PENDING_KEY);}catch(e){}}
 function addEgg(tier,count=1){const e=loadEggs();e[tier]=(e[tier]||0)+Math.max(1,count|0);saveEggs(e);render();return e;}
 function allPuffs(){const f=F();if(!f)return[];return [...Object.values(f.BASE||{}),...Object.values(f.FUSIONS||{})];}
 function pool(tier){
  const all=allPuffs();
  if(tier==='legendary')return all.filter(p=>p.rarity==='legendary').map(p=>p.id);
  if(tier==='epic')return all.filter(p=>p.rarity==='epic').map(p=>p.id);
  if(tier==='rare')return all.filter(p=>p.rarity==='rare'||p.rarity==='common').map(p=>p.id);
  return all.filter(p=>p.rarity==='common').map(p=>p.id);
 }
 function getPuff(id){return allPuffs().find(x=>x.id===id)||null}
 function reserveHatch(tier){if(hatching)return null;const e=loadEggs(),p=pool(tier),f=F();if(!f||(e[tier]||0)<=0||!p.length)return null;const id=p[Math.floor(Math.random()*p.length)];e[tier]--;saveEggs(e);f.add(id,1);window.SkyPuffFusionUI?.renderDex?.();return id;}
 function hatch(tier){const id=reserveHatch(tier);if(id)render();return id;}
 function animateHatch(tier){const id=reserveHatch(tier);if(!id)return;hatching=true;render();const p=getPuff(id),layer=document.getElementById('eggHatchLayer'),egg=document.getElementById('eggHatchEgg'),reveal=document.getElementById('eggHatchReveal');if(!layer||!egg||!reveal){hatching=false;render();return;}layer.style.display='flex';reveal.style.display='none';egg.style.display='block';egg.className='eggHatchEgg '+tier;egg.textContent='🥚';requestAnimationFrame(()=>egg.classList.add('shake'));setTimeout(()=>{egg.classList.remove('shake');egg.classList.add('crack');egg.textContent='✨';},850);setTimeout(()=>{egg.style.display='none';reveal.style.display='block';const art=window.SkyPuffVisuals?.art?.(id,0);reveal.innerHTML=`<div class="hatchBurst">${art||`<div style="font-size:58px">${p?.icon||'☁️'}</div>`}<b>${p?.name||id}</b><small>${tier.toUpperCase()} HATCH!</small></div>`;render();},1250);setTimeout(()=>{layer.style.display='none';egg.style.display='block';egg.className='eggHatchEgg';reveal.innerHTML='';hatching=false;render();},2700);}
 function toggleVault(id){const f=F();if(!f)return false;const s=f.load();s.vault=Array.isArray(s.vault)?[...new Set(s.vault)].slice(0,MAX_VAULT):[];const i=s.vault.indexOf(id);if(i>=0){s.vault.splice(i,1);f.save(s);render();return true;}if(s.vault.length>=MAX_VAULT||!(s.owned?.[id]>0))return false;s.vault.push(id);f.save(s);render();return true;}
 function ensure(){
  if(document.getElementById('nurseryVaultMenu'))return;
  const style=document.createElement('style');style.id='nurseryVaultResponsiveCss';style.textContent=`
   #nurseryVaultMenu{align-items:flex-start;overflow-y:auto;padding:max(10px,env(safe-area-inset-top)) 10px max(10px,env(safe-area-inset-bottom));overscroll-behavior:contain}
   #nurseryVaultMenu .nurseryVaultCard{width:min(94vw,620px);max-height:calc(100dvh - 20px);margin:auto;overflow-y:auto;overscroll-behavior:contain;-webkit-overflow-scrolling:touch;padding:20px 18px 12px;scrollbar-gutter:stable}
   #nurseryVaultMenu h1{font-size:32px!important;line-height:1.08;margin:2px 0 6px}
   .nurserySection{margin-top:14px;padding:13px;border-radius:18px;background:rgba(255,255,255,.5);border:1px solid rgba(85,150,190,.14)}.nurserySection h3{margin:0 0 9px;color:#35516b}
   #nurseryEggs{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}#nurseryEggs button{min-width:0!important;margin:0!important;padding:11px 5px!important;font-size:12px!important}
   #hatchResult:empty{display:none}#vaultSlots{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;margin:9px 0 12px}.vaultSlot{min-width:0;min-height:94px;padding:9px 5px;border-radius:15px;background:rgba(226,242,252,.88);border:2px dashed rgba(74,133,173,.28);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px;color:#5c7488}.vaultSlot.filled{background:linear-gradient(150deg,rgba(255,235,151,.92),rgba(255,178,115,.82));border-style:solid;border-color:rgba(238,151,66,.42);color:#3d5367}.vaultSlotIcon{font-size:25px}.vaultSlot b{font-size:11px;line-height:1.15;overflow-wrap:anywhere}.vaultSlot small{font-size:9px;font-weight:900}.vaultSlot button{min-width:0!important;width:auto!important;margin:3px 0 0!important;padding:5px 8px!important;font-size:9px!important;min-height:0!important}#vaultList{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}#vaultList button{min-width:0!important;margin:0!important;padding:10px 7px!important;font-size:12px!important;overflow-wrap:anywhere}
   #closeNurseryVault{position:sticky;bottom:0;z-index:3;width:100%;margin:12px 0 0!important;box-shadow:0 -8px 18px rgba(238,249,255,.92),0 7px 16px rgba(80,120,170,.14)}
   #eggHatchLayer{position:fixed;inset:0;z-index:9999;background:rgba(25,30,60,.62);backdrop-filter:blur(4px);align-items:center;justify-content:center}.eggHatchEgg{font-size:88px;filter:drop-shadow(0 8px 12px #0004);will-change:transform}.eggHatchEgg.shake{animation:eggShake .18s ease-in-out 5}.eggHatchEgg.crack{animation:eggPop .4s ease-out}.hatchBurst{text-align:center;color:#fff;animation:hatchReveal .42s cubic-bezier(.2,.9,.3,1.25)}.hatchBurst .spPuffArt{margin:0 auto 18px;transform:scale(1.35)}.hatchBurst b,.hatchBurst small{display:block;text-shadow:0 2px 8px #0008}.hatchBurst b{font-size:28px}.hatchBurst small{font-size:13px;margin-top:5px}
   @keyframes eggShake{0%,100%{transform:rotate(0)}25%{transform:rotate(-9deg)}75%{transform:rotate(9deg)}}@keyframes eggPop{50%{transform:scale(1.22)}100%{transform:scale(.1);opacity:.2}}@keyframes hatchReveal{from{transform:scale(.3);opacity:0}to{transform:scale(1);opacity:1}}
   @media(max-width:430px){#nurseryVaultMenu{padding-left:6px;padding-right:6px}#nurseryVaultMenu .nurseryVaultCard{width:96vw;max-height:calc(100dvh - 12px);padding:15px 11px 9px;border-radius:22px}#nurseryVaultMenu h1{font-size:27px!important}.nurserySection{padding:10px;margin-top:10px}#nurseryEggs{grid-template-columns:1fr}#nurseryEggs button{min-height:46px!important}#vaultSlots{grid-template-columns:repeat(3,minmax(0,1fr));gap:5px}.vaultSlot{min-height:88px;padding:7px 3px}.vaultSlot b{font-size:10px}#vaultList{grid-template-columns:1fr}#vaultList button{min-height:48px!important}}
   @media(prefers-reduced-motion:reduce){.eggHatchEgg.shake,.eggHatchEgg.crack,.hatchBurst{animation:none!important}}
  `;document.head.appendChild(style);
  const el=document.createElement('div');el.id='nurseryVaultMenu';el.className='overlay';el.style.display='none';el.innerHTML=`<div class="card nurseryVaultCard"><h1>Nursery & Vault 🥚🔐</h1><div class="small">Klekk egg og beskytt opptil ${MAX_VAULT} Pufflings mot Steal My Puffling.</div><section class="nurserySection"><h3>🥚 Nursery</h3><div id="nurseryEggs"></div><div id="hatchResult"></div></section><section class="nurserySection"><h3>🔐 Puff Vault <span id="vaultCount"></span></h3><div class="small">Alle tre Vault-plassene vises under. Hver plass beskytter én Puffling.</div><div id="vaultSlots" aria-label="Tre Puff Vault-plasser"></div><div class="small" style="margin-bottom:8px"><b>Velg Puffling</b> – har du flere kopier av samme type, er bare den lagrede kopien trygg.</div><div id="vaultList"></div></section><button id="closeNurseryVault" class="secondary">TILBAKE</button></div>`;document.body.appendChild(el);
  const layer=document.createElement('div');layer.id='eggHatchLayer';layer.style.display='none';layer.innerHTML='<div id="eggHatchEgg" class="eggHatchEgg">🥚</div><div id="eggHatchReveal"></div>';document.body.appendChild(layer);
  document.getElementById('closeNurseryVault').onclick=()=>{el.style.display='none';document.getElementById('start').style.display='flex'};
  const b=document.createElement('button');b.id='nurseryVaultBtn';b.className='secondary';b.textContent='NURSERY & VAULT 🥚🔐';b.onclick=open;(document.getElementById('menuMoreGrid')||document.querySelector('#start .menuActions'))?.appendChild(b);render();
 }
 function render(){
  const f=F();if(!f)return;const eggs=loadEggs(),box=document.getElementById('nurseryEggs');
  if(box){box.innerHTML='';['rare','epic','legendary'].forEach(t=>{const n=eggs[t]||0,b=document.createElement('button');b.className=t==='legendary'?'gold':'secondary';b.innerHTML=`${t==='rare'?'💙':t==='epic'?'💜':'💛'} ${t.toUpperCase()} EGG<br><small>x${n}</small>`;b.disabled=n<=0||hatching;b.onclick=()=>animateHatch(t);box.appendChild(b)});}
  const s=f.load();s.vault=Array.isArray(s.vault)?[...new Set(s.vault)].filter(id=>(s.owned?.[id]||0)>0).slice(0,MAX_VAULT):[];f.save(s);
  const count=document.getElementById('vaultCount');if(count)count.textContent=`${s.vault.length}/${MAX_VAULT}`;
  const slots=document.getElementById('vaultSlots');if(slots){slots.innerHTML='';for(let i=0;i<MAX_VAULT;i++){const id=s.vault[i],p=id?getPuff(id):null,slot=document.createElement('div');slot.className='vaultSlot'+(id?' filled':'');if(id){slot.innerHTML=`<span class="vaultSlotIcon">${p?.icon||'☁️'}</span><b>${p?.name||id}</b><small>PLASS ${i+1} • TRYGG 🔒</small>`;const remove=document.createElement('button');remove.className='secondary';remove.textContent='FJERN';remove.onclick=()=>toggleVault(id);slot.appendChild(remove);}else slot.innerHTML=`<span class="vaultSlotIcon">➕</span><b>TOM PLASS</b><small>PLASS ${i+1}</small>`;slots.appendChild(slot);}}
  const list=document.getElementById('vaultList');if(list){list.innerHTML='';Object.entries(s.owned||{}).filter(([,n])=>n>0).forEach(([id,n])=>{const p=getPuff(id),locked=s.vault.includes(id),safe=locked?1:0,b=document.createElement('button');b.className=locked?'gold':'secondary';b.innerHTML=`${p?.icon||'☁️'} ${p?.name||id} x${n}<br><small>${locked?`1 TRYGG 🔒 • ${Math.max(0,n-safe)} UTE`:'LEGG 1 I VAULT'}</small>`;b.onclick=()=>{if(!toggleVault(id)&&!locked&&typeof showToast==='function')showToast(`Vault er full (${MAX_VAULT}/${MAX_VAULT})`);};list.appendChild(b)});if(!list.children.length)list.innerHTML='<div class="small">Ingen Pufflings eid ennå.</div>';}
 }
 function open(){ensure();document.getElementById('start').style.display='none';const menu=document.getElementById('nurseryVaultMenu');menu.style.display='flex';menu.scrollTop=0;menu.querySelector('.nurseryVaultCard').scrollTop=0;render();}
 migratePending();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(ensure,40));else setTimeout(ensure,40);window.SkyPuffNurseryVault={loadEggs,addEgg,hatch,animateHatch,toggleVault,open,render,maxVault:MAX_VAULT,pool};
})();
