/* Puffling — Boss Puffling Rewards v0.5 server-authoritative grant */
(function(){
  const DROP_CHANCE=0.35,EPIC_WITHIN_DROP=0.04,LEGENDARY_WITHIN_DROP=0.01;let previousBoss=null,rewardedBossKey='',grantPending=false;
  function fusion(){return window.SkyPuffFusion}function gameplay(){return window.SkyPuffPufflingGameplay}
  function all(){const F=fusion();return F?[...Object.values(F.BASE||{}),...Object.values(F.FUSIONS||{})]:[]}
  function byRarity(r){return all().filter(p=>!p.starterOnly&&p.rarity===r).map(p=>p.id)}function commonPool(){return all().filter(p=>!p.starterOnly&&(p.rarity==='common'||p.rarity==='rare')).map(p=>p.id)}
  function puffInfo(id){return gameplay()?.getPuff?.(id)||all().find(p=>p.id===id)||null}function randomFrom(list){return list.length?list[Math.floor(Math.random()*list.length)]:null}
  function rollPufflingId(){const rr=Math.random();if(rr<LEGENDARY_WITHIN_DROP)return randomFrom(byRarity('legendary'));if(rr<LEGENDARY_WITHIN_DROP+EPIC_WITHIN_DROP)return randomFrom(byRarity('epic'));return randomFrom(commonPool())}
  function endpoint(){try{const ws=localStorage.getItem('skyPuffRaceWsUrl')||window.SKY_PUFF_RACE_WS_URL||'';const u=new URL(ws);u.protocol=u.protocol==='wss:'?'https:':'http:';u.pathname='';u.search='';u.hash='';return u.origin}catch(e){return''}}
  async function identity(){let token='';try{token=localStorage.getItem('pufflingAccountAuthToken')||''}catch(e){}if(token)return token;try{const x=await window.SkyPuffRaceTransport?.ensureGuestIdentity?.();return x?.token||localStorage.getItem('pufflingAccountAuthToken')||''}catch(e){return''}}
  function applyGranted(id){const F=fusion();if(!F)return;F.add(id,1);const p=puffInfo(id);if(gameplay()&&!gameplay().active())gameplay().setActive(id);window.SkyPuffFusionUI?.renderDex?.();const rarity=(p?.rarity||'common').toUpperCase(),rare=(p?.rarity==='epic'||p?.rarity==='legendary')?` ${rarity}!`:' ';if(typeof showToast==='function')showToast(`BOSS DROP!${rare} ${p?.icon||'☁️'} ${p?.name||id} funnet!`)}
  async function requestGrant(key,id){const base=endpoint(),token=await identity();if(!base||!token)throw new Error('reward_server_unavailable');const r=await fetch(base+'/api/acquisition/boss',{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+token,'accept':'application/json'},body:JSON.stringify({bossRef:key,pufflingId:id})});let b={};try{b=await r.json()}catch(e){}if(!r.ok||!b?.ok||!b?.serverAuthoritative)throw new Error(b?.error||'reward_rejected');return b}
  async function rollBossReward(defeated){if(grantPending||!defeated||typeof bossRushMode!=='undefined'&&bossRushMode||typeof bossDefeated!=='undefined'&&!bossDefeated)return;const key=`${defeated.id||'boss'}:${defeated.at||0}:${defeated.tier||1}`;if(key===rewardedBossKey)return;rewardedBossKey=key;if(Math.random()>DROP_CHANCE){if(typeof showToast==='function')showToast('Boss reward: Ingen Puffling denne gangen ☁️');return}const id=rollPufflingId();if(!id)return;grantPending=true;try{const grant=await requestGrant(key,id);applyGranted(grant.pufflingId||id)}catch(e){rewardedBossKey='';if(typeof showToast==='function')showToast('Boss reward kunne ikke bekreftes av serveren — ingen Puffling ble lagt til.')}finally{grantPending=false}}
  function tick(){try{if(typeof boss!=='undefined'){if(boss)previousBoss={id:boss.id,name:boss.name,at:boss.at,tier:boss.tier};else if(previousBoss){const defeated=previousBoss;previousBoss=null;if(typeof running==='undefined'||running)rollBossReward(defeated)}}}catch(e){}requestAnimationFrame(tick)}
  requestAnimationFrame(tick);window.SkyPuffBossPufflingRewards={dropChance:DROP_CHANCE,epicWithinDrop:EPIC_WITHIN_DROP,legendaryWithinDrop:LEGENDARY_WITHIN_DROP,rollBossReward,requestGrant};
})();