/* Orbuff — Race My Orbuff network transport v0.8 */
(function(){
  const PROTOCOL_VERSION=3;
  const AUTH_TOKEN_KEY='pufflingAccountAuthToken',ACCOUNT_ID_KEY='pufflingAccountId',RECOVERY_KEY='pufflingAccountRecoveryKey';
  const listeners=new Map();let socket=null,state='offline',room='',playerId='',authToken='',accountId='',lastSentAt=0,manualClose=false,reconnectTimer=null,reconnectDeadline=0,reconnectAttempt=0,connectedOnce=false,activeUrl='';
  const MIN_POSITION_INTERVAL=66,RECONNECT_WINDOW_MS=11000,RETRY_DELAYS=[300,700,1200,1800,2500,3000],BOT_WAIT_MS=8000,BOT_TICK_MS=100;
  let botTimer=null,botTick=null,bot=null,lastPlayerHeight=0;
  function emit(type,payload){const set=listeners.get(type);if(!set)return;set.forEach(fn=>{try{fn(payload)}catch(e){console.error('[RaceTransport]',e)}});}
  function on(type,fn){if(!listeners.has(type))listeners.set(type,new Set());listeners.get(type).add(fn);return()=>listeners.get(type)?.delete(fn);}
  function endpoint(){try{return localStorage.getItem('skyPuffRaceWsUrl')||window.SKY_PUFF_RACE_WS_URL||'';}catch(e){return window.SKY_PUFF_RACE_WS_URL||'';}}
  function apiBase(wsUrl){const configured=String(window.skyPuffConfig?.gameApiUrl||window.skyPuffConfig?.apiBase||window.SKY_PUFF_GAME_API_URL||'').trim();if(configured)return configured.replace(/\/$/,'');try{const u=new URL(wsUrl||endpoint());u.protocol=u.protocol==='wss:'?'https:':'http:';u.pathname='';u.search='';u.hash='';return u.origin;}catch(e){return '';}}
  function readIdentity(){try{return{token:String(localStorage.getItem(AUTH_TOKEN_KEY)||''),accountId:String(localStorage.getItem(ACCOUNT_ID_KEY)||''),recoveryKey:String(localStorage.getItem(RECOVERY_KEY)||'')}}catch(e){return{token:'',accountId:'',recoveryKey:''}}}
  function storeIdentity(token,id,recoveryKey){authToken=String(token||'');accountId=String(id||'');try{if(authToken)localStorage.setItem(AUTH_TOKEN_KEY,authToken);else localStorage.removeItem(AUTH_TOKEN_KEY);if(accountId)localStorage.setItem(ACCOUNT_ID_KEY,accountId);else localStorage.removeItem(ACCOUNT_ID_KEY);if(recoveryKey)localStorage.setItem(RECOVERY_KEY,String(recoveryKey));}catch(e){}return readIdentity();}
  function setAuthToken(token,{persist=true}={}){authToken=String(token||'');if(persist){const saved=readIdentity();storeIdentity(authToken,accountId||saved.accountId,saved.recoveryKey);}return authToken;}
  function tokenClaims(token){try{const body=String(token||'').split('.')[0];if(!body)return null;const normalized=body.replace(/-/g,'+').replace(/_/g,'/');const padded=normalized+'='.repeat((4-normalized.length%4)%4);return JSON.parse(decodeURIComponent(Array.prototype.map.call(atob(padded),c=>'%'+c.charCodeAt(0).toString(16).padStart(2,'0')).join('')));}catch(e){return null;}}
  function tokenFresh(token,skewSeconds=90){const claims=tokenClaims(token),exp=Number(claims?.exp||0),sub=String(claims?.sub||'');return !!sub&&Number.isFinite(exp)&&exp>(Date.now()/1000)+skewSeconds;}
  async function requestAccount(base,path,opts={}){const headers={accept:'application/json',...(opts.body?{'content-type':'application/json'}:{})};if(opts.token)headers.authorization=`Bearer ${opts.token}`;const response=await fetch(base+path,{method:opts.method||'POST',headers,body:opts.body?JSON.stringify(opts.body):undefined});let body={};try{body=await response.json();}catch(e){}if(!response.ok||body?.ok===false)throw new Error(body?.error||`http_${response.status}`);return body;}
  async function provisionRecovery(base,saved){
    if(!saved.token||!saved.accountId||saved.recoveryKey)return saved;
    const body=await requestAccount(base,'/api/account/recovery',{token:saved.token});
    if(!body?.recoveryKey)throw new Error('account_recovery_key_missing');
    return storeIdentity(saved.token,saved.accountId,body.recoveryKey);
  }
  async function ensureGuestIdentity(){
    const saved=readIdentity(),base=apiBase(activeUrl||endpoint());
    if(saved.token&&tokenFresh(saved.token)){
      authToken=saved.token;accountId=saved.accountId||String(tokenClaims(saved.token)?.sub||'');
      if(saved.recoveryKey||!base)return storeIdentity(authToken,accountId,saved.recoveryKey);
      return provisionRecovery(base,{token:authToken,accountId,recoveryKey:''});
    }
    if(!base)throw new Error('account_endpoint_missing');
    if(saved.accountId&&saved.recoveryKey){
      const recovered=await requestAccount(base,'/api/account/recover',{body:{accountId:saved.accountId,recoveryKey:saved.recoveryKey}});
      if(!recovered?.token||!recovered?.accountId)throw new Error('account_recovery_failed');
      return storeIdentity(recovered.token,recovered.accountId,saved.recoveryKey);
    }
    if(saved.accountId&&!saved.recoveryKey&&saved.token){
      // Legacy beta identity with an expired token cannot be proven after expiry. Do not silently overwrite it.
      throw new Error('legacy_account_recovery_required');
    }
    const created=await requestAccount(base,'/api/account/guest');
    if(!created?.token||!created?.accountId||!created?.recoveryKey)throw new Error('account_bootstrap_failed');
    return storeIdentity(created.token,created.accountId,created.recoveryKey);
  }
  async function rotateRecoveryKey(){const id=await ensureGuestIdentity();const base=apiBase(activeUrl||endpoint());if(!base)throw new Error('account_endpoint_missing');const body=await requestAccount(base,'/api/account/recovery',{token:id.token});if(!body?.recoveryKey)throw new Error('account_recovery_key_missing');return storeIdentity(id.token,id.accountId,body.recoveryKey);}
  async function recoverGuestIdentity(id,recoveryKey){const base=apiBase(activeUrl||endpoint());if(!base)throw new Error('account_endpoint_missing');const body=await requestAccount(base,'/api/account/recover',{body:{accountId:String(id||'').trim(),recoveryKey:String(recoveryKey||'').trim()}});if(!body?.token||!body?.accountId)throw new Error('account_recovery_failed');return storeIdentity(body.token,body.accountId,String(recoveryKey||'').trim());}
  function clearStoredIdentity(){authToken='';accountId='';try{localStorage.removeItem(AUTH_TOKEN_KEY);localStorage.removeItem(ACCOUNT_ID_KEY);localStorage.removeItem(RECOVERY_KEY);}catch(e){}}
  function setState(next,extra={}){state=next;emit('state',{state,room,playerId,reconnectDeadline,...extra});}
  function clearReconnect(){if(reconnectTimer){clearTimeout(reconnectTimer);reconnectTimer=null;}}
  function clearBot(){if(botTimer){clearTimeout(botTimer);botTimer=null;}if(botTick){clearInterval(botTick);botTick=null;}bot=null;lastPlayerHeight=0;}
  function sendRaw(msg){if(socket&&socket.readyState===WebSocket.OPEN){socket.send(JSON.stringify(msg));return true;}return false;}
  function botPublic(){return{playerId:'BOT_MEDIUM',accountId:null,pufflingId:bot?.pufflingId||'volt',skin:'default',evolutionStage:1,rankRating:1000,rankAuthenticated:false,ready:true,connected:true,height:Math.floor(bot?.height||0),x:bot?.x||0,y:null,worldY:null,attacksUsed:bot?.attacksUsed||0,bot:true,difficulty:'medium'};}
  function startBotFallback(){if(bot||manualClose)return;manualClose=true;try{socket?.close(1000,'bot fallback')}catch(e){}socket=null;clearReconnect();const startAt=Date.now()+3000;bot={height:0,x:0,startedAt:startAt,lastAt:startAt,attacksUsed:0,nextAttackAt:.32,finished:false,pufflingId:['ember','volt','frost','wind'][Math.floor(Math.random()*4)]};setState('bot',{bot:true,difficulty:'medium'});emit('race:opponentJoined',{room,player:botPublic(),bot:true});emit('race:start',{room,mode:'bot',serverStartAt:startAt,countdownMs:3000,goal:1500,courseSeed:`BOT_${room}`,courseVersion:1,players:[{playerId,accountId,pufflingId:null,ready:true,connected:true,height:0},botPublic()],bot:true,difficulty:'medium'});
    botTick=setInterval(()=>{if(!bot||bot.finished||Date.now()<bot.startedAt)return;const t=Date.now(),dt=Math.min(.25,Math.max(.02,(t-bot.lastAt)/1000));bot.lastAt=t;const progress=Math.max(lastPlayerHeight,bot.height)/1500;const rubber=(lastPlayerHeight-bot.height)*.018;const base=11.2+Math.sin(t/1700)*1.2;const jitter=(Math.random()-.5)*2.2;bot.height=Math.max(bot.height,Math.min(1500,bot.height+(base+rubber+jitter)*dt));bot.x=Math.sin(t/700)*120;emit('race:position',{type:'race:position',room,playerId:'BOT_MEDIUM',t,x:bot.x,y:null,worldY:null,height:bot.height,state:'jumping',pufflingId:bot.pufflingId,skin:'default',evolutionStage:1,bot:true});if(bot.attacksUsed<3&&progress>=bot.nextAttackAt){bot.attacksUsed++;bot.nextAttackAt=[.32,.60,.82,2][bot.attacksUsed]||2;emit('race:attack',{type:'race:attack',room,playerId:'BOT_MEDIUM',ability:'gust',abilityId:'gust',attacksUsed:bot.attacksUsed,remaining:3-bot.attacksUsed,bot:true});}if(bot.height>=1500){bot.finished=true;clearInterval(botTick);botTick=null;emit('race:result',{type:'race:result',room,mode:'bot',winnerId:'BOT_MEDIUM',finishedAt:t,goal:1500,reason:'bot_finish',rank:null,rankServerAuthoritative:false,players:[{playerId,height:lastPlayerHeight},botPublic()],bot:true});}},BOT_TICK_MS);
  }
  function armBotFallback(m){if(botTimer||bot||m?.mode!=='quick'||!Array.isArray(m.players)||m.players.length!==1)return;botTimer=setTimeout(()=>{botTimer=null;startBotFallback();},BOT_WAIT_MS);}
  function handleMessage(ev){try{const m=JSON.parse(ev.data);if(!m||!m.type)return;if(m.room)room=String(m.room);if(m.type==='race:matched')armBotFallback(m);if(m.type==='race:opponentJoined'||m.type==='race:start'){if(botTimer){clearTimeout(botTimer);botTimer=null;}}if(m.type==='race:error'&&['race_auth_required','rank_auth_required','unsupported_protocol'].includes(String(m.code||'')))setState('server_rejected',{code:m.code,expectedProtocol:m.expectedProtocol});emit(m.type,m);}catch(e){}}
  function scheduleReconnect(){clearReconnect();if(manualClose||!activeUrl)return;if(!reconnectDeadline)reconnectDeadline=Date.now()+RECONNECT_WINDOW_MS;if(Date.now()>=reconnectDeadline){setState('reconnect_failed');emit('reconnect_failed',{room,playerId});return;}const delay=RETRY_DELAYS[Math.min(reconnectAttempt,RETRY_DELAYS.length-1)];reconnectAttempt++;reconnectTimer=setTimeout(()=>openSocket(activeUrl,true),delay);}
  function openSocket(url,isReconnect=false){clearReconnect();if(manualClose)return;try{socket=new WebSocket(url);setState(isReconnect?'reconnecting':'connecting',{attempt:reconnectAttempt});const timeout=setTimeout(()=>{if(socket&&socket.readyState!==WebSocket.OPEN){try{socket.close()}catch(e){}}},3500);socket.onopen=()=>{clearTimeout(timeout);connectedOnce=true;reconnectAttempt=0;setState('online',{resumed:isReconnect});sendRaw({type:'race:hello',room,playerId,protocol:PROTOCOL_VERSION,resume:isReconnect,authToken});};socket.onmessage=handleMessage;socket.onerror=()=>{};socket.onclose=()=>{clearTimeout(timeout);socket=null;if(manualClose){if(!bot)setState('offline');return;}if(connectedOnce){setState('reconnecting');scheduleReconnect();}else setState('connect_failed');};}catch(e){socket=null;if(connectedOnce){setState('reconnecting');scheduleReconnect();}else setState('connect_failed');}}
  async function connect(opts={}){clearBot();room=opts.room||room||'';playerId=opts.playerId||playerId||('p_'+Math.random().toString(36).slice(2,10));activeUrl=opts.url||endpoint();manualClose=false;reconnectAttempt=0;reconnectDeadline=0;connectedOnce=false;const saved=readIdentity();authToken=String(opts.authToken||saved.token||'');accountId=saved.accountId||'';if(!activeUrl){setState('local');return{mode:'local',room,playerId,authenticated:!!authToken,accountId};}if(!authToken||!tokenFresh(authToken)){setState('authenticating');try{const identity=await ensureGuestIdentity();authToken=identity.token;accountId=identity.accountId;}catch(e){setState('race_auth_failed',{error:String(e?.message||e)});return{mode:'auth_failed',room,playerId,authenticated:false,error:String(e?.message||e)};}}return new Promise(resolve=>{let settled=false;const off=on('state',m=>{if(settled)return;if(m.state==='online'){settled=true;off();resolve({mode:'online',room,playerId,authenticated:!!authToken,accountId});}if(['connect_failed','server_rejected'].includes(m.state)){settled=true;off();manualClose=true;try{socket?.close()}catch(e){}socket=null;resolve({mode:'error',room,playerId,authenticated:!!authToken,accountId,error:m.code||m.state});}});openSocket(activeUrl,false);setTimeout(()=>{if(settled)return;settled=true;off();manualClose=true;try{socket?.close()}catch(e){}socket=null;setState('local');resolve({mode:'local',room,playerId,authenticated:!!authToken,accountId});},4200);});}
  function sendPosition(data){const t=performance.now();if(t-lastSentAt<MIN_POSITION_INTERVAL)return false;lastSentAt=t;if(bot){lastPlayerHeight=Math.max(lastPlayerHeight,Number(data?.height)||0);if(lastPlayerHeight>=1500&&!bot.finished){bot.finished=true;if(botTick){clearInterval(botTick);botTick=null;}emit('race:result',{type:'race:result',room,mode:'bot',winnerId:playerId,finishedAt:Date.now(),goal:1500,reason:'finish',rank:null,rankServerAuthoritative:false,players:[{playerId,height:lastPlayerHeight},botPublic()],bot:true});}return true;}return sendRaw({type:'race:position',room,playerId,t:Date.now(),...data});}
  function sendAttack(data){if(bot)return true;return sendRaw({type:'race:attack',room,playerId,t:Date.now(),...data});}function sendFinish(data){if(bot){lastPlayerHeight=Math.max(lastPlayerHeight,Number(data?.height)||0);return true;}return sendRaw({type:'race:finish',room,playerId,t:Date.now(),...data});}function sendReady(data={}){if(bot)return true;return sendRaw({type:'race:ready',room,playerId,t:Date.now(),...data});}
  function disconnect(){manualClose=true;clearReconnect();clearBot();reconnectDeadline=0;reconnectAttempt=0;if(socket){try{socket.close(1000,'leave race')}catch(e){}}socket=null;setState('offline');}
  function snapshot(){const saved=readIdentity();return{state,room,playerId,accountId:saved.accountId||accountId,authenticated:!!(saved.token||authToken),recoverable:!!(saved.accountId&&saved.recoveryKey),online:state==='online'||state==='bot',bot:!!bot,reconnecting:state==='reconnecting',reconnectDeadline,endpoint:endpoint(),protocolVersion:PROTOCOL_VERSION};}
  window.SkyPuffRaceTransport={connect,disconnect,on,sendPosition,sendAttack,sendFinish,sendReady,snapshot,setAuthToken,ensureGuestIdentity,rotateRecoveryKey,recoverGuestIdentity,clearStoredIdentity,readIdentity,tokenFresh,protocolVersion:PROTOCOL_VERSION,botFallbackMs:BOT_WAIT_MS};
})();
