/* Puffling — Ranked Quick Race v2.0
 * Server-authoritative Quick Race rank. Friend/local races never change MMR.
 */
(function(){
  const KEY='pufflingQuickRaceRankV1';
  const START_RATING=1000,MIN_RATING=600;
  const TIERS=[{name:'Bronze',min:0,icon:'🟤'},{name:'Silver',min:1000,icon:'⚪'},{name:'Gold',min:1200,icon:'🟡'},{name:'Platinum',min:1400,icon:'🔷'},{name:'Diamond',min:1600,icon:'💎'},{name:'Master',min:1800,icon:'👑'},{name:'Champion',min:2000,icon:'🏆'}];
  let currentMode='idle',currentRoom='',lastUpdate=null,transportBound=false;
  function finite(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}
  function normalize(raw={}){const rating=Math.max(MIN_RATING,Math.round(finite(raw.rating,START_RATING)));return{rating,wins:Math.max(0,Math.floor(finite(raw.wins,0))),losses:Math.max(0,Math.floor(finite(raw.losses,0))),games:Math.max(0,Math.floor(finite(raw.games,0))),streak:Math.max(0,Math.floor(finite(raw.streak,0))),bestRating:Math.max(rating,Math.round(finite(raw.bestRating,rating))),lastDelta:Math.round(finite(raw.lastDelta,0)),lastRaceId:String(raw.lastRaceId||'')};}
  function load(){try{return normalize(JSON.parse(localStorage.getItem(KEY)||'{}'));}catch(e){return normalize();}}
  function saveState(s){s=normalize(s);try{localStorage.setItem(KEY,JSON.stringify(s));}catch(e){}return s;}
  function rankFor(rating){const r=Math.max(0,Math.round(finite(rating,START_RATING)));let i=0;for(let x=0;x<TIERS.length;x++)if(r>=TIERS[x].min)i=x;const tier=TIERS[i],next=TIERS[i+1]||null;if(!next)return{...tier,division:'',label:`${tier.icon} ${tier.name}`,progress:1,nextMin:null,nextName:null};const span=Math.max(1,next.min-tier.min),within=Math.max(0,Math.min(span-1,r-tier.min)),third=span/3,division=within<third?'III':within<third*2?'II':'I';return{...tier,division,label:`${tier.icon} ${tier.name} ${division}`,progress:Math.max(0,Math.min(1,within/span)),nextMin:next.min,nextName:next.name};}
  function profile(){const s=load();return{...s,rank:rankFor(s.rating)};}
  function mineId(){try{return window.SkyPuffRaceTransport?.snapshot?.().playerId||'';}catch(e){return '';}}
  function applyServerResult(message){
    if(currentMode!=='quick'||!message?.rankServerAuthoritative||!message?.rank)return{applied:false,reason:'server-rank-required',profile:profile()};
    const raceId=String(message.room||currentRoom||'');if(!raceId)return{applied:false,reason:'missing-race-id',profile:profile()};
    const mine=mineId(),me=Array.isArray(message.players)?message.players.find(p=>p?.playerId===mine):null;
    const profiles=message.rank.profiles||{};let serverProfile=null;
    if(me?.accountId&&profiles[me.accountId])serverProfile=profiles[me.accountId];
    if(!serverProfile&&me?.rankRating!=null){const before=load();serverProfile={...before,rating:me.rankRating};}
    if(!serverProfile)return{applied:false,reason:'missing-server-profile',profile:profile()};
    const before=load();if(before.lastRaceId===raceId)return{applied:false,reason:'duplicate-result',profile:profile()};
    const after=saveState({...before,...serverProfile,lastRaceId:raceId,lastDelta:Math.round(finite(serverProfile.rating,before.rating)-before.rating)});
    lastUpdate={applied:true,won:message.winnerId===mine,delta:after.lastDelta,before:{...before,rank:rankFor(before.rating)},after:{...after,rank:rankFor(after.rating)},raceId,at:Date.now(),serverAuthoritative:true};
    try{window.dispatchEvent(new CustomEvent('race:rankUpdate',{detail:lastUpdate}));}catch(e){}render();return lastUpdate;
  }
  function resultRankHtml(){if(currentMode!=='quick')return'';if(lastUpdate&&Date.now()-lastUpdate.at<15000){const u=lastUpdate,a=u.after,sign=u.delta>0?'+':'';return`<div id="raceRankResult" style="margin-top:14px;padding:12px;border-radius:15px;background:rgba(255,255,255,.72);font-weight:900"><div style="font-size:15px">${a.rank.label}</div><div style="margin-top:4px">MMR <b>${a.rating}</b> <span style="font-weight:1000">(${sign}${u.delta})</span></div><div style="font-size:11px;opacity:.72;margin-top:3px">Server verified • ${a.wins}W / ${a.losses}L</div></div>`;}return'<div id="raceRankResult" style="margin-top:14px;padding:12px;border-radius:15px;background:rgba(255,255,255,.72);font-size:12px;font-weight:900">Rank unchanged — verified server result required.</div>';}
  function decorateResult(){if(typeof document==='undefined')return;const body=document.getElementById('raceResultBody');if(!body)return;body.querySelector('#raceRankResult')?.remove();const html=resultRankHtml();if(html)body.insertAdjacentHTML('beforeend',html);}
  function ensureCard(){const card=document.querySelector('#multiplayerMenu .card');if(!card)return null;let box=document.getElementById('raceRankPanel');if(!box){box=document.createElement('div');box.id='raceRankPanel';box.style.cssText='margin:10px 0 12px;padding:12px 14px;border-radius:17px;background:rgba(255,255,255,.78);border:1px solid rgba(63,136,190,.2);box-shadow:0 7px 20px rgba(37,94,137,.08)';const quick=document.getElementById('quickMatchBtn');if(quick)quick.insertAdjacentElement('beforebegin',box);else card.appendChild(box);}return box;}
  function render(){if(typeof document==='undefined')return;const p=profile(),box=ensureCard();if(!box)return;const next=p.rank.nextMin?`${Math.max(0,p.rank.nextMin-p.rating)} MMR to ${p.rank.nextName}`:'Top rank';box.innerHTML=`<div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><div><div style="font-size:11px;font-weight:1000;letter-spacing:.8px;opacity:.62">QUICK RACE RANK</div><div style="font-size:21px;font-weight:1000;margin-top:2px">${p.rank.label}</div></div><div style="text-align:right"><div style="font-size:19px;font-weight:1000">${p.rating}</div><div style="font-size:10px;font-weight:900;opacity:.64">MMR</div></div></div><div style="height:7px;background:rgba(40,80,120,.12);border-radius:999px;margin-top:9px;overflow:hidden"><div style="height:100%;width:${Math.round(p.rank.progress*100)}%;background:linear-gradient(90deg,#63b7ff,#9b75ff);border-radius:999px"></div></div><div style="display:flex;justify-content:space-between;gap:8px;margin-top:7px;font-size:10px;font-weight:900;opacity:.72"><span>${p.wins}W • ${p.losses}L</span><span>${next}</span></div>`;}
  function bindTransport(){if(transportBound)return;const T=window.SkyPuffRaceTransport;if(!T)return;transportBound=true;T.on('race:matched',m=>{currentMode=m?.mode==='quick'?'quick':'friend';currentRoom=String(m?.room||'');render();});T.on('race:result',m=>{if(currentMode!=='quick')return;applyServerResult(m);setTimeout(decorateResult,0);});}
  function patchGameHooks(){if(typeof window.startMultiplayerRace==='function'&&!window.startMultiplayerRace.__rankWrapped){const base=window.startMultiplayerRace,wrapped=function(type){currentMode=type==='random'?'quick':'friend';currentRoom='';lastUpdate=null;return base.apply(this,arguments);};wrapped.__rankWrapped=true;window.startMultiplayerRace=wrapped;}if(window.SkyPuffRaceUI?.showResult&&!window.SkyPuffRaceUI.showResult.__rankWrapped){const base=window.SkyPuffRaceUI.showResult,wrapped=function(){const out=base.apply(this,arguments);decorateResult();return out;};wrapped.__rankWrapped=true;window.SkyPuffRaceUI.showResult=wrapped;}if(typeof window.openMultiplayer==='function'&&!window.openMultiplayer.__rankWrapped){const base=window.openMultiplayer,wrapped=function(){const out=base.apply(this,arguments);setTimeout(render,0);return out;};wrapped.__rankWrapped=true;window.openMultiplayer=wrapped;}}
  function init(){bindTransport();patchGameHooks();render();}
  window.SkyPuffQuickRank={profile,rankFor,applyServerResult,render,decorateResult,get lastUpdate(){return lastUpdate;},START_RATING,MIN_RATING,rankServerAuthoritative:true,version:2};
  if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,40));else setTimeout(init,40);}else{bindTransport();patchGameHooks();}
})();
