function stopActiveModes(){
 running=false;paused=false;bossRushMode=false;bossRushSelected=null;
 if(typeof cancelBossWarning==='function')cancelBossWarning();else{bossWarningActive=false;bossPendingStage=null;if(bossWarningEl)bossWarningEl.style.display='none';}
 bossArena=false;bossArenaY=0;boss=null;bossSpawned=false;playerShots=[];bossShots=[];
 if(multiplayerInterval){clearInterval(multiplayerInterval);multiplayerInterval=null;}
 multiplayerMode=false;multiplayerState='idle';multiplayerOpponentScore=0;multiplayerEndAt=0;endlessEvent=null;endlessEventTime=0;
 stopBossMusic(false);
 if(typeof clearTransientUi==='function')clearTransientUi();
 if(multiplayerHudEl)multiplayerHudEl.style.display='none';if(multiplayerMenuEl)multiplayerMenuEl.style.display='none';if(bossRushMenuEl)bossRushMenuEl.style.display='none';if(pauseMenuEl)pauseMenuEl.style.display='none';if(resumeCountdownEl)resumeCountdownEl.style.display='none';if(bossWrap)bossWrap.style.display='none';if(bossIdentityEl)bossIdentityEl.style.display='none';
}
function showMainMenu(){stopActiveModes();gameOverEl.style.display='none';missionCompleteEl.style.display='none';shopEl.style.display='none';upgradesEl.style.display='none';if(audioSettingsEl)audioSettingsEl.style.display='none';if(leaderboardMenuEl)leaderboardMenuEl.style.display='none';refreshMenu();startEl.style.display='flex';startMusic();}
function reset(){stopBossMusic(false);if(typeof clearTransientUi==='function')clearTransientUi();if(typeof cancelBossWarning==='function')cancelBossWarning();bossRushMode=false;bossRushSelected=null;lastBossTriggerAt=0;cameraY=0;score=0;coins=0;boost=100;combo=1;bestCombo=1;comboTimer=0;invuln=0;shield=0;superShieldCharges=0;magnet=0;mega=0;coinRush=0;rainbowOvercharge=0;endlessEvent=null;endlessEventTime=0;nextEndlessEventAt=5200;boss=null;bossSpawned=false;bossDefeated=false;bossArena=false;bossArenaY=0;defeatedBosses={storm:false,candy:false,ice:false,galaxy:false};nextLifePickupAt=500;nextMilestoneRewardAt=2500;const startPlatformY=H*.82;player={x:W/2,y:startPlatformY-28,vx:0,vy:-10.6,r:28,rot:0,hp:3+save.upHealth};platforms=[];coinItems=[];clouds=[];enemies=[];powerups=[];particles=[];playerShots=[];bossShots=[];skySparkles=[];screenShake=0;puffAnim=-1;bossFlash=0;let y=startPlatformY;platforms.push({x:W/2-55,y,w:110,h:18,move:false,breakable:false});for(let i=0;i<30;i++){y-=70+Math.random()*35;addPlatform(y)}for(let i=0;i<11;i++)clouds.push({x:Math.random()*W,y:Math.random()*H,s:.5+Math.random()*.9,drift:.08+Math.random()*.18});for(let i=0;i<28;i++)skySparkles.push({x:Math.random()*W,y:Math.random()*H,tw:Math.random()*6.28,s:.7+Math.random()*1.8});setMission();scoreEl.textContent=0;coinsEl.textContent=0;hpEl.textContent=player.hp;streakEl.textContent=save.streak;boostEl.style.width='100%';bossWrap.style.display='none';if(bossIdentityEl)bossIdentityEl.style.display='none';}
function startGame(){stopActiveModes();reset();paused=false;running=true;startEl.style.display='none';gameOverEl.style.display='none';missionCompleteEl.style.display='none';shopEl.style.display='none';upgradesEl.style.display='none';lastTime=performance.now();startMusic();requestAnimationFrame(loop)}
function openShop(){renderShop();applyLanguage();startEl.style.display='none';shopEl.style.display='flex';}
function closeShop(){shopEl.style.display='none';startEl.style.display='flex';}
playBtnEl.onclick=startGame;retryBtnEl.onclick=startGame;menuBtnEl.onclick=showMainMenu;if(continueBtnEl)continueBtnEl.onclick=()=>{missionCompleteEl.style.display='none'};
leaderboardBtnEl.onclick=()=>{startEl.style.display='none';leaderboardMenuEl.style.display='flex';loadLeaderboard();};closeLeaderboardEl.onclick=()=>{leaderboardMenuEl.style.display='none';startEl.style.display='flex';};refreshLeaderboardEl.onclick=loadLeaderboard;playerNameEl.addEventListener('change',()=>{save.playerName=cleanPlayerName(playerNameEl.value);playerNameEl.value=save.playerName;persist();});shopBtnEl.onclick=openShop;closeShopEl.onclick=closeShop;upgradeBtnEl.onclick=()=>{renderUpgrades();applyLanguage();startEl.style.display='none';upgradesEl.style.display='flex'};closeUpgradesEl.onclick=()=>{upgradesEl.style.display='none';startEl.style.display='flex'};dailyBtnEl.onclick=()=>{const now=Date.now(),day=86400000;if(now-save.lastDaily>=day){const reward=250;save.bank+=reward;save.lastDaily=now;save.streak++;persist();refreshMenu();showToast(tr('dailyReward',{streak:save.streak,reward}))}else showToast(tr('dailyClaimed'))};
function pauseGame(){if(!running||paused)return;paused=true;pauseMenuEl.style.display='flex';}function resumeGame(){if(!running||!paused)return;pauseMenuEl.style.display='none';resumeCountdownEl.style.display='flex';const started=performance.now();function countdown(now){if(!running){resumeCountdownEl.style.display='none';return;}const left=Math.max(0,1500-(now-started));resumeCountdownTextEl.textContent=(left/1000).toFixed(1);if(left>0){requestAnimationFrame(countdown);}else{resumeCountdownEl.style.display='none';paused=false;lastTime=performance.now();requestAnimationFrame(loop);}}requestAnimationFrame(countdown);}pauseBtnEl.onclick=pauseGame;resumeBtnEl.onclick=resumeGame;pauseMenuBtnEl.onclick=showMainMenu;
function unlockBossCosmetic(id){const key='boss'+id.charAt(0).toUpperCase()+id.slice(1);if(!save[key]){save[key]=true;persist();setTimeout(()=>showToast(tr('bossCosmetic')),1250);}}
function renderChoiceRow(row,obj,currentKey,saveKey){row.innerHTML='';Object.entries(obj).forEach(([id,s])=>{const bossUnlocked=s.boss?save['boss'+s.boss.charAt(0).toUpperCase()+s.boss.slice(1)]:false;const achievementUnlocked=s.achievement?!!save[s.achievement]:false;const unlocked=bossUnlocked||achievementUnlocked||save.total>=s.need,b=document.createElement('button');b.className='skin'+(unlocked?'':' locked')+(save[currentKey]===id?' selected':'');b.textContent=unlocked?s.name:(s.boss?'🔒 Boss reward':s.achievement?'🔒 Achievement reward':`🔒 ${s.need}m`);b.onclick=()=>{if(!unlocked)return showToast(s.boss?tr('bossUnlock'):s.achievement?'Krev achievement 🏅':tr('needHeight',{need:s.need}));save[currentKey]=id;persist();renderShop();};row.appendChild(b);});}
function renderShop(){renderChoiceRow(skinrowEl,skins,'skin','skyPuffSkin');renderChoiceRow(facerowEl,faceStyles,'face','skyPuffFace');renderChoiceRow(hatrowEl,hats,'hat','skyPuffHat');renderChoiceRow(trailrowEl,trailStyles,'trail','skyPuffTrail');}
const upgrades=[{key:'upBoost',name:'Rainbow Tank',desc:'Lavere puff-kostnad og sterkere boost.',base:1000,max:5},{key:'upMagnet',name:'Magnet Power',desc:'Lengre magnet-varighet.',base:1250,max:5},{key:'upCoin',name:'Coin Bonus',desc:'Flere bankmynter per runde.',base:1500,max:5},{key:'upHealth',name:'Ekstra Liv',desc:'Starter med mer helse.',base:2000,max:3}];
function upgradeLabel(u){const map={no:{upBoost:['Rainbow Tank','Lavere puff-kostnad og sterkere boost.'],upHealth:['Ekstra Liv','Starter med mer helse.'],upCoin:['Coin Bonus','Flere bankmynter per runde.'],upMagnet:['Magnet Power','Lengre magnet-varighet.']},en:{upBoost:['Rainbow Tank','Lower puff cost and stronger boost.'],upHealth:['Extra Life','Start each run with more health.'],upCoin:['Coin Bonus','More bank coins per run.'],upMagnet:['Magnet Power','Longer magnet duration.']},de:{upBoost:['Rainbow Tank','Geringere Puff-Kosten und stärkerer Boost.'],upHealth:['Extra Leben','Starte jede Runde mit mehr Leben.'],upCoin:['Coin Bonus','Mehr Bankmünzen pro Runde.'],upMagnet:['Magnet Power','Längere Magnet-varighet.']},es:{upBoost:['Rainbow Tank','Menor coste de puff y boost más fuerte.'],upHealth:['Vida Extra','Empieza cada partida con más vida.'],upCoin:['Coin Bonus','Más monedas para el banco por partida.'],upMagnet:['Magnet Power','Mayor duración del imán.']},fr:{upBoost:['Rainbow Tank','Coût de puff réduit et boost plus puissant.'],upHealth:['Vie Supplémentaire','Commence chaque partie avec plus de vie.'],upCoin:['Coin Bonus','Plus de pièces en banque par partie.'],upMagnet:['Magnet Power','Durée de l’aimant augmentée.']}};return(map[lang]||map.no)[u.key]||[u.name,u.desc];}
function renderUpgrades(){upgraderowEl.innerHTML='';upgrades.forEach(u=>{const lv=save[u.key],cost=Math.floor(u.base*Math.pow(1.8,lv)),b=document.createElement('button');b.className='upgrade';const[nm,ds]=upgradeLabel(u);const priceLabel=lang==='en'?'Price':lang==='de'?'Preis':lang==='es'?'Precio':lang==='fr'?'Prix':'Pris';b.innerHTML=`<strong>${nm} — Lv ${lv}/${u.max}</strong><small>${ds}<br>${lv>=u.max?tr('maxLevel'):`${priceLabel}: ${cost} 🪙`}</small>`;b.onclick=()=>{if(lv>=u.max)return showToast(tr('maxLevel'));if(save.bank<cost)return showToast(tr('needCoins'));save.bank-=cost;save[u.key]++;persist();renderUpgrades();refreshMenu();showToast(tr('upgraded',{name:upgradeLabel(u)[0]}))};upgraderowEl.appendChild(b)})}