/* Sky Puff — Steal My Puff winner choice UI v0.1 */
(function(){
  function ensureUI(){if(document.getElementById('stealMyPuffResult'))return;const el=document.createElement('div');el.id='stealMyPuffResult';el.className='overlay';el.style.display='none';el.innerHTML='<div class="card" style="max-width:560px"><h1 style="font-size:36px">DU VANT! 🏆</h1><div class="small" style="margin-bottom:14px">Velg premien din</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><button id="chooseMysteryBox" class="gold">🎁 MYSTERY BOX</button><button id="chooseStealPuff" class="secondary">😈 STEAL PUFFLING</button></div><div id="stealChoiceArea" style="margin-top:14px"></div></div>';document.body.appendChild(el);document.getElementById('chooseMysteryBox').onclick=openBox;document.getElementById('chooseStealPuff').onclick=renderStealChoices;}
  function rivalState(){const f=window.SkyPuffFusion;if(!f)return {owned:{},vault:[],discovered:[]};const ids=Object.keys(f.BASE);const owned={};for(let i=0;i<3;i++){const id=ids[Math.floor(Math.random()*ids.length)];owned[id]=(owned[id]||0)+1;}return {owned,vault:[],discovered:Object.keys(owned)};}
  let currentRival=null;
  function show(){ensureUI();currentRival=rivalState();document.getElementById('stealChoiceArea').innerHTML='';document.getElementById('stealMyPuffResult').style.display='flex';}
  function finish(msg){if(typeof showToast==='function')showToast(msg);document.getElementById('stealMyPuffResult').style.display='none';setTimeout(()=>typeof showMainMenu==='function'&&showMainMenu(),350);}
  function openBox(){const S=window.SkyPuffSteal,F=window.SkyPuffFusion;if(!S||!F)return;const reward=S.mysteryBox();if(reward.type==='coins'){if(typeof save!=='undefined'){save.bank=(save.bank||0)+reward.amount;if(typeof persist==='function')persist();if(typeof refreshMenu==='function')refreshMenu();}}else if(reward.type==='egg'){const ids=Object.keys(F.BASE);F.add(ids[Math.floor(Math.random()*ids.length)],1);}else{try{const k='skyPuffItemsV1',v=JSON.parse(localStorage.getItem(k)||'{}');v[reward.id]=(v[reward.id]||0)+(reward.amount||1);localStorage.setItem(k,JSON.stringify(v));}catch(e){}}finish(`Mystery Box: ${reward.label}! 🎁`);}
  function renderStealChoices(){const S=window.SkyPuffSteal,F=window.SkyPuffFusion,area=document.getElementById('stealChoiceArea');if(!S||!F||!area)return;const choices=S.stealablePufflings(currentRival);area.innerHTML='<div class="small" style="margin-bottom:8px">Velg én Puffling fra motstanderen:</div>';choices.forEach(x=>{const p=[...Object.values(F.BASE),...Object.values(F.FUSIONS)].find(q=>q.id===x.id);const b=document.createElement('button');b.className='secondary';b.style.margin='5px';b.textContent=`${p?.icon||'☁️'} ${p?.name||x.id}`;b.onclick=()=>steal(x.id);area.appendChild(b)});if(!choices.length)area.innerHTML+='<div class="small">Ingen Pufflings kan stjeles.</div>';}
  function steal(id){const S=window.SkyPuffSteal,F=window.SkyPuffFusion;if(!S||!F)return;const mine=F.load(),res=S.stealLocal(mine,currentRival,id);if(!res.ok)return;F.save(res.winnerState);const p=[...Object.values(F.BASE),...Object.values(F.FUSIONS)].find(q=>q.id===id);window.SkyPuffFusionUI?.renderDex?.();finish(`Du stjal ${p?.icon||'☁️'} ${p?.name||id}! 😈`);}
  window.SkyPuffStealUI={show};ensureUI();
})();
