(function(){
const FALLBACK_BUILD='5.27-beta.107';let BUILD=FALLBACK_BUILD;try{const src=document.currentScript&&document.currentScript.src;if(src){const v=new URL(src,location.href).searchParams.get('v');if(v)BUILD=v;}}catch(e){}
try{document.title='Orbuff';const set=(sel,text)=>{const el=document.querySelector(sel);if(el)el.textContent=text;};set('#studioSplash .studioGame','ORBUFF');set('#start h1','Orbuff');set('#pufflingsHubBtn','ORBUFFS ☁️');set('#start .menuVersion','ORBUFF • 5.27 BETA 107 • ZYCON STUDIOS');set('#pauseText','Orbuff tar en liten pust i bakken ☁️');set('#shop h1','Orbuff Cosmetics');set('#gameOver h1','Orbuff down! 💨');const mp=document.querySelector('#multiplayerMenu .card .small');if(mp&&/90\s*sekunder/i.test(mp.textContent||''))mp.textContent='Race mot en venn eller en tilfeldig spiller. Førstemann til 1500 m vinner.';const timer=document.getElementById('mpTimer');if(timer&&timer.textContent.trim()==='90')timer.textContent='1500 m';}catch(e){}
const parts=['js/platform_compat.js','js/beta_config.js','js/dom_refs.js','js/localization_core.js','js/language_default.js','js/audio_core.js','js/endless_boss_core.js','js/boss_multiplayer.js','js/music_bridge.js','js/leaderboard_submit.js','js/leaderboard_language_ui.js','js/desktop_game_width.js','js/race_course_seed.js','js/state_content.js','js/save_integrity.js','js/world_helpers.js','js/run_menu_shop_upgrades.js','js/anti_cheat.js','js/input_missions_boss_spawn.js','js/gameplay_update.js','js/late_game_bosses.js','js/late_boss_persistence_fix.js','js/boss_rush_all_defeated.js','js/boss_pattern_override.js','js/late_game_boss_patterns.js','js/boss_movement_fix.js','js/boss_transition_fix.js','js/post_boss_guard.js','js/boss_boost_tuning.js','js/combo_ui_remove.js','js/mission_ui_remove.js','js/rainbow_puff_hint.js','js/start_guard.js','js/achievements.js','js/achievements_menu.js','js/endless_events.js','js/player_render_helpers.js','js/renderer_runtime.js','js/boss_puff_creator_v2.js','js/boss_puff_premium.js','js/boss_puff_main_unlock.js','js/reward_economy_hardening.js','js/boss_visual_override.js','js/late_boss_visuals.js','js/ai_diagnostics.js','js/beta_release_ui.js','js/diagnostics_support.js','js/puff_fusion_core.js','js/puffling_collection_50.js','js/puffling_collection_36.js','js/puffling_unique_traits.js','js/steal_my_puff_core.js','js/puffling_visual_upgrade.js','js/puffling_performance_mode.js','js/performance_settings_ui.js','js/puff_fusion_ui.js','js/main_menu_cleanup.js','js/orbvault_progression.js','js/puffling_nursery_vault.js','js/diamond_wallet_client.js','js/diamond_mystery_shop.js','js/diamond_iap_store.js','js/menu_beta_cleanup.js','js/puffling_gameplay.js','js/puffling_trait_runtime.js','js/puffling_starter_choice.js','js/puffling_progression.js','js/puffling_trade.js','js/puffling_trade_inventory_sync.js','js/puffling_evolution.js','js/orbuff_energy.js','js/orbvault_status_ui.js','js/puffling_evolution_ui_guard.js','js/puffling_evolution_perks.js','js/boss_session_client.js','js/puffling_boss_rewards.js','js/diamond_boss_rewards.js','js/puffling_follower.js','js/puffling_abilities_v2.js','js/puffling_fusion_abilities.js','js/puffling_fusion_signature.js','js/race_multiplayer_transport.js','js/steal_my_puff_ui.js','js/race_ranked.js','js/steal_my_puff_multiplayer_bridge.js','js/race_course_sync.js','js/race_progress_sync.js','js/race_ghost_interpolation.js','js/steal_my_puffling_menu.js','js/race_friend_lobby_guard.js','js/race_puffling_eligibility.js','js/orbuff_game_guide.js','js/puffling_rebrand.js','js/smoke_check.js'];
const start=document.getElementById('start');if(start){start.inert=true;start.setAttribute?.('aria-busy','true');}window.__skyPuffModulesReady=false;let norwegian=false;try{norwegian=localStorage.getItem('skyPuffLang')==='no';}catch(e){}let i=0,notice=null;
function loadingNotice(failed){if(!notice){notice=document.createElement('div');notice.id='skyPuffLoadNotice';notice.style.cssText='position:fixed;inset:0;z-index:2147483647;display:flex;align-items:center;justify-content:center;background:#58c4ff;padding:24px;text-align:center;font:700 18px system-ui;color:#173650';notice.innerHTML='<div><p role="status" aria-live="polite"></p><button type="button" style="display:none;padding:14px 24px;border:0;border-radius:16px;background:#fff;color:#173650;font:inherit"></button></div>';notice.querySelector('button').textContent=norwegian?'Prøv igjen':'Try again';notice.querySelector('button').onclick=()=>location.reload();document.body.appendChild(notice);}notice.querySelector('p').textContent=failed?(norwegian?'Orbuff kunne ikke lastes. Sjekk forbindelsen og prøv igjen.':'Could not load Orbuff. Check your connection and try again.'):(norwegian?'Laster Orbuff …':'Loading Orbuff …');notice.querySelector('button').style.display=failed?'inline-block':'none';}
function finishLoading(){if(start){start.inert=false;start.removeAttribute?.('aria-busy');}if(notice)notice.remove();window.__skyPuffModulesReady=true;window.dispatchEvent?.(new Event('sky-puff-ready'));}
/* Yield between modules so mobile browsers can paint and run the startup watchdog. */
let finished=false;
function release(){
  if(finished)return;
  finished=true;
  finishLoading();
}
function progress(path,state){try{window.dispatchEvent(new CustomEvent('orbuff-load-progress',{detail:{loaded:i,total:parts.length,path,state}}));}catch(e){}}
function loadNext(){
  if(i>=parts.length){progress('', 'complete');release();return;}
  const path=parts[i++];progress(path,'loading');
  const script=document.createElement('script');
  script.src=path+'?v='+encodeURIComponent(BUILD);
  script.onload=()=>{progress(path,'loaded');setTimeout(loadNext,0);};
  script.onerror=()=>{console.error('Orbuff module failed to load',path);progress(path,'failed');setTimeout(loadNext,0);};
  document.body.appendChild(script);
}
setTimeout(loadNext,0);
})();