const assert=require('assert');
const createAccountAuth=require('./account_auth');
const secret='0123456789abcdef0123456789abcdef';
const auth=createAccountAuth({secret,ttlSeconds:3600});
assert.strictEqual(auth.enabled(),true);
const token=auth.issue('player_123');
const verified=auth.verify(token);
assert.strictEqual(verified.ok,true);
assert.strictEqual(verified.accountId,'player_123');
assert.strictEqual(verified.claims.aud,'puffling-game');
assert.strictEqual(auth.verify(token+'x').ok,false);
assert.strictEqual(createAccountAuth({secret:''}).enabled(),false);
assert.strictEqual(createAccountAuth({secret,audience:'other-game'}).verify(token).ok,false,'wrong audience rejected');
const protectedToken=auth.issue('player_123',{sub:'attacker',iss:'evil',aud:'evil',exp:1});
const protectedClaims=auth.verify(protectedToken);
assert.strictEqual(protectedClaims.ok,true,'caller cannot override protected claims');
assert.strictEqual(protectedClaims.accountId,'player_123');
assert.strictEqual(protectedClaims.claims.iss,'puffling-race');
assert.strictEqual(protectedClaims.claims.aud,'puffling-game');
console.log('account_auth_check: ok');
