const crypto=require('crypto');
function clean(v,max=96){const s=String(v||'').trim();return /^[A-Za-z0-9:_+.-]+$/.test(s)&&s.length<=max?s:'';}
const BOSS_REWARDS=Object.freeze(['NONE','ember','volt','frost','wind','prism','nova','supernova','phoenix']);
const BOSS_REWARD_SET=new Set(BOSS_REWARDS);
function validReward(source,pufflingId){const s=clean(source,32),p=clean(pufflingId,64);if(!s||!p)return false;return s==='boss'&&BOSS_REWARD_SET.has(p);}
module.exports=function createAcquisitionStore(opts={}){
 const pool=opts.pool||global.PufflingTradeInventoryStore?.pool||null;let ready=false;
 async function init(db=pool){if(!db)return false;await db.query(`CREATE TABLE IF NOT EXISTS puffling_acquisition_grants(grant_id varchar(96) PRIMARY KEY,account_id varchar(96) NOT NULL,puffling_id varchar(64) NOT NULL,source varchar(32) NOT NULL,source_ref varchar(96) NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(account_id,source,source_ref))`);await db.query('CREATE UNIQUE INDEX IF NOT EXISTS puffling_acquisition_source_once ON puffling_acquisition_grants(account_id,source,source_ref)');ready=true;return true;}
 function bossGrantId(accountId,sessionId){const a=clean(accountId),r=clean(sessionId);if(!a||!r)throw new Error('invalid_grant');return 'BOSS_'+crypto.createHash('sha256').update(`${a}:${r}`).digest('hex').slice(0,40);}
 async function getGrant(grantId){const id=clean(grantId);if(!id||!ready||!pool)return null;const q=await pool.query('SELECT grant_id,puffling_id,source,source_ref FROM puffling_acquisition_grants WHERE grant_id=$1',[id]);if(!q.rows.length)return null;const r=q.rows[0];return{grantId:r.grant_id,pufflingId:r.puffling_id==='NONE'?null:r.puffling_id,source:r.source,sourceRef:r.source_ref};}
 async function grant(db,input){if(input===undefined){input=db;db=pool;}db=db||pool;if(!ready||!db)throw new Error('acquisition_unavailable');const grantId=clean(input?.grantId),accountId=clean(input?.accountId),pufflingId=clean(input?.pufflingId,64),source=clean(input?.source,32),sourceRef=clean(input?.sourceRef);if(!grantId||!accountId||!pufflingId||!source||!sourceRef||!validReward(source,pufflingId))throw new Error('invalid_grant');const c=await db.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`grant:${grantId}`]);const old=await c.query('SELECT * FROM puffling_acquisition_grants WHERE grant_id=$1 OR (account_id=$2 AND source=$3 AND source_ref=$4) FOR UPDATE',[grantId,accountId,source,sourceRef]);if(old.rows.length){const r=old.rows[0];if(r.account_id!==accountId||r.source!==source||r.source_ref!==sourceRef||r.puffling_id!==pufflingId)throw new Error('grant_conflict');await c.query('COMMIT');return{applied:false,duplicate:true,grantId:r.grant_id,pufflingId:r.puffling_id==='NONE'?null:r.puffling_id};}if(pufflingId!=='NONE')await c.query('INSERT INTO puffling_inventory(account_id,puffling_id,quantity,protected_quantity) VALUES($1,$2,1,0) ON CONFLICT(account_id,puffling_id) DO UPDATE SET quantity=puffling_inventory.quantity+1,updated_at=now()',[accountId,pufflingId]);await c.query('INSERT INTO puffling_acquisition_grants(grant_id,account_id,puffling_id,source,source_ref) VALUES($1,$2,$3,$4,$5)',[grantId,accountId,pufflingId,source,sourceRef]);await c.query('COMMIT');return{applied:true,duplicate:false,grantId,pufflingId:pufflingId==='NONE'?null:pufflingId};}catch(e){try{await c.query('ROLLBACK');}catch{}throw e;}finally{c.release();}}
 async function settleBossSession(input){if(!ready||!pool)throw new Error('acquisition_unavailable');const accountId=clean(input?.accountId),sessionId=clean(input?.sessionId),pufflingId=clean(input?.pufflingId,64);if(!accountId||!sessionId||!pufflingId||!validReward('boss',pufflingId))throw new Error('invalid_grant');const grantId=bossGrantId(accountId,sessionId),c=await pool.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`boss-settle:${sessionId}`]);const session=await c.query('SELECT session_id,account_id,boss_ref,expires_at,completed_at,consumed_at,boss_hp FROM puffling_boss_sessions WHERE session_id=$1 FOR UPDATE',[sessionId]);if(!session.rows.length||session.rows[0].account_id!==accountId)throw new Error('boss_proof_required');const proof=session.rows[0];const old=await c.query("SELECT * FROM puffling_acquisition_grants WHERE grant_id=$1 OR (account_id=$2 AND source='boss' AND source_ref=$3) FOR UPDATE",[grantId,accountId,sessionId]);if(old.rows.length){const r=old.rows[0];if(r.account_id!==accountId||r.source!=='boss'||r.source_ref!==sessionId||r.puffling_id!==pufflingId)throw new Error('grant_conflict');if(!proof.consumed_at)await c.query('UPDATE puffling_boss_sessions SET consumed_at=now() WHERE session_id=$1 AND consumed_at IS NULL',[sessionId]);await c.query('COMMIT');return{applied:false,duplicate:true,grantId:r.grant_id,pufflingId:r.puffling_id==='NONE'?null:r.puffling_id,bossRef:proof.boss_ref};}if(!proof.completed_at||proof.consumed_at||Number(proof.boss_hp)>0||new Date(proof.expires_at).getTime()<=Date.now())throw new Error('boss_proof_required');if(pufflingId!=='NONE')await c.query('INSERT INTO puffling_inventory(account_id,puffling_id,quantity,protected_quantity) VALUES($1,$2,1,0) ON CONFLICT(account_id,puffling_id) DO UPDATE SET quantity=puffling_inventory.quantity+1,updated_at=now()',[accountId,pufflingId]);await c.query('INSERT INTO puffling_acquisition_grants(grant_id,account_id,puffling_id,source,source_ref) VALUES($1,$2,$3,$4,$5)',[grantId,accountId,pufflingId,'boss',sessionId]);const consumed=await c.query('UPDATE puffling_boss_sessions SET consumed_at=now() WHERE session_id=$1 AND consumed_at IS NULL RETURNING consumed_at',[sessionId]);if(consumed.rowCount!==1)throw new Error('boss_proof_required');await c.query('COMMIT');return{applied:true,duplicate:false,grantId,pufflingId:pufflingId==='NONE'?null:pufflingId,bossRef:proof.boss_ref};}catch(e){try{await c.query('ROLLBACK');}catch{}throw e;}finally{c.release();}}
 return{init,grant,settleBossSession,getGrant,bossGrantId,validReward,bossRewards:()=>[...BOSS_REWARDS],status:()=>({ready,version:5,rewardAllowlist:true,sourceIdempotency:true})};
};
module.exports.BOSS_REWARDS=BOSS_REWARDS;
module.exports.validReward=validReward;