const crypto=require('crypto');
module.exports=function createAcquisitionHttp(auth,store,bossSessions){
 function json(res,status,body){res.writeHead(status,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(body));}
 function bearer(req){const h=String(req.headers?.authorization||'');return h.startsWith('Bearer ')?h.slice(7):'';}
 async function body(req){let raw='',size=0;for await(const c of req){size+=c.length;if(size>32768)throw new Error('body_too_large');raw+=c.toString();}return raw?JSON.parse(raw):{};}
 const BASE_DROP=Object.freeze({storm:2500,candy:3000,ice:3500,galaxy:4000,solar:4500,void:5000,thunder:5500,crystal:6000,inferno:6500,cosmic:7500});
 function parseRef(ref){const m=/^([a-z]+):([1-9][0-9]{0,2})$/i.exec(String(ref||''));return m?{id:m[1].toLowerCase(),tier:Number(m[2])}:null;}
 function dropChanceFor(bossRef){const b=parseRef(bossRef);if(!b||BASE_DROP[b.id]==null)return 0;const tierBonus=b.tier>1?(b.tier-1)*300:0;return Math.min(8500,BASE_DROP[b.id]+tierBonus);}
 function hashMod(label,sessionId,mod){return crypto.createHash('sha256').update(`${label}:${sessionId}`).digest().readUInt32BE(0)%mod;}
 function rewardFor(sessionId,bossRef){const chance=dropChanceFor(bossRef);if(!chance||hashMod('boss-drop',sessionId,10000)>=chance)return'NONE';const n=hashMod('boss-reward',sessionId,350);if(n<15)return'phoenix';if(n<55)return'supernova';if(n<120)return'nova';if(n<210)return'prism';return['ember','volt','frost','wind'][n%4];}
 return async function handle(req,res){const path=String(req.url||'').split('?')[0];if(path!=='/api/acquisition/boss'||req.method!=='POST')return false;const verified=auth.verify(bearer(req));if(!verified.ok)return json(res,401,{ok:false,error:'auth_required'}),true;if(!store.status().ready||!bossSessions?.statusInfo().ready)return json(res,503,{ok:false,error:'acquisition_unavailable'}),true;try{const data=await body(req),sessionId=String(data?.sessionId||''),proof=await bossSessions.status(verified.accountId,sessionId);if(!proof?.bossRef)throw new Error('boss_proof_required');const chanceBasisPoints=dropChanceFor(proof.bossRef),pufflingId=rewardFor(sessionId,proof.bossRef);const grant=await store.settleBossSession({accountId:verified.accountId,sessionId,pufflingId});return json(res,200,{ok:true,serverAuthoritative:true,noDrop:!grant.pufflingId,pufflingId:grant.pufflingId,grantId:grant.grantId,bossRef:grant.bossRef,duplicate:grant.duplicate,dropChance:chanceBasisPoints/10000});}catch(e){const code=String(e?.message||e);if(code==='boss_proof_required')return json(res,403,{ok:false,error:'boss_proof_required',serverAuthoritative:false}),true;if(code==='grant_conflict')return json(res,409,{ok:false,error:'grant_conflict'}),true;json(res,code==='body_too_large'?413:400,{ok:false,error:'invalid_request'});return true;}};
};
module.exports._test={dropChanceFor:(ref)=>{const m=/^([a-z]+):([1-9][0-9]{0,2})$/i.exec(String(ref||''));if(!m)return 0;const id=m[1].toLowerCase(),tier=Number(m[2]),base={storm:2500,candy:3000,ice:3500,galaxy:4000,solar:4500,void:5000,thunder:5500,crystal:6000,inferno:6500,cosmic:7500}[id];return base==null?0:Math.min(8500,base+(tier>1?(tier-1)*300:0));}};