const crypto=require('crypto');
function clean(v,max=96){const s=String(v||'').trim();return /^[A-Za-z0-9:_+.-]+$/.test(s)&&s.length<=max?s:'';}
module.exports=function createAcquisitionStore(opts={}){
 const pool=opts.pool||global.PufflingTradeInventoryStore?.pool||null;let ready=false;
 async function init(db=pool){if(!db)return false;await db.query(`CREATE TABLE IF NOT EXISTS puffling_acquisition_grants(grant_id varchar(96) PRIMARY KEY,account_id varchar(96) NOT NULL,puffling_id varchar(64) NOT NULL,source varchar(32) NOT NULL,source_ref varchar(96) NOT NULL,created_at timestamptz NOT NULL DEFAULT now())`);ready=true;return true;}
 function bossGrantId(accountId,bossRef){const a=clean(accountId),r=clean(bossRef);if(!a||!r)throw new Error('invalid_grant');return 'BOSS_'+crypto.createHash('sha256').update(`${a}:${r}`).digest('hex').slice(0,40);}
 async function grant(db,input={}){if(!ready||!db)throw new Error('acquisition_unavailable');const grantId=clean(input.grantId),accountId=clean(input.accountId),pufflingId=clean(input.pufflingId,64),source=clean(input.source,32),sourceRef=clean(input.sourceRef);if(!grantId||!accountId||!pufflingId||!source||!sourceRef)throw new Error('invalid_grant');const c=await db.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`grant:${grantId}`]);const old=await c.query('SELECT * FROM puffling_acquisition_grants WHERE grant_id=$1',[grantId]);if(old.rows.length){await c.query('COMMIT');return{applied:false,duplicate:true,grantId,pufflingId:old.rows[0].puffling_id};}await c.query('INSERT INTO puffling_inventory(account_id,puffling_id,quantity,protected_quantity) VALUES($1,$2,1,0) ON CONFLICT(account_id,puffling_id) DO UPDATE SET quantity=puffling_inventory.quantity+1,updated_at=now()',[accountId,pufflingId]);await c.query('INSERT INTO puffling_acquisition_grants(grant_id,account_id,puffling_id,source,source_ref) VALUES($1,$2,$3,$4,$5)',[grantId,accountId,pufflingId,source,sourceRef]);await c.query('COMMIT');return{applied:true,duplicate:false,grantId,pufflingId};}catch(e){try{await c.query('ROLLBACK');}catch{}throw e;}finally{c.release();}}
 return{init,grant,bossGrantId,status:()=>({ready,version:1})};
};
