const http=require('http');
const createIapStore=require('./iap_store');const createIapHttp=require('./iap_http');const createLeaderboardStore=require('./leaderboard_store');const createLeaderboardHttp=require('./leaderboard_http');const createRankedStore=require('./ranked_store');const createRankedHttp=require('./ranked_http');const createAccountAuth=require('./account_auth');const createAccountHttp=require('./account_http');const createTradeInventoryStore=require('./trade_inventory_store');const createTradeInventoryHttp=require('./trade_inventory_http');const createAcquisitionStore=require('./acquisition_store');const createAcquisitionHttp=require('./acquisition_http');const createBossSessionStore=require('./boss_session_store');const createBossSessionHttp=require('./boss_session_http');
(async()=>{
 const iapStore=createIapStore(),leaderboardStore=createLeaderboardStore(),rankedStore=createRankedStore(),tradeInventoryStore=createTradeInventoryStore(),accountAuth=createAccountAuth();
 try{await iapStore.init();console.log('[IAP] Diamond wallet database ready');}catch(e){console.warn('[IAP] Diamond wallet database unavailable:',String(e?.message||e));}
 try{await leaderboardStore.init();console.log('[Leaderboard] Global score database ready');}catch(e){console.warn('[Leaderboard] Score database unavailable:',String(e?.message||e));}
 try{await rankedStore.init();console.log('[Ranked] Persistent rank database ready');}catch(e){console.warn('[Ranked] Rank database unavailable:',String(e?.message||e));}
 try{await tradeInventoryStore.init();console.log('[Trade] Authoritative inventory database ready');}catch(e){console.warn('[Trade] Inventory database unavailable:',String(e?.message||e));}
 const acquisitionStore=createAcquisitionStore({pool:tradeInventoryStore.pool});try{await acquisitionStore.init();console.log('[Acquisition] Server reward grants ready');}catch(e){console.warn('[Acquisition] Reward grants unavailable:',String(e?.message||e));}
 const bossSessionStore=createBossSessionStore({pool:tradeInventoryStore.pool});try{await bossSessionStore.init();console.log('[Boss] Authoritative session database ready');}catch(e){console.warn('[Boss] Session database unavailable:',String(e?.message||e));}
 global.PufflingRankedStore=rankedStore;global.PufflingTradeInventoryStore=tradeInventoryStore;global.PufflingAccountAuth=accountAuth;global.PufflingAcquisitionStore=acquisitionStore;global.PufflingBossSessionStore=bossSessionStore;
 const handleAccount=createAccountHttp(accountAuth,rankedStore),handleTradeInventory=createTradeInventoryHttp(accountAuth,tradeInventoryStore),handleAcquisition=createAcquisitionHttp(accountAuth,acquisitionStore),handleBossSession=createBossSessionHttp(accountAuth,bossSessionStore),handleIap=createIapHttp(iapStore),handleLeaderboard=createLeaderboardHttp(leaderboardStore),handleRanked=createRankedHttp(rankedStore);
 const originalCreateServer=http.createServer;http.createServer=function(listener){return originalCreateServer.call(http,async(req,res)=>{
  const handlers=[[handleAccount,'Account'],[handleTradeInventory,'Trade'],[handleBossSession,'Boss'],[handleAcquisition,'Acquisition'],[handleRanked,'Ranked'],[handleLeaderboard,'Leaderboard'],[handleIap,'IAP']];for(const [h,n] of handlers){try{if(await h(req,res))return;}catch(e){console.error(`[${n}] HTTP handler failure`,e);if(!res.headersSent){res.writeHead(500,{'content-type':'application/json'});res.end(JSON.stringify({ok:false,error:'server_error'}));}return;}}return listener(req,res);
 });};
 const closeStores=()=>Promise.allSettled([iapStore.close(),leaderboardStore.close(),rankedStore.close(),tradeInventoryStore.close()]);process.on('SIGTERM',()=>closeStores());process.on('SIGINT',()=>closeStores());require('./index');
})();