const crypto=require('crypto');
function clean(v,max=96){const s=String(v||'').trim();return /^[A-Za-z0-9:_+.-]+$/.test(s)&&s.length<=max?s:'';}
module.exports=function createBossSessionStore(opts={}){
 const pool=opts.pool||null;let ready=false;const ttlMs=Math.max(30000,Math.min(15*60*1000,Number(opts.ttlMs||5*60*1000))),minFightMs=Math.max(10000,Number(opts.minFightMs||20000)),minHitMs=Math.max(120,Number(opts.minHitMs||180));
 const baseHp={storm:120,candy:175,ice:240,galaxy:340};
 function parseBossRef(v){const m=/^(storm|candy|ice|galaxy):([1-9][0-9]{0,2})$/i.exec(clean(v));return m?{id:m[1].toLowerCase(),tier:Number(m[2])}:null;}
 function maxHp(ref){const b=parseBossRef(ref);if(!b)return 0;if(b.tier===1)return baseHp[b.id];return Math.max(baseHp[b.id],Math.round(5*Math.pow(1.22,b.tier-1))*24);}
 async function init(){if(!pool)return false;await pool.query(`CREATE TABLE IF NOT EXISTS puffling_boss_sessions(session_id varchar(64) PRIMARY KEY,account_id varchar(96) NOT NULL,boss_ref varchar(96) NOT NULL,nonce varchar(64) NOT NULL,started_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz NOT NULL,completed_at timestamptz,consumed_at timestamptz,boss_hp integer NOT NULL DEFAULT 0,hit_count integer NOT NULL DEFAULT 0,last_hit_at timestamptz)`);await pool.query('ALTER TABLE puffling_boss_sessions ADD COLUMN IF NOT EXISTS boss_hp integer NOT NULL DEFAULT 0');await pool.query('ALTER TABLE puffling_boss_sessions ADD COLUMN IF NOT EXISTS hit_count integer NOT NULL DEFAULT 0');await pool.query('ALTER TABLE puffling_boss_sessions ADD COLUMN IF NOT EXISTS last_hit_at timestamptz');ready=true;return true;}
 function validBossRef(v){return !!parseBossRef(v);}
 async function issue(accountId,bossRef){const a=clean(accountId),b=clean(bossRef);if(!ready||!pool)throw new Error('boss_session_unavailable');if(!a||!validBossRef(b))throw new Error('invalid_boss_session');const sessionId='BS_'+crypto.randomBytes(24).toString('base64url'),nonce=crypto.randomBytes(18).toString('base64url'),expires=new Date(Date.now()+ttlMs),hp=maxHp(b);await pool.query('INSERT INTO puffling_boss_sessions(session_id,account_id,boss_ref,nonce,expires_at,boss_hp) VALUES($1,$2,$3,$4,$5,$6)',[sessionId,a,b,nonce,expires,hp]);return{sessionId,bossRef:b,nonce,expiresAt:expires.toISOString(),bossHp:hp,maxHp:hp};}
 async function status(accountId,sessionId){const a=clean(accountId),s=clean(sessionId,64);if(!a||!s||!ready||!pool)return null;const q=await pool.query('SELECT session_id,boss_ref,started_at,expires_at,completed_at,consumed_at,boss_hp,hit_count FROM puffling_boss_sessions WHERE session_id=$1 AND account_id=$2',[s,a]);if(!q.rows.length)return null;const r=q.rows[0];return{sessionId:r.session_id,bossRef:r.boss_ref,startedAt:r.started_at,expiresAt:r.expires_at,completedAt:r.completed_at,consumedAt:r.consumed_at,bossHp:r.boss_hp,maxHp:maxHp(r.boss_ref),hitCount:r.hit_count,expired:new Date(r.expires_at).getTime()<Date.now()};}
 async function recordHit(accountId,sessionId,nonce){const a=clean(accountId),s=clean(sessionId,64),n=clean(nonce,64);if(!a||!s||!n||!ready||!pool)return null;const c=await pool.connect();try{await c.query('BEGIN');const q=await c.query('SELECT * FROM puffling_boss_sessions WHERE session_id=$1 AND account_id=$2 AND nonce=$3 FOR UPDATE',[s,a,n]);const r=q.rows[0];if(!r||r.completed_at||r.consumed_at||new Date(r.expires_at).getTime()<Date.now()){await c.query('ROLLBACK');return null;}if(r.last_hit_at&&Date.now()-new Date(r.last_hit_at).getTime()<minHitMs){await c.query('ROLLBACK');return{accepted:false,reason:'hit_rate_limited',bossHp:r.boss_hp,completed:false};}const damage=Math.min(24,Math.max(12,Math.ceil(maxHp(r.boss_ref)/10))),hp=Math.max(0,r.boss_hp-damage),elapsed=Date.now()-new Date(r.started_at).getTime(),complete=hp<=0&&elapsed>=minFightMs;const u=await c.query('UPDATE puffling_boss_sessions SET boss_hp=$2,hit_count=hit_count+1,last_hit_at=now(),completed_at=CASE WHEN $3 THEN COALESCE(completed_at,now()) ELSE completed_at END WHERE session_id=$1 RETURNING hit_count,completed_at',[s,hp,complete]);await c.query('COMMIT');return{accepted:true,bossHp:hp,maxHp:maxHp(r.boss_ref),hitCount:u.rows[0].hit_count,completed:!!u.rows[0].completed_at};}catch(e){try{await c.query('ROLLBACK');}catch{}throw e;}finally{c.release();}}
 async function consumeCompleted(accountId,sessionId){const a=clean(accountId),s=clean(sessionId,64);if(!a||!s||!ready||!pool)return null;const c=await pool.connect();try{await c.query('BEGIN');const q=await c.query('SELECT * FROM puffling_boss_sessions WHERE session_id=$1 AND account_id=$2 FOR UPDATE',[s,a]);const r=q.rows[0];if(!r||!r.completed_at||r.consumed_at||r.boss_hp>0||new Date(r.expires_at).getTime()<Date.now()){await c.query('ROLLBACK');return null;}await c.query('UPDATE puffling_boss_sessions SET consumed_at=now() WHERE session_id=$1',[s]);await c.query('COMMIT');return{sessionId:s,bossRef:r.boss_ref,completedAt:r.completed_at};}catch(e){try{await c.query('ROLLBACK');}catch{}throw e;}finally{c.release();}}
 return{init,issue,status,recordHit,consumeCompleted,validBossRef,parseBossRef,maxHp,statusInfo:()=>({ready,ttlMs,minFightMs,minHitMs,version:4})};
};