const crypto=require('crypto');
function clean(v,max=96){const s=String(v||'').trim();return /^[A-Za-z0-9:_+.-]+$/.test(s)&&s.length<=max?s:'';}
module.exports=function createBossSessionStore(opts={}){
 const pool=opts.pool||null;let ready=false;const ttlMs=Math.max(30000,Math.min(15*60*1000,Number(opts.ttlMs||5*60*1000)));
 async function init(){if(!pool)return false;await pool.query(`CREATE TABLE IF NOT EXISTS puffling_boss_sessions(session_id varchar(64) PRIMARY KEY,account_id varchar(96) NOT NULL,boss_ref varchar(96) NOT NULL,nonce varchar(64) NOT NULL,started_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz NOT NULL,completed_at timestamptz,consumed_at timestamptz)`);ready=true;return true;}
 async function issue(accountId,bossRef){const a=clean(accountId),b=clean(bossRef);if(!ready||!pool)throw new Error('boss_session_unavailable');if(!a||!b)throw new Error('invalid_boss_session');const sessionId='BS_'+crypto.randomBytes(24).toString('base64url'),nonce=crypto.randomBytes(18).toString('base64url'),expires=new Date(Date.now()+ttlMs);await pool.query('INSERT INTO puffling_boss_sessions(session_id,account_id,boss_ref,nonce,expires_at) VALUES($1,$2,$3,$4,$5)',[sessionId,a,b,nonce,expires]);return{sessionId,bossRef:b,nonce,expiresAt:expires.toISOString()};}
 async function status(accountId,sessionId){const a=clean(accountId),s=clean(sessionId,64);if(!a||!s||!ready||!pool)return null;const q=await pool.query('SELECT session_id,boss_ref,started_at,expires_at,completed_at,consumed_at FROM puffling_boss_sessions WHERE session_id=$1 AND account_id=$2',[s,a]);if(!q.rows.length)return null;const r=q.rows[0];return{sessionId:r.session_id,bossRef:r.boss_ref,startedAt:r.started_at,expiresAt:r.expires_at,completedAt:r.completed_at,consumedAt:r.consumed_at,expired:new Date(r.expires_at).getTime()<Date.now()};}
 async function markCompletedTrusted(accountId,sessionId){const a=clean(accountId),s=clean(sessionId,64);if(!a||!s||!ready||!pool)return null;const q=await pool.query('UPDATE puffling_boss_sessions SET completed_at=COALESCE(completed_at,now()) WHERE session_id=$1 AND account_id=$2 AND consumed_at IS NULL AND expires_at>now() RETURNING session_id,boss_ref,completed_at',[s,a]);return q.rows[0]||null;}
 async function consumeCompleted(accountId,sessionId){const a=clean(accountId),s=clean(sessionId,64);if(!a||!s||!ready||!pool)return null;const c=await pool.connect();try{await c.query('BEGIN');const q=await c.query('SELECT * FROM puffling_boss_sessions WHERE session_id=$1 AND account_id=$2 FOR UPDATE',[s,a]);const r=q.rows[0];if(!r||!r.completed_at||r.consumed_at||new Date(r.expires_at).getTime()<Date.now()){await c.query('ROLLBACK');return null;}await c.query('UPDATE puffling_boss_sessions SET consumed_at=now() WHERE session_id=$1',[s]);await c.query('COMMIT');return{sessionId:s,bossRef:r.boss_ref,completedAt:r.completed_at};}catch(e){try{await c.query('ROLLBACK');}catch{}throw e;}finally{c.release();}}
 return{init,issue,status,markCompletedTrusted,consumeCompleted,statusInfo:()=>({ready,ttlMs,version:2})};
};