const {spawn}=require('child_process');
const {WebSocket}=require('ws');
const createAccountAuth=require('./account_auth');
const PORT=12000+Math.floor(Math.random()*1000),URL=`ws://127.0.0.1:${PORT}`,ROOM='quickmatch';
const SECRET='integration-test-secret-0123456789abcdef';
const auth=createAccountAuth({secret:SECRET});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const fail=msg=>{throw new Error(msg)};
function peer(playerId){const ws=new WebSocket(URL),queue=[],waiters=[];ws.on('message',raw=>{let m;try{m=JSON.parse(raw.toString())}catch{return;}const idx=waiters.findIndex(w=>w.type===m.type);if(idx>=0){const w=waiters.splice(idx,1)[0];clearTimeout(w.timer);w.resolve(m);}else queue.push(m);});return{ws,playerId,open:()=>new Promise((resolve,reject)=>{ws.once('open',resolve);ws.once('error',reject)}),send:m=>ws.send(JSON.stringify(m)),wait(type,timeout=5000){const idx=queue.findIndex(m=>m.type===type);if(idx>=0)return Promise.resolve(queue.splice(idx,1)[0]);return new Promise((resolve,reject)=>{const waiter={type,resolve,timer:setTimeout(()=>{const i=waiters.indexOf(waiter);if(i>=0)waiters.splice(i,1);reject(new Error(`timeout waiting for ${type} (${playerId})`));},timeout)};waiters.push(waiter);});},close:()=>{try{ws.close()}catch{}}};}
async function waitUntil(p,type,pred,timeout=5000){const end=Date.now()+timeout;while(Date.now()<end){const m=await p.wait(type,Math.max(50,end-Date.now()));if(pred(m))return m;}throw new Error(`timeout waiting for matching ${type} (${p.playerId})`);}
async function expectNo(p,type,timeout=220){try{await p.wait(type,timeout);fail(`unexpected ${type} (${p.playerId})`);}catch(e){if(!String(e.message||e).startsWith('timeout waiting'))throw e;}}
async function waitForServer(child){let output='';return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(`server start timeout: ${output}`)),5000);child.stdout.on('data',buf=>{output+=buf.toString();if(output.includes('listening on')){clearTimeout(timer);resolve();}});child.stderr.on('data',buf=>{output+=buf.toString();});child.once('exit',code=>{clearTimeout(timer);reject(new Error(`server exited early (${code}): ${output}`));});});}
(async()=>{const server=spawn(process.execPath,['index.js'],{cwd:__dirname,env:{...process.env,PORT:String(PORT),PUFFLING_AUTH_SECRET:SECRET,PUFFLING_TRADE_TEST_INVENTORY:'1'},stdio:['ignore','pipe','pipe']});const peers=[];try{
 await waitForServer(server);
 const unauth=peer('unauth');peers.push(unauth);await unauth.open();unauth.send({type:'race:hello',room:ROOM,playerId:unauth.playerId,protocol:3,rankRating:9999});if((await unauth.wait('race:error')).code!=='rank_auth_required')fail('Quick Race accepted missing auth');unauth.close();
 const tokenA=auth.issue('acct_a',{kind:'guest'}),tokenB=auth.issue('acct_b',{kind:'guest'});
 const a=peer('launch_a'),b=peer('launch_b');peers.push(a,b);await Promise.all([a.open(),b.open()]);
 a.send({type:'race:hello',room:ROOM,playerId:a.playerId,protocol:3,authToken:tokenA,rankRating:9999});const matchA=await a.wait('race:matched');
 b.send({type:'race:hello',room:ROOM,playerId:b.playerId,protocol:3,authToken:tokenB,rankRating:1});const matchB=await b.wait('race:matched');const joinedA=await a.wait('race:opponentJoined');
 if(matchA.mode!=='quick'||matchB.mode!=='quick')fail('Quick Match did not create quick room');const pa=matchB.players?.find(p=>p.playerId===a.playerId),pb=joinedA.player;if(pa?.rankRating!==1000||pb?.rankRating!==1000)fail('Client MMR spoof was trusted');if(pa?.accountId!=='acct_a'||pb?.accountId!=='acct_b')fail('Verified account identity was not bound to Race players');if(!matchA.courseSeed||matchA.courseSeed!==matchB.courseSeed)fail('Shared course metadata failed');
 const disconnected=a.wait('race:opponentDisconnected');b.close();await disconnected;const br=peer('launch_b');peers.push(br);await br.open();const reconnected=a.wait('race:opponentReconnected');br.send({type:'race:hello',room:matchB.room,playerId:br.playerId,protocol:3,resume:true,authToken:tokenB});const resumed=await br.wait('race:resumed');await reconnected;if(resumed.room!==matchB.room)fail('Authenticated reconnect failed');
 const startA=a.wait('race:start'),startB=br.wait('race:start');a.send({type:'race:ready',pufflingId:'ember'});br.send({type:'race:ready',pufflingId:'volt'});const [sa,sb]=await Promise.all([startA,startB]);if(sa.serverStartAt!==sb.serverStartAt||sa.goal!==1500)fail('Synchronized start failed');await sleep(Math.max(0,sa.serverStartAt-Date.now()+180));const rejected=a.wait('race:positionRejected');a.send({type:'race:position',height:1500,x:120});if(!['height_rate','height_jump'].includes((await rejected).reason))fail('Teleport not rejected');await expectNo(a,'race:result');const relay=br.wait('race:position');a.send({type:'race:position',height:100,x:120});if((await relay).height!==100)fail('Position relay failed');const attackRelay=br.wait('race:attack');a.send({type:'race:attack',ability:{id:'tinyGust'}});if((await attackRelay).remaining!==2)fail('Attack relay failed');const cooldown=a.wait('race:attackRejected');a.send({type:'race:attack',ability:{id:'tinyGust'}});if((await cooldown).reason!=='cooldown')fail('Attack cooldown failed');const resultA=a.wait('race:result',8000),resultB=br.wait('race:result',8000);for(let height=200;height<=1500;height+=100){await sleep(205);a.send({type:'race:position',height,x:120});}const [ra,rb]=await Promise.all([resultA,resultB]);if(ra.winnerId!==a.playerId||rb.winnerId!==a.playerId)fail('Valid finisher not awarded');if(ra.rankServerAuthoritative)fail('Rank unexpectedly authoritative without test database');console.log('✅ Race auth: missing token rejected, MMR spoof ignored, reconnect and integrity passed');a.close();br.close();
 const same1=peer('same_1'),same2=peer('same_2');peers.push(same1,same2);await Promise.all([same1.open(),same2.open()]);same1.send({type:'race:hello',room:ROOM,playerId:same1.playerId,protocol:3,authToken:tokenA});await same1.wait('race:matched');same2.send({type:'race:hello',room:ROOM,playerId:same2.playerId,protocol:3,authToken:tokenA});if((await same2.wait('race:error')).code!=='same_account')fail('Same account matched itself');same1.close();same2.close();
 const noAuth=peer('trade_noauth');peers.push(noAuth);await noAuth.open();noAuth.send({type:'trade:hello',room:'TRD999',playerId:noAuth.playerId,protocol:2});if((await noAuth.wait('trade:error')).code!=='trade_auth_required')fail('Trade accepted missing auth');noAuth.close();
 const c=peer('trade_a'),d=peer('trade_b');peers.push(c,d);await Promise.all([c.open(),d.open()]);c.send({type:'trade:hello',room:'TRD123',playerId:c.playerId,protocol:2,authToken:tokenA});const cm=await c.wait('trade:matched');if(!cm.serverAuthoritativeInventory)fail('Trade did not advertise authoritative inventory');d.send({type:'trade:hello',room:'TRD123',playerId:d.playerId,protocol:2,authToken:tokenB});await d.wait('trade:matched');await c.wait('trade:opponentJoined');c.send({type:'trade:offer',pufflingId:'starterpuff',availableCount:999});if((await c.wait('trade:error')).code!=='starter_locked')fail('Starter trade lock failed');c.send({type:'trade:offer',pufflingId:'ember',availableCount:999});d.send({type:'trade:offer',pufflingId:'volt',availableCount:999});const both=s=>Array.isArray(s.players)&&s.players.length===2&&s.players.every(p=>p.offer?.pufflingId);await Promise.all([waitUntil(c,'trade:state',both),waitUntil(d,'trade:state',both)]);c.send({type:'trade:accept'});d.send({type:'trade:accept'});const [tc,td]=await Promise.all([c.wait('trade:commit'),d.wait('trade:commit')]);if(!tc.serverAuthoritative||tc.txId!==td.txId)fail('Authoritative Trade commit mismatch');if(!tc.transfers?.some(t=>t.from===c.playerId&&t.to===d.playerId&&t.pufflingId==='ember'))fail('Trade transfer mapping failed');
 c.send({type:'trade:offer',pufflingId:'prism',availableCount:999});d.send({type:'trade:offer',pufflingId:'volt',availableCount:999});const forged=s=>Array.isArray(s.players)&&s.players.length===2&&s.players.some(p=>p.playerId===c.playerId&&p.offer?.pufflingId==='prism')&&s.players.some(p=>p.playerId===d.playerId&&p.offer?.pufflingId==='volt');await Promise.all([waitUntil(c,'trade:state',forged),waitUntil(d,'trade:state',forged)]);c.send({type:'trade:accept'});d.send({type:'trade:accept'});const inventoryError=await waitUntil(c,'trade:error',m=>m.code==='inventory_missing');if(inventoryError.code!=='inventory_missing')fail('Forged client inventory was trusted');console.log('✅ Trade auth + authoritative inventory regression passed');
 }finally{peers.forEach(p=>p.close());try{server.kill('SIGTERM')}catch{}}})().catch(err=>{console.error('❌ Multiplayer integration check failed:',err.message||err);process.exitCode=1;});
