const {Pool}=require('pg');
function secureDatabaseUrl(value){const url=String(value||'').trim();if(!url||/localhost|127\.0\.0\.1/.test(url))return url;return url.replace(/([?&])sslmode=require(?=(&|$))/i,'$1sslmode=verify-full');}
function cleanAccountId(v){const s=String(v||'').trim();return /^[A-Za-z0-9:_-]{3,96}$/.test(s)?s:'';}
function cleanPufflingId(v){const s=String(v||'').trim();return /^[A-Za-z0-9_+.-]{1,64}$/.test(s)?s:'';}
function cleanTradeId(v){const s=String(v||'').trim();return /^[A-Za-z0-9:_-]{3,96}$/.test(s)?s:'';}
module.exports=function createTradeInventoryStore(opts={}){
 const databaseUrl=secureDatabaseUrl(opts.databaseUrl??process.env.DATABASE_URL??'');const pool=opts.pool||(databaseUrl?new Pool({connectionString:databaseUrl,max:3}):null);let ready=false;
 async function init(){if(!pool)return false;await pool.query(`CREATE TABLE IF NOT EXISTS puffling_inventory(account_id varchar(96) NOT NULL,puffling_id varchar(64) NOT NULL,quantity integer NOT NULL DEFAULT 0 CHECK(quantity>=0),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(account_id,puffling_id))`);await pool.query(`CREATE TABLE IF NOT EXISTS puffling_trade_results(trade_id varchar(96) PRIMARY KEY,account_a varchar(96) NOT NULL,account_b varchar(96) NOT NULL,puffling_a varchar(64) NOT NULL,puffling_b varchar(64) NOT NULL,created_at timestamptz NOT NULL DEFAULT now())`);ready=true;return true;}
 async function quantity(accountId,pufflingId,client=null){const a=cleanAccountId(accountId),p=cleanPufflingId(pufflingId);if(!a||!p)throw new Error('invalid_inventory_key');if(!ready||!pool)throw new Error('trade_inventory_unavailable');const db=client||pool,q=await db.query('SELECT quantity FROM puffling_inventory WHERE account_id=$1 AND puffling_id=$2',[a,p]);return Number(q.rows[0]?.quantity)||0;}
 async function exchange(input={}){if(!ready||!pool)throw new Error('trade_inventory_unavailable');const tradeId=cleanTradeId(input.tradeId),a=cleanAccountId(input.accountA),b=cleanAccountId(input.accountB),pa=cleanPufflingId(input.pufflingA),pb=cleanPufflingId(input.pufflingB);if(!tradeId||!a||!b||a===b||!pa||!pb)throw new Error('invalid_trade');const client=await pool.connect();try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(hashtext($1))',[tradeId]);const old=await client.query('SELECT * FROM puffling_trade_results WHERE trade_id=$1',[tradeId]);if(old.rows.length){const r=old.rows[0];if(r.account_a!==a||r.account_b!==b||r.puffling_a!==pa||r.puffling_b!==pb)throw new Error('trade_result_conflict');await client.query('COMMIT');return{applied:false,duplicate:true,tradeId};}await client.query('INSERT INTO puffling_inventory(account_id,puffling_id,quantity) VALUES($1,$2,0),($3,$4,0) ON CONFLICT DO NOTHING',[a,pa,b,pb]);const locked=await client.query('SELECT account_id,puffling_id,quantity FROM puffling_inventory WHERE (account_id=$1 AND puffling_id=$2) OR (account_id=$3 AND puffling_id=$4) ORDER BY account_id,puffling_id FOR UPDATE',[a,pa,b,pb]);const own=new Map(locked.rows.map(r=>[`${r.account_id}:${r.puffling_id}`,Number(r.quantity)||0]));if((own.get(`${a}:${pa}`)||0)<1||(own.get(`${b}:${pb}`)||0)<1)throw new Error('inventory_missing');await client.query('UPDATE puffling_inventory SET quantity=quantity-1,updated_at=now() WHERE account_id=$1 AND puffling_id=$2',[a,pa]);await client.query('UPDATE puffling_inventory SET quantity=quantity-1,updated_at=now() WHERE account_id=$1 AND puffling_id=$2',[b,pb]);await client.query('INSERT INTO puffling_inventory(account_id,puffling_id,quantity) VALUES($1,$2,1),($3,$4,1) ON CONFLICT(account_id,puffling_id) DO UPDATE SET quantity=puffling_inventory.quantity+1,updated_at=now()',[a,pb,b,pa]);await client.query('INSERT INTO puffling_trade_results(trade_id,account_a,account_b,puffling_a,puffling_b) VALUES($1,$2,$3,$4,$5)',[tradeId,a,b,pa,pb]);await client.query('COMMIT');return{applied:true,duplicate:false,tradeId,transfers:[{from:a,to:b,pufflingId:pa},{from:b,to:a,pufflingId:pb}]};}catch(e){try{await client.query('ROLLBACK');}catch{}throw e;}finally{client.release();}}
 async function close(){if(!opts.pool)await pool?.end();}return{init,quantity,exchange,status:()=>({ready,database:!!pool}),close,cleanAccountId,cleanPufflingId,version:1};
};
