import fs from 'node:fs';
import vm from 'node:vm';
const root=process.cwd();const fail=msg=>{console.error(`❌ ${msg}`);process.exitCode=1;};const ok=msg=>console.log(`✅ ${msg}`);
function storage(){const m=new Map();return{getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k),clear:()=>m.clear()};}function run(ctx,rel){vm.runInNewContext(fs.readFileSync(`${root}/${rel}`,'utf8'),ctx,{filename:rel});}
const localStorage=storage(),ctx={window:{},localStorage,console,requestAnimationFrame:()=>0,showToast:()=>{}};ctx.window=ctx;run(ctx,'js/puff_fusion_core.js');const F=ctx.SkyPuffFusion;
F.add('ember',1);F.add('ember',2);if(F.load().owned.ember!==3)fail('Duplicate Pufflings do not stack and persist as xN');else ok('Duplicate Pufflings persist as owned counts');
const first=F.tradeTransfer('ember','prism','trade_test_1');if(!first.ok||first.duplicate||F.load().owned.ember!==2||F.load().owned.prism!==1)fail('Local authoritative-commit mirror did not move exactly one copy');else ok('Local collection can mirror one authoritative Trade commit');
const replay=F.tradeTransfer('ember','prism','trade_test_1');if(!replay.ok||!replay.duplicate||F.load().owned.ember!==2||F.load().owned.prism!==1)fail('Trade receipt did not block duplicate local application');else ok('Authoritative Trade commits remain idempotent locally');
F.add('shadow',1);const s=F.load();s.vault=['shadow'];F.save(s);const blocked=F.tradeTransfer('shadow','frost','trade_test_vault');if(blocked.ok||blocked.reason!=='protected_or_missing')fail('Vault-protected local copy could be transferred');else ok('Vault protection remains enforced by collection layer');const starter=F.tradeTransfer('starterpuff','frost','trade_test_starter');if(starter.ok||starter.reason!=='starter_locked')fail('Starter trade was not blocked');else ok('Starter Pufflings remain trade-locked');
const client=fs.readFileSync(`${root}/js/puffling_trade.js`,'utf8');for(const token of ['ensureIdentity','pufflingAccountAuthToken','authToken','protocol:2','trade:commit','server-authoritative'])if(!client.includes(token))fail(`Trade client missing ${token}`);for(const forbidden of ['availableCount:F().availableCount(id)','trade:prepared','trade:prepare'])if(client.includes(forbidden))fail(`Trade client still trusts legacy flow: ${forbidden}`);if(!process.exitCode)ok('Trade client authenticates and waits for authoritative server commit');
const server=fs.readFileSync(`${root}/server/trade.js`,'utf8');for(const token of ['accountAuth','inventoryStore','trade_auth_required','same_account','inventoryStore.exchange','serverAuthoritative:true','starter_locked'])if(!server.includes(token))fail(`Trade server missing ${token}`);for(const forbidden of ['m.availableCount','trade:prepare'])if(server.includes(forbidden))fail(`Trade server still trusts legacy client inventory: ${forbidden}`);if(!process.exitCode)ok('Trade server owns authentication, inventory validation and settlement');
const store=fs.readFileSync(`${root}/server/trade_inventory_store.js`,'utf8');for(const token of ['BEGIN','pg_advisory_xact_lock','FOR UPDATE','inventory_missing','puffling_trade_results','COMMIT','ROLLBACK'])if(!store.includes(token))fail(`Trade inventory store missing ${token}`);if(!process.exitCode)ok('Trade inventory settlement is transactional and idempotent');
const bootstrap=fs.readFileSync(`${root}/server/bootstrap.js`,'utf8'),index=fs.readFileSync(`${root}/server/index.js`,'utf8');if(!bootstrap.includes('tradeInventoryStore.init()')||!bootstrap.includes('PufflingTradeInventoryStore'))fail('Trade inventory store is not initialized by server bootstrap');if(!index.includes('accountAuth,inventoryStore:tradeInventoryStore'))fail('Trade service does not receive shared auth and inventory store');
const loader=fs.readFileSync(`${root}/game.js`,'utf8');if(!loader.includes("'js/puffling_trade.js'"))fail('Puffling trade module is not active in game loader');else ok('Puffling Trade v2 remains active in game loader');
if(process.exitCode)process.exit(process.exitCode);console.log('✅ Server-authoritative Puffling Trade v2 checks passed');
